### ISSUE TITLE
Error executing 'postInstallation': Unable to start com.bitnami.postgresql: pg_ctl: could not start server

### ISSUE THREAD

**Issue by OneCent** [bitnami/bitnami-docker-postgresql#102]
**Description**

Try to run bitnami/postgresql:latest with a volume attached in Windows 10

**Steps to reproduce the issue:**
with a fresh and empty e:\entwicklung\myjenkins\postgresql_data

1.  `docker run --rm -v e:\entwicklung\myjenkins\postgresql_data:/bitnami bitnami/postgresql:latest`

**Describe the results you received:**
```
Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': Unable to start com.bitnami.postgresql: pg_ctl: could not start server
Examine the log output.
: pg_ctl: could not start server
Examine the log output.
```
**Additional information you deem important (e.g. issue happens only occasionally):**

This happens with Windows 10. I have no problems with OS X.
The directory available and postgresql creates his datafile.
Without the -v postgresql does start.

**Version**

- Output of `docker version`:
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     true
 Kubernetes:
  Version:          Unknown
  StackAPI:         Unknown
```
- Output of `docker info`:
```
Containers: 35
 Running: 17
 Paused: 0
 Stopped: 18
Images: 46
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155d589645
ID: 6F24:VAOW:TQDN:VUD5:SKKN:MKXW:34JL:LI2D:ZL2Y:LLZF:2D3B:E7L4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 68
 Goroutines: 86
 System Time: 2018-12-31T13:20:25.3895954Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```
- Output of `docker-compose version` (if applicable):
```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by carrodher** [comment]
Hi,
I found other similar issues with Windows and volumes, for example, this one: https://github.com/docker/for-win/issues/2048

Can you try using `docker-compose`? In the following link, you can find the information https://github.com/bitnami/bitnami-docker-postgresql#persisting-your-database about how to do the same action using `docker run` or `docker-compose up`

**Comment by OneCent** [comment]
Hi,
I get the same error with docker-compose up

**Comment by andresbono** [comment]
Hi @OneCent, can you add the following environment variable to the docker-compose? It will show verbose trace that may show the source of the issue:

```diff 
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:10'
    environment:
+     - NAMI_LOG_LEVEL=trace
    volumes:
      - E:\entwicklung\myjenkins\postgresql_data:/bitnami

volumes:
  postgresql_data:
    driver: local
```

**Comment by OneCent** [comment]
Hi @andresbono, @carrodher 
It looks like it has something to do with the permission

postgresql_1  | nami    INFO  Initializing postgresql
postgresql_1  | postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgresql_1  | postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgresql_1  | postgre INFO  ==> Deploying PostgreSQL from scratch...
postgresql_1  | postgre TRACE [prepareDataToPersist] Preparing /opt/bitnami/postgresql/data to persist in /bitnami/postgresql/data
postgresql_1  | postgre TRACE [runProgram] Executing: /opt/bitnami/postgresql/bin/initdb -E UTF8 -D /opt/bitnami/postgresql/data -U "postgres"
postgresql_1  | postgre TRACE [runProgram] Executing: null /opt/bitnami/postgresql/bin/pg_ctl start -w -D /opt/bitnami/postgresql/data -l /opt/bitnami/postgresql/logs/postgresql.log -o '--config-file=/opt/bitnami/postgresql/conf/postgresql.conf --external_pid_file=/opt/bitnami/postgresql/tmp/postgresql.pid --hba_file=/opt/bitnami/postgresql/data/pg_hba.conf'
postgresql_1  | postgre TRACE Last log entries:
postgresql_1  | 2019-01-03 16:27:55.834 GMT [55] FATAL:  data directory "/opt/bitnami/postgresql/data" has wrong ownership
postgresql_1  | 2019-01-03 16:27:55.834 GMT [55] HINT:  The server must be started by the user that owns the data directory.
postgresql_1  |
postgresql_1  | Error executing 'postInstallation': Unable to start com.bitnami.postgresql: pg_ctl: could not start server
postgresql_1  | Examine the log output.
postgresql_1  | : pg_ctl: could not start server
postgresql_1  | Examine the log output.
postgresql_1  |
postgresql_1  | nami    TRACE Error: Error executing 'postInstallation': Unable to start com.bitnami.postgresql: pg_ctl: could not start server
postgresql_1  | Examine the log output.
postgresql_1  | : pg_ctl: could not start server
postgresql_1  | Examine the log output.
postgresql_1  |
postgresql_1  |     at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:162:15)
postgresql_1  |     at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
postgresql_1  |     at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
postgresql_1  |     at Service.$app.postInstallation (/.nami/components/com.bitnami.postgresql/main.js:56:12)
postgresql_1  |     at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
postgresql_1  |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
postgresql_1  |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
postgresql_1  |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
postgresql_1  |     at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
postgresql_1  |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)

**Comment by aerotog** [comment]
I am running into the same issue. This may be a red herring, but I think it might be related to the fact that the entry point is running under USER 1001 which does not exist in the base image.

When I shell into the container, I see the following:

I have no name!@pgtest-64d48f8975-hv5ht:/$ id
`uid=1001 gid=0(root) groups=0(root)`
I have no name!@pgtest-64d48f8975-hv5ht:/$ cat /etc/passwd                                 
`root:x:0:0:root:/root:/bin/bash`
`daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin`                                   
`bin:x:2:2:bin:/bin:/usr/sbin/nologin`
`sys:x:3:3:sys:/dev:/usr/sbin/nologin`
`sync:x:4:65534:sync:/bin:/bin/sync`
`games:x:5:60:games:/usr/games:/usr/sbin/nologin`                                            
`man:x:6:12:man:/var/cache/man:/usr/sbin/nologin`                                            
`lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin`
`mail:x:8:8:mail:/var/mail:/usr/sbin/nologin`
`news:x:9:9:news:/var/spool/news:/usr/sbin/nologin`                                          
`uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin`                                        
`proxy:x:13:13:proxy:/bin:/usr/sbin/nologin`
`www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin`                                      
`backup:x:34:34:backup:/var/backups:/usr/sbin/nologin`                                       
`list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin`                              
`irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin`                                           
`gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin`          
`nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin`                                 
`_apt:x:100:65534::/nonexistent:/bin/false`
`bitnami:x:1000:1000::/home/bitnami:/bin/bash`
I have no name!@pgtest-64d48f8975-hv5ht:/$

Is it expected for /etc/passwd to have user 1000 defined while the image is trying to use 1001?

**Comment by aerotog** [comment]
The bitnami user is defined [here](https://github.com/bitnami/minideb-extras/blob/0e52c95e0bf5c0b7b8f7c56ca65933bb26601b6a/stretch/Dockerfile#L9). The UID is not explicitly defined so it can change depending on the prior build/image steps.

**Comment by aerotog** [comment]
I'm testing in both Docker for Windows and Amazon EKS. It works better in EKS, but I'm still seeing odd behavior in the latest release. I can open a separate issue if you think it's unrelated. For instance, running bitnami/postgresql:latest in either D4Win or EKS results in this same matching behavior:
 ```bash
λ kubectl run pg --image bitnami/postgresql:latest
deployment.apps "pg" created
...snip...
λ kubectl exec pg-7cf9594bbc-n5j2d -it /bin/bash
I have no name!@pg-7cf9594bbc-n5j2d:/$ psql
psql: local user with ID 1001 does not exist
```

It seems very odd to me that the image it trying to run under a UID that doesn't exist.

**Comment by aerotog** [comment]
@OneCent it looks like this issue is very similar to helm/charts#9093. I added a long comment over there with links explaining the details but basically Docker for Windows doesn't support mounting volumes to Windows drives when certain permissions/ownership are needed by the container.

To get around this, you need to use a file on the Linux VM host that Docker for Windows uses (MobyLinuxVM in Hyper-V by default). You can do this by running the following command:
`λ docker run --rm -v /tmp:/bitnami bitnami/postgresql:latest`

The issue with mounting Windows drives to Docker/Kubernetes volumes is a known limitation of Docker for Windows. There was a closed ticket for it which said there are no plans to fix it.

The missing user for UID 1001 looks like its not a direct cause of this so ignore my previous comments, but I may open my own issue unless I find a good explanation for what I'm seeing.

**Comment by tompizmor** [comment]
@aerotog 

> It seems very odd to me that the image it trying to run under a UID that doesn't exist.

This is expected and it is a characteristic of non-root containers. Some kubernetes distributions like Openshift runs the container with UUID totally random so the image needs to be prepared to run as a non existent user. 

>I have no name!@pg-7cf9594bbc-n5j2d:/$ psql
psql: local user with ID 1001 does not exist

In this case, you need to specify the database user: `$ psql -U postgres`

>Edit: I have been using this image prior to the holiday break for a couple months and was having zero issues. I only started seeing this behavior yesterday when I pulled new images. I recently cleared my Docker image cache so I don't have old copies to compare against.

Probably the postgresql image was moved to the non-root approach during that interval of time. Please let us know the issues you may find and we will try to help.

**Comment by madhupnvl** [comment]
Hi All,

Any solution ?
Now Docker for Windows is updated as Docker Desktop, but still same issue.

We are unable to create a PV/PVC with persistence.enabled=true.

**Comment by tompizmor** [comment]
Hi @madhupnvl,

I am afraid that regarding this topic, Docker Desktop has the same limitations than Docker for Windows. 

Have you considered running the PostgreSQL chart as root? You would need to install the chart with the following options:

```
--set securityContext.fsGroup=0 --set securityContext.runAsUser=0
```

If you run the container as root you should not have permissions errors in the volume.

**Comment by madhupnvl** [comment]
Hi @tompizmor ,

I tried with running with --set securityContext.fsGroup=0 --set securityContext.runAsUser=0, but it is not worked out. Still same issue.

**Comment by tompizmor** [comment]
Can you please share which error do you get?
Can you also share the output of `kubectl describe pod <YOUR_POSTGRES_POD>`?

**Comment by madhupnvl** [comment]
@tompizmor 
ERROR Unable to start com.bitnami.postgresql: pg_ctl: could not start server
Examine the log output. 

Pod has unbound immediate PersistentVolumeClaims
Readiness probe failed: 10.1.14.145:5432 - no response
Back-off restarting failed container 

$ kubectl describe pod derm-postgresql-postgresql-0
Error from server (NotFound): pods "derm-postgresql-postgresql-0" not found

**Comment by andresbono** [comment]
It seems the pod with name `derm-postgresql-postgresql-0` doesn't exist. Was it a typo? Can you check the existing pods with the following command?:

```
kubectl get pods
```

**Comment by aerotog** [comment]
@madhupnvl I bet you are running into the same issue I documented above. Please see my comments [here ](https://github.com/bitnami/bitnami-docker-postgresql/issues/102#issuecomment-451588696)and [here](https://github.com/helm/charts/issues/9093#issuecomment-451571490).

The gist is that this Postgres image requires permissions that are incompatible with Docker Desktop for Windows. The two options are to:
1) Disable persistence
2) Mount a volume in the Linux VM instead of the Windows host path

See my linked comments for more details.

**Comment by mertmetin** [comment]
I am having the same issue. Any suggestions?

**Comment by mertmetin** [comment]
Found the solution here: https://github.com/bitnami/bitnami-docker-discourse/issues/34

It seems discourse doesn't work with Postgresql version 10.x.

This fixes the problem:
    image: 'bitnami/postgresql:9.6'

**Comment by carrodher** [comment]
It shouldn't affect, I mean, according to https://github.com/discourse/discourse/blob/master/docs/INSTALL.md#software-requirements Discourse requires Postgresql 10+

Maybe you're facing a similar issue than the one described [here](https://github.com/bitnami/bitnami-docker-postgresql/issues/102#issuecomment-482708114), but the change is not related to the postgresql version itself but related to changes in the image

**Comment by mertmetin** [comment]
I think you are right.

**Comment by javsalgar** [comment]
Hi,

However, could you confirm that with the image version 9.6 you do not find the issue?

**Comment by mertmetin** [comment]
@carrodher I am running it with 9.6 and everything seems fine.

@javsalgar I discovered the real problem I had. The username and password were different for var parameters below:
POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME
POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD

and 

DISCOURSE_POSTGRESQL_USERNAME
DISCOURSE_POSTGRESQL_PASSWORD

**Comment by javsalgar** [comment]
Hi,

So, just to make sure. Is the issue solved then?

**Comment by javsalgar** [comment]
Hi,

Thanks for sharing :)
