### ISSUE TITLE
Explanation request for running as non-existent user

### ISSUE THREAD

**Issue by aerotog** [bitnami/bitnami-docker-postgresql#103]
This stems from a conversation in #102. It isn't a bug request per se, but the last few days I've been trying to understand a design decision in this image. I would truly appreciate some insight into the why/how of the following.

This image uses uid 1001 when running. This is intentional based on [this comment](https://github.com/bitnami/bitnami-docker-postgresql/issues/102#issuecomment-451379008):
```
USER 1001
ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "/run.sh" ]
```

However, based on the parent image `bitnami/minideb-extras` and the nami code itself, it seems the intent is that the application be run under user `bitnami`. The `bitnami` user has a uid of 1000. In fact, **there is no user in the image with a uid of 1001**. 

This results in the following odd behavior:
```bash
λ docker exec -it 0e3bc9977d94 /bin/bash                                                  
I have no name!@0e3bc9977d94:/$ psql                                                      
psql: local user with ID 1001 does not exist                                                                                                                    
I have no name!@0e3bc9977d94:/$ su postgres                                               
su: Cannot determine your user name.                                                      
I have no name!@0e3bc9977d94:/$ id                                                        
uid=1001 gid=0(root) groups=0(root)                                                       
I have no name!@0e3bc9977d94:/$ cat /etc/passwd                                           
root:x:0:0:root:/root:/bin/bash                                                           
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin                                           
bin:x:2:2:bin:/bin:/usr/sbin/nologin                                                      
sys:x:3:3:sys:/dev:/usr/sbin/nologin                                                      
sync:x:4:65534:sync:/bin:/bin/sync                                                        
games:x:5:60:games:/usr/games:/usr/sbin/nologin                                           
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin                                           
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin                                              
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin                                               
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin                                         
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin                                       
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin                                                
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin                                      
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin                                      
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin                             
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin                                          
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin         
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin                                
_apt:x:100:65534::/nonexistent:/bin/false                                                 
bitnami:x:1000:1000::/home/bitnami:/bin/bash                                              
```

There are workarounds like specifying a different user when running docker exec commands but this requirement seems wrong to me. In addition, having the image run as a non-existent user seems to reek havoc with permissions when change configuration via helm.

All that said, I'd appreciate answers to the following questions:
- Why and how is this image running under a non-existent user (uid 1001)? 
- Should it not be using the bitnami user (uid 1000)?
- If this is truly intentional, can we create a user with uid 1001 so the odd behavior shown before is avoided? I think this would cut down on issues like #87.

**Comment by tompizmor** [comment]
I already partially replied this questions at https://github.com/bitnami/bitnami-docker-postgresql/issues/102#issuecomment-451883271.

> Why and how is this image running under a non-existent user (uid 1001)?

Why? The main reason is in order to the image to be compatible with OpenShfit. By default, this kubernetes distributions run all the containers as non-root with a random UUID. 
And how? If you launch a docker container with a non-existent user this user belongs to the `root` group. So in theory all you need to do is configure the permissions for the `root` group and your application will be able to run as user 1001. 


> Should it not be using the bitnami user (uid 1000)?

It could run as `bitnami` or for example we could have created another non-root user called `postgres`. However, if we force the container to run as an specific and existent user then it won't work by default on OpenShift.

> If this is truly intentional, can we create a user with uid 1001 so the odd behavior shown before is avoided? I think this would cut down on issues like #87.

I am not sure if this could interfere with the group permissions configuration or we may not be noticing possible issues while running on OpenShift. In any case, I would share this option internally and we will evaluate it.

**Comment by aerotog** [comment]
Thank you for the answers!

I should have done a bit more research on this. There is an existing ticket on a different Bitnami issue bitnami/bitnami-docker-redis#86. @prydonius links to the [Open Shift best practices](https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines). Under `Support Arbitrary User IDs` it explains why arbitrary user IDs are used. This seems to be unique to Open Shift as I haven't found/seen this behavior in any other Kubernetes implementation.

Running as non-root makes perfect sense to me. And while it does sound odd to me that containers can/will run applications under a non-existing user, it sounds like it shouldn't actually be a problem. It is a known pattern which has a few side effects like [not having a $HOME or user name](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15).

I do think there would be benefits to creating a user for ID 1001 while maintaining the non-root security, but based on what I've read, it shouldn't be necessary to run/meet best practices.

Since this is intended and known design, I'm closing this issue.

**Comment by Ademord** [comment]
Hello! I didn't understand your solution.
If we're supposed to run a container (jupyter notebook) and we get the error ```su: Cannot determine your user name.```, how do we add the necessary user and permissions to run the container commands?

**Comment by miguelaeh** [comment]
Hi @Ademord ,
To run container commands you don't need to change the user. If you have the uid 1001 without name that error is expected. You can run commands normally but you cannot change the user with `su`.

**Comment by Deepwalker** [comment]
I cant run commands locally actually when using helm: ```I have no name!@postgresql-0:/$ psql
psql: local user with ID 1001 does not exist```

**Comment by aerotog** [comment]
@Deepwalker When running psql commands, specify the user you configured in Postgres by using the -U flag.

**Comment by cawoodm** [comment]
I am also trying to run `psql` or `dropdb` inside the postgres pod and failing with `dropdb: error: local user with ID 1001 does not exist`. Since I don't know the passwords of any users inside the pod I don't see how `-U` could help.

How can I run `psql` inside the pod?

**Comment by rafariossaa** [comment]
Hi @cawoodm ,
  Would you mind to open a new issue ? This way we can properly track it and help you .

**Comment by cawoodm** [comment]
#335 👍

**Comment by rafariossaa** [comment]
Thanks.
