### ISSUE TITLE
Add PostGIS support

### ISSUE THREAD

**Issue by dene14** [bitnami/bitnami-docker-postgresql#106]
That was already touched in #85 but can we actually add postgis into the image?

PostGIS is quite popular extension for postgres and used in 30% (if not more) installations across the globe. Now that helm chart in stable repository has quite tight dependency on Bitnami docker image it's quite hard to get it working w/o doing a lot of extra work which will be done in private forks.

For e.g. stable/postgresql=0.13.1 works just fine with `mdillon/postgis` image (even alpine version).

**Comment by javsalgar** [comment]
Hi! Thanks for reporting.  We are going to evaluate whether adding postgis to our current container or creating a new one with that extension (it will depend on the resulting container size). We will update this ticket when we have more information

**Comment by Amithpn** [comment]
Container with postgis support is coming anytime soon?

**Comment by carrodher** [comment]
We have at task included in our backlog. Although there is no release date for this task, it will be considered for future application versions

**Comment by notamargetic** [comment]
Any updates or is this still backlogged? - Thanks!

**Comment by beltran-rubo** [comment]
PostGIS is already included into the Bitnami PostgreSQL container image, see the supported versions at https://github.com/bitnami/bitnami-docker-postgresql#9615-r82-9615-ol-7-r92-9615-centos-7-r91-10100-r82-10100-ol-7-r90-10100-centos-7-r91-1150-r80-1150-centos-7-r87-1150-ol-7-r92-1200-r11-1200-centos-7-r17-and-1200-ol-7-r17
