### ISSUE TITLE
Add ability to pass initdb args via env

### ISSUE THREAD

**Issue by alebabai** [bitnami/bitnami-docker-postgresql#107]
**Description**

Official image of postgresql has way to override initdb args.
>**POSTGRES_INITDB_ARGS**
This optional environment variable can be used to send arguments to postgres initdb. The value is a space separated string of arguments as postgres initdb would expect them. This is useful for adding functionality like data page checksums: -e POSTGRES_INITDB_ARGS="--data-checksums". 
It would be nice to have such option here.

Example use-case is to change database locale.

**Comment by alebabai** [comment]
Also described here 
https://community.bitnami.com/t/initdb-args-for-bitnami-postgresql-docker-images/62402/3

**Comment by juan131** [comment]
Hi @alebabai 

You're right! There's no way to override them currently on this image. I'll open an internal task to include this feature! Thanks so much for reporting!

cc/ @tompizmor @javsalgar

**Comment by alebabai** [comment]
@juan131  thanks!

**Comment by juan131** [comment]
This feature was included in the version **9.6.11-r66**. More information can be found in the link below:

https://github.com/bitnami/bitnami-docker-postgresql#9611-r66-9611-ol-7-r83-1060-r68-1060-ol-7-r83-1110-r62-and-1110-ol-7-r79
