### ISSUE TITLE
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'

### ISSUE THREAD

**Issue by willzhang** [bitnami/bitnami-docker-postgresql#111]
```
docker run -d --name postgresql-master \
    --network app-tier \
    -p 5432:5432 \
    --user $(id -u):$(id -g) \
    -e POSTGRESQL_REPLICATION_MODE=master \
    -e POSTGRESQL_USERNAME=postgres \
    -e POSTGRESQL_PASSWORD=password123 \
    -e POSTGRESQL_DATABASE=my_database \
    -e POSTGRESQL_REPLICATION_USER=my_repl_user \
    -e POSTGRESQL_REPLICATION_PASSWORD=my_repl_password \
    -v /postgresql-master/bitnami/:/bitnami \
    bitnami/postgresql:latest	
```

```
[root@localhost ~]# docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
1a7601fa5c2e        bitnami/postgresql:latest   "/app-entrypoint.s..."   2 seconds ago       Up 2 seconds        0.0.0.0:5432->5432/tcp   postgresql-master
[root@localhost ~]# cd /postgresql-master/
[root@localhost postgresql-master]# ll
total 0
drwxr-xr-x 2 root root 6 Feb 22 14:54 bitnami
[root@localhost postgresql-master]# cd bitnami/
[root@localhost bitnami]# ll
total 0
[root@localhost bitnami]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

```
[root@localhost bitnami]# docker logs -f postgresql-master 

Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/postgresql'
[root@localhost bitnami]# 
```

**Comment by javsalgar** [comment]
Hi,

You can exec inside the container and execute psql inside. Which container platform are you using?

**Comment by willzhang** [comment]
you should delete POSTGRESQL_USERNAME=my_user first
then
docker run -it --rm \
   --network app-tier \
   bitnami/postgresql:latest psql -h postgresql-master -U postgres -p 5432 -d postgres

**Comment by willzhang** [comment]
i resolve it 

delete POSTGRESQL_USERNAME=my_user

docker run -it --rm \
   --network app-tier \
   bitnami/postgresql:latest psql -h postgresql-master -U postgres -p 5432 -d postgres

**Comment by willzhang** [comment]
i have anthor problem, how to check conf?

[root@iZ4kgzm2ne37e4Z ~]# cat postgresql.auto.conf 
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.

**Comment by willzhang** [comment]
here is the best way resolve the problem:	--user $(id -u):$(id -g) \

```
docker run -d --name postgresql-master \
    --network app-tier \
    -p 5432:5432 \
	--user $(id -u):$(id -g) \
    -e POSTGRESQL_REPLICATION_MODE=master \
	-e POSTGRESQL_USERNAME=postgres \
    -e POSTGRESQL_PASSWORD=password123 \
    -e POSTGRESQL_DATABASE=my_database \
    -e POSTGRESQL_REPLICATION_USER=my_repl_user \
    -e POSTGRESQL_REPLICATION_PASSWORD=my_repl_password \
    -v /postgresql-master/bitnami/:/bitnami \
    bitnami/postgresql:latest
```

**Comment by willzhang** [comment]
close it thanks

**Comment by willzhang** [comment]
how can i read the configuration?

[root@localhost data]# ll
total 32
drwx------ 6 1001 root   54 Feb 22 15:19 base
drwx------ 2 1001 root 4096 Feb 22 15:19 global
drwx------ 2 1001 root    6 Feb 22 15:18 pg_commit_ts
drwx------ 2 1001 root    6 Feb 22 15:18 pg_dynshmem
-rw-r--r-- 1 root root 4646 Feb 22 15:19 pg_hba.conf
-rw-r--r-- 1 root root 1636 Feb 22 15:18 pg_ident.conf
drwx------ 4 1001 root   68 Feb 22 15:24 pg_logical
drwx------ 4 1001 root   36 Feb 22 15:18 pg_multixact
drwx------ 2 1001 root   18 Feb 22 15:19 pg_notify
drwx------ 2 1001 root    6 Feb 22 15:18 pg_replslot
drwx------ 2 1001 root    6 Feb 22 15:18 pg_serial
drwx------ 2 1001 root    6 Feb 22 15:18 pg_snapshots
drwx------ 2 1001 root    6 Feb 22 15:19 pg_stat
drwx------ 2 1001 root   63 Feb 22 15:28 pg_stat_tmp
drwx------ 2 1001 root   18 Feb 22 15:18 pg_subtrans
drwx------ 2 1001 root    6 Feb 22 15:18 pg_tblspc
drwx------ 2 1001 root    6 Feb 22 15:18 pg_twophase
-rw------- 1 1001 root    3 Feb 22 15:18 PG_VERSION
drwx------ 3 1001 root   60 Feb 22 15:18 pg_wal
drwx------ 2 1001 root   18 Feb 22 15:18 pg_xact
-rw------- 1 1001 root   88 Feb 22 15:18 postgresql.auto.conf
-rw------- 1 1001 root  253 Feb 22 15:19 postmaster.opts
-rw------- 1 1001 root   85 Feb 22 15:19 postmaster.pid
[root@localhost data]# cat postgresql.auto.conf 
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
[root@localhost data]#

**Comment by javsalgar** [comment]
Hi,

I see that you are setting a different user from 1001, could you explain your use case? The configuration files are in /opt/bitnami/postgresql/conf

**Comment by dmytrocx75** [comment]
Tried the above suggested solution on SentOS7 - didn't work, as it can't open /.nami.json file
This works https://github.com/7cart/7cart/wiki/Troubleshooting

**Comment by wochinge** [comment]
would it make sense to own the whole data directory at startup time?

**Comment by javsalgar** [comment]
@wochinge are you also using an user different from 1001?

**Comment by wochinge** [comment]
@javsalgar If running on OpenShift, OpenShift will pick a random user id to run the container. Only constant is that the arbitrary user will be part of the `root` usergroup: https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines

**Comment by javsalgar** [comment]
The thing is that, during startup, it is that random user that creates the data folder, so there shouldn't be a problem with that. Could you elaborate a bit more how you deploy Postgres in Openshift and the issue you found?

**Comment by mo-miisol-ltd** [comment]
I hit similar issue today , struggling to find the root cause. 
This is DOCKER-EE environment. 
**Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/postgresql/.initialized'**
===========
Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
**Error executing 'postInstallation': EPERM: operation not permitted, utime '/bitnami/postgresql/.initialized'**
=================

**Comment by javsalgar** [comment]
Hi,

Could you add more details about the docker-compose.yml file you are using? Are you bind-mounting folders from your filesystem?

**Comment by mo-miisol-ltd** [comment]
Hi , 
issue resolved - it was due to Azure storage class - it was using azurefile by defult , had to change it to 
azuredisk. 

persistence:
    enabled: true
    storageClass: azuredisk
  service:
    port: 5432

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue. If you have more questions, please do not hesitate to let us know

**Comment by wochinge** [comment]
> The thing is that, during startup, it is that random user that creates the data folder, so there shouldn't be a problem with that. Could you elaborate a bit more how you deploy Postgres in Openshift and the issue you found?

Thanks you're totally right. Had a misunderstanding there 🙂
