### ISSUE TITLE
Cannot send initdb variables to set default collation when using the postgresql Helm Chart 

### ISSUE THREAD

**Issue by drbityz** [bitnami/bitnami-docker-postgresql#112]
**Description**

Creating a helm chart which depends upon the postgres helm chart, then creating a database with an en_US.UTF-8 encoding fails.  The chart brings up the database fine and it is usable, but only with the C collation.  Ultimately, the problem is that initdb is not being called with the correct arguments.

**Steps to reproduce the issue:**

1. create a helm chart with the following requiremnts.yaml

```yaml
    dependencies:
    - name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 3.11.6
```
and the following Values.yaml

```yaml
    postgresql:
      postgresqlInitdbArgs: --locale=en_US.UTF-8 --debug
```

2. view the postgresql logs with kubectl or the k8s dashboard.  Note that the initdb portion of the log does not show any evidence of the --debug flag

3. use any mechanism to create a database:

```
    CREATE DATABASE mydb OWNER myuser ENCODING 'UTF-8' LC_COLLATE 'en_US.utf8' LC_CTYPE = 'en_US.utf8';
```

**Describe the results you received:**

The method I use to create the database is to use an init container to run a psql script with the line above in it.  The error I get in the log is

```
   psql:/scripts/create_db.psql:4: ERROR:  new collation (en_US.utf8) is incompatible with the collation of the template database (C)
    HINT:  Use the same collation as in the template database, or use template0 as template.
```

**Describe the results you expected:**

I expected a successful database creation.

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking into this I find:

1) in the [docker file](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/10/debian-9/Dockerfile) 
    1.1) postgres is installed.  instead of an official postgres image being used.
    1.2) the en_GB and en_US locales are created.  

2) in the [entrypoint](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/10/debian-9/rootfs/app-entrypoint.sh)
    2.1) env variables are duplicated so that the bitname versions (which have "POSTGRES_" as can be seen in the [stateful set definition](https://github.com/helm/charts/blob/master/stable/postgresql/templates/statefulset.yaml) ) are available through the official versions (which have "POSTGRESQL_" )
    2.2) Note that the POSTGRES_INITDB_ARGS env variable does not have an alias because the [postgres initdb does not take any similar environment variables.](https://www.postgresql.org/docs/10/app-initdb.html)
    2.3) initdb is apparantly started by 

    ```
    nami_initialize postgresql
    ```

    which is opaque to me.   **This is likely where the location of the failure to marshal arguments from the environment variable.**

So where does ```nami_initialize``` come from?  The Dockerfile indicates 

```
FROM bitnami/minideb-extras:stretch-r296
```

which brings us to the [Dockerfile for bitnami/minideb-extras:stretch-r296](https://github.com/bitnami/minideb-extras/blob/stretch-r296/stretch/Dockerfile)

This seems to be downloading nami:

```
ENV NAMI_VERSION 1.0.0-1

RUN cd /tmp && \
  curl -sSLO https://nami-prod.s3.amazonaws.com/tools/nami/releases/nami-$NAMI_VERSION-linux-x64.tar.gz 
```

but nowhere do I see the origin of nami_initialize.

I am stumped.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 51
 Running: 46
 Paused: 0
 Stopped: 5
Images: 248
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: jjii7aqkbtlrxqjelrnkz0cly
 Is Manager: true
 ClusterID: ewu96gl2y7tkvcuiidgzzzpts
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 5.554GiB
Name: linuxkit-00155db96009
ID: 3CGU:5A4F:OHGX:S56O:CFRT:5GAG:ZZVW:CSG3:VIX3:CS2X:UILQ:KWCN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 168
 Goroutines: 267
 System Time: 2019-02-26T21:09:42.8889872Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
Not applicable
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

```
helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", 
Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", 
Platform:"linux/amd64"}
```

**Comment by drbityz** [comment]
If you can point me to the code for ```nami_initialize```, I can take the analysis further.   Otherwise, any help would be appreciated.  

This issue is related to https://github.com/bitnami/bitnami-docker-postgresql/issues/74 which was resolved by creating the locales in the dockerfile (as I mentioned above), and to https://github.com/bitnami/bitnami-docker-postgresql/issues/107 which acknowledges the issue but leaves the reader hanging.

Any update you could provide would be appreciated.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the detailed report. Thanks to this, I just saw that, in the container logic 
https://github.com/bitnami/bitnami-docker-postgresql/blob/master/10/debian-9/rootfs/app-entrypoint.sh, we are missing the instruction to convert the variable POSTGRES_INITDB_ARGS to POSTGRESQL_INITDB_ARGS. I am releasing a new container that fixes the issue. 

As you are interested in the logic behind the initialization, you can find it inside the container in the following path

`/.nami/components/com.bitnami.postgresql`

There you will see some NodeJS files (main.js and helpers.js) which contain the logic to initialize. We are in the process of transitioning to bash, in order to reduce the opaqueness that you currently found. Examples of bash containers are the Bitnami Redis container: https://github.com/bitnami/bitnami-docker-redis/tree/master/5.0/debian-9/rootfs

I will let you know when we have the fixed version of the container available.

**Comment by javsalgar** [comment]
Just a note to let you know that the new version of the container is available (`r12`)

https://github.com/bitnami/bitnami-docker-postgresql/commit/c502c942ca5aba6b26a23b2f1ebd70094aac9d98
