### ISSUE TITLE
Fails to open port with custom configuration (using stable/postgresql helm chart)

### ISSUE THREAD

**Issue by erdarun** [bitnami/bitnami-docker-postgresql#114]
**Description**

When using the `stable/postgresql` Helm chart (3.11.7), app (10.7.0) and custom configuration, PostgreSQL fails to open port 5432. This is with setting custom configuration using `postgresqlConfiguration`.

**Steps to reproduce the issue:**

```shell
helm install stable/postgresql \
  --set postgresqlConfiguration.max_connections=5000
```

**Describe the results you received:**

The log contains:

```
nami    INFO  Initializing postgresql
postgre INFO  ==> postgresql.conf file found...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
postgre INFO  ==> Creating database anchore...
postgre INFO  ==> Creating user "anchoreengine"...
postgre INFO  ==> Granting access to "anchoreengine" to the database anchore...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Persisted data and properties have been restored.
postgre INFO     Any input specified will not take effect.
postgre INFO   This installation requires no credentials.
postgre INFO  ########################################################################
postgre INFO
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql...
2019-02-28 20:15:38.828 GMT [100] LOG:  aborting any active transactions
2019-02-28 20:15:38.829 GMT [100] LOG:  worker process: logical replication launcher (PID 107) exited with exit code 1
2019-02-28 20:15:38.830 GMT [102] LOG:  shutting down
2019-02-28 20:15:38.900 GMT [100] LOG:  database system is shut down
2019-02-28 20:15:40.600 GMT [156] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2019-02-28 20:15:40.600 GMT [156] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2019-02-28 20:15:40.600 GMT [156] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2019-02-28 20:15:40.605 GMT [156] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-02-28 20:15:40.814 GMT [158] LOG:  database system was shut down at 2019-02-28 20:15:38 GMT
2019-02-28 20:15:40.819 GMT [156] LOG:  database system is ready to accept connections
```
**Describe the results you expected:**

PostgreSQL Port should be opened which is closed now.

**Additional information you deem important (e.g. issue happens only occasionally):**

Appears to be reliably reproducible on the latest helm chart version 3.11.7 and 10.7.0 PostgreSQL versions.

**Version**

* Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
* Output of `docker info`:

[probably not relevant, but let me know and I'll include it]

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Kubernetes cluster built with openstack cloud environment. Kubernetes version v1.13.2

**Comment by erdarun** [comment]
Similar to #101 which seems to be closed but issue not yet fixed.

**Comment by erdarun** [comment]
@marcosbc Please check and revert on it

**Comment by andresbono** [comment]
Hi @erdarun,

Can you use `postgresqlExtendedConf` instead? In the [README.md](https://github.com/helm/charts/blob/master/stable/postgresql/README.md):

| Parameter                                     | Description                                                                                                            | Default                                                     |
| --------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------- |
| `postgresqlConfiguration`                     | Runtime Config Parameters                                                                                              | `nil`                                                       |
 | `postgresqlExtendedConf`                      | Extended Runtime Config Parameters (appended to main or default configuration)                                         | `nil`                                                       |

The command will be like this one:

```
helm install stable/postgresql --set postgresqlExtendedConf.max_connections=5000
```

Hope it helps!

**Comment by erdarun** [comment]
Hi @andresbono 

It works but logs show continuous warning messages like below,

> 2019-03-12 08:43:42.565 GMT [325] WARNING:  there is no transaction in progress
> 2019-03-12 08:43:42.565 GMT [650] WARNING:  there is no transaction in progress
> 2019-03-12 08:43:42.565 GMT [673] WARNING:  there is no transaction in progress

**Comment by andresbono** [comment]
Great that you could make it work!

About the warning that the logs show, does it happened right after you deployed the helm chart? How are you sending the queries to PostgreSQL? Could it be related to the client part of your setup?

**Comment by erdarun** [comment]
@andresbono Yes it happened right after deployment of helm chart from the start of DB.

**Comment by andresbono** [comment]
Hi @erdarun, we can't reproduce it. How are you sending the queries to PostgreSQL? Do you think it could it be related to the client part of your setup?
