### ISSUE TITLE
Change default value of checkpoint_segments to at least 10 for better performance?

### ISSUE THREAD

**Issue by HCHCHH** [bitnami/bitnami-docker-postgresql#117]
The Postgre [official document](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server) recommends to set **checkpoint_segments** to at least 10, which improves the performance.
"**Unless you're running on a very small configuration, you'll almost certainly be better setting this to at least 10, which also allows usefully increasing the completion target.** ". 

I wonder if the default need to be changed for performance concern. Thanks.

**Comment by tompizmor** [comment]
Hi @HCHCHH,

The `checkpoint_segments` configuration parameter is deprecated since postgresql 9.5 and we are providing postgresql 9.6, 10 and 11 so that option is not being used at all.
I checked the configuration files and it is not present.
