### ISSUE TITLE
MAJOR CHANGE: Move PostgreSQL container to bash

### ISSUE THREAD

**Issue by javsalgar** [bitnami/bitnami-docker-postgresql#125]
We are working on moving our containers initialization logic from nami to bash. The aim of this is to improve both transparency and performance of our containers. Examples of Bitnami containers in bash are:

https://github.com/bitnami/bitnami-docker-redis
https://github.com/bitnami/bitnami-docker-mariadb
https://github.com/bitnami/bitnami-docker-elasticsearch

This container will be backwards compatible with the current nami-based image, however, we advise users to take special measures when upgrading their deploymens. We will update this thread when the PR is ready.

**Comment by juan131** [comment]
@javsalgar I think we can close this issue since the changes were already merged and the new PostgreSQL container is based on Bash scripts.

Feel free to reopen the issue.
