### ISSUE TITLE
How do I configure postgresql.conf with Kubernetes?

### ISSUE THREAD

**Issue by booboothefool** [bitnami/bitnami-docker-postgresql#128]
I would appreciate some guidance on how to apply a custom postgresql.conf with Kubernetes or the ability to just set it in the Dockerfile.

I have gotten this Docker image to work, but am not sure how to edit the config, I have tried the helm chart, but there I am having trouble with the volume claims.

**Comment by carrodher** [comment]
You can use custom configuration files following two approaches:

- The image looks for _postgresql.conf_ file in _/opt/bitnami/postgresql/conf/_. You can mount a volume at _/bitnami/postgresql/conf/_ and copy/edit the _postgresql.conf_ file in the _/path/to/postgresql-persistence/conf/_. You have more information in the specific [README section](https://github.com/bitnami/bitnami-docker-postgresql#configuration-file).
- Apart from using a custom _postgresql.conf_, you can include files ending in _.conf_ from the _conf.d_ directory in the volume at _/bitnami/postgresql/conf/_. You can find more information in the [README section](https://github.com/bitnami/bitnami-docker-postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf).
