### ISSUE TITLE
data directory "/bitnami/postgresql" has group or world access

### ISSUE THREAD

**Issue by alphabt** [bitnami/bitnami-docker-postgresql#130]
**Description**

postgres master container is unable to start. It failed with error below
```
FATAL:  data directory "/bitnami/postgresql" has group or world access
DETAIL:  Permissions should be u=rwx (0700).
```

**Steps to reproduce the issue:**

Sorry I haven't had a chance to repro using vanilla docker. But here's my setup that current repros in helm using stable/postgresql chart as a requirement. Please let me know if you need me to further repro in just using docker.

**requirements.yaml**
```yaml
dependencies:
  - name: postgresql
    version: "3.13.1"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
```
**helm install**
```shell
helm upgrade --install \
  --wait \
  [...snipped]
  --set postgresql.enabled="$postgres_enabled" \
  --set postgresql.postgresqlUsername="$POSTGRES_USER" \
  --set postgresql.postgresqlPassword="$POSTGRES_PASSWORD" \
  --set postgresql.postgresqlDatabase="$POSTGRES_DB" \
```

**Describe the results you received:**
master container failed to start with error above

**Describe the results you expected:**
master container starts successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Helm: 2.12.3
Kubernetes: 1.11.7
Chart: stable/postgresql 3.13.1

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I believe this started with 10.7.0-r69 since my setup hasn't changed and it was working fine as of 2019/5/6, before 10.7.0-r69 dropped.

**Comment by juan131** [comment]
Hi @alphabt 

Thanks for reporting the issue. I saw you also opened the same issue at https://github.com/helm/charts/issues/13651. I'll continue the discussion there to avoid confusion.

**Comment by alphabt** [comment]
@juan131 Sorry for the dup. I wasn't sure which project is the root cause so I opened both for more exposure. Thank you for closing one of them.
