### ISSUE TITLE
Unable to create user 'user' and db with dash

### ISSUE THREAD

**Issue by alphabt** [bitnami/bitnami-docker-postgresql#133]
**Description**

I am unable to create user `user` nor database with dash in the name such as `my-db`.

**Steps to reproduce the issue:**

```
docker run --rm --name postgresql -e POSTGRESQL_USERNAME=user -e POSTGRESQL_PASSWORD=password123 -e POSTGRESQL_DATABASE=my-database bitnami/postgresql:latest
```

**Describe the results you received:**

```
ERROR:  syntax error at or near "-" at character 19
STATEMENT:  CREATE DATABASE my-database
INFO  ==> Creating user user
ERROR:  syntax error at or near "user" at character 13
STATEMENT:  CREATE ROLE user WITH LOGIN CREATEDB PASSWORD 'password123';
INFO  ==> Grating access to user to the database my-database
ERROR:  syntax error at or near "-" at character 36
STATEMENT:  GRANT ALL PRIVILEGES ON DATABASE my-database TO user;
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

I believe we need to quote the following vars:
- `${POSTGRESQL_USERNAME}` in https://github.com/bitnami/bitnami-docker-postgresql/blob/bdea5179261c24bbe408a674b53e62bc3c8f08c6/10/debian-9/rootfs/libpostgresql.sh#L373
- `$POSTGRESQL_DATABASE` in https://github.com/bitnami/bitnami-docker-postgresql/blob/bdea5179261c24bbe408a674b53e62bc3c8f08c6/10/debian-9/rootfs/libpostgresql.sh#L388
- `${POSTGRESQL_DATABASE}` and `${POSTGRESQL_USERNAME}` in https://github.com/bitnami/bitnami-docker-postgresql/blob/bdea5179261c24bbe408a674b53e62bc3c8f08c6/10/debian-9/rootfs/libpostgresql.sh#L375

There are probably other things to quote such as:
- `$POSTGRESQL_REPLICATION_USER` in https://github.com/bitnami/bitnami-docker-postgresql/blob/bdea5179261c24bbe408a674b53e62bc3c8f08c6/10/debian-9/rootfs/libpostgresql.sh#L321

I didn't do an exhausted check, just FYI.

And it looks like `echo` will eat both single and double quotes.
```shell
$ echo "asfd"
asfd
$ echo 'asfd'
asfd
```

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @alphabt 

Thanks so much for reporting it! I just created a PR to fix it!

**Comment by juan131** [comment]
See https://github.com/bitnami/bitnami-docker-postgresql/pull/135

**Comment by alphabt** [comment]
@juan131 thank you for the quick fix!

**Comment by juan131** [comment]
We just merged the PR @alphabt 

I'm working on release a new revision of the images and I'll ping you once they're released.

**Comment by alphabt** [comment]
Awesome!

**Comment by juan131** [comment]
Hi @alphabt 

We just released the new revisions including the fix:

- 9.6 series: **9.6.12-r73**
- 10 series: **10.7.0-r72**
- 11 series: **11.2.0-r73**

**Comment by alphabt** [comment]
@juan131 I've tested the new version and it works for me. Thank you 😄
