### ISSUE TITLE
9.6.12-debian-9-r73 : /liblog.sh: line 34: MODULE: unbound variable

### ISSUE THREAD

**Issue by kel00s** [bitnami/bitnami-docker-postgresql#137]
**Description**

**Steps to reproduce the issue:**

1. Starting postgresql container from stable/postgresql Helm Chart
2. Getting error: /liblog.sh: line 34: MODULE: unbound variable
3. Container is in crashing loop.

**Version**
9.6.12-r73 started in GKE

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
K8s in GKE

**Comment by juan131** [comment]
Hi @kel00s 

Could you share the **values.yaml** you're using to deploy the chart?

**Comment by kel00s** [comment]
Sure,

[values.yaml.zip](https://github.com/bitnami/bitnami-docker-postgresql/files/3166562/values.yaml.zip)

**Comment by juan131** [comment]
Hi @kel00s 

It's very weird.. The error you're facing is related to some library included on **minideb-extras-base** (the base image used on this PostgreSQL image):

https://github.com/bitnami/minideb-extras-base/blob/3276315ed253dceab7d46a1d7984d8cff5755a47/stretch/rootfs/liblog.sh#L15

That library has been used without any change during 6 months by many other containers and it's very weird you're facing this issue now.

**Comment by juan131** [comment]
Hi @kel00s 

I found the problem!!!

Could you try disabling the parameter `image.debug=true`? E.g. set it to `false`

**Comment by juan131** [comment]
Hi @kel00s 

I created a PR to update the chart so the right env. variable is used to enable debugging.

**Comment by juan131** [comment]
Hi @kel00s 

We just released a new version of the chart that'll allow you to use `image.debug=true` again. Please try with the latest version of the chart: **4.0.2**

**Comment by kel00s** [comment]
Thanks @juan131,

Now I got same unbound variable but somewhere else:
```
INFO  ==> ** Starting PostgreSQL setup **
INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql:x:1000:
INFO  ==> Initializing PostgreSQL database...
DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
DEBUG ==> Ensuring expected directories/files exist...
/libpostgresql.sh: line 465: DB_DAEMON_USER: unbound variable
INFO  ==> Stopping PostgreSQL...
 ```

**Comment by juan131** [comment]
Thanks again for reporting it @kel00s 
I just created a PR to address that issue too!

**Comment by juan131** [comment]
We just merged the changes and I triggered the release process. I'll update this issue once the images are released. Thanks for you consideration and patience.
