### ISSUE TITLE
Change owner at database creation

### ISSUE THREAD

**Issue by Elrondo46** [bitnami/bitnami-docker-postgresql#139]
Can you let us change the owner when creating a custom database at first launch ?

**Comment by juan131** [comment]
Hi @Elrondo46 

I think you're looking for what's explained on the section below of the README.md:

https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-user-on-first-run

Am I right?

**Comment by minhdanh** [comment]
Even a POSTGRES_USER is specified, the user is created but it's still not the owner of the database. `postgres` is the owner. Is this expected?

**Comment by miguelaeh** [comment]
Hi @minhdanh ,
Is that [other issue](https://github.com/bitnami/bitnami-docker-postgresql/issues/143) what are you looking for?

**Comment by w1ndy** [comment]
@miguelaeh 
Same issue here. I'm using the helm chart to deploy PostgreSQL. Although the database and user specified in the configuration are created successfully, the owner of the created database is not the user defined by POSTGRES_USER.

I attempted to execute the following command with psql, logging in as POSTGRES_USER:
```
alter database POSTGRES_DATABASE owner to POSTGRES_USER;
```
but it failed with
```
ERROR:  must be owner of database POSTGRES_DATABASE
```

**Comment by miguelaeh** [comment]
Hi @w1ndy ,
The only users that can change the owner of a database are the owner of the database and the superuser. In this case it seems that you should connect with the user `postgres` user. The `POSTGRES_USER` is the user of the database but not the owner, that is because you can't change it.
I am not sure if is expected to change the owner too.

**Comment by w1ndy** [comment]
@miguelaeh 
Thanks for the tip! I have figured this out when I tried to deploy a Atlassian Confluence instance with PostgreSQL and the installation failed a million times with weird errors because the user 'confluence' did not own the database 'confluence'...

**Comment by miguelaeh** [comment]
Hi @w1ndy ,
So, that solve your problem?

**Comment by w1ndy** [comment]
Hi @miguelaeh ,
Yes, I've installed Confluence successfully using the default user 'postgres'. I think this should be noted somewhere in the documentation to warn that changing POSTGRES_USER does not change the owner of the created database...

**Comment by miguelaeh** [comment]
Hi @w1ndy ,
Thank you for the information, we will improve the documents.
