### ISSUE TITLE
How to create many databases on first run ?

### ISSUE THREAD

**Issue by AlawnWong** [bitnami/bitnami-docker-postgresql#142]
How to create many databases on first run ?

**Comment by alemorcuq** [comment]
Hi, @AlawnWong.

Check [this section on the README](https://github.com/bitnami/bitnami-docker-postgresql#initializing-a-new-instance). Those files will be executed on first run, so you can create as many databases as you want.

Regards,
Alejandro

**Comment by AlawnWong** [comment]
3Q
