### ISSUE TITLE
POSTGRES_USER environment variable not evaluated

### ISSUE THREAD

**Issue by ldelossa** [bitnami/bitnami-docker-postgresql#143]
**Description**

Attempting to use the postgres stable helm chart. It does not seem like the bitnami docker container respects the POSTGRES_USER environment variable. When the kubernetes POD is configured with that env var, no user is created in the resulting postgres instance in the container.

**Steps to reproduce the issue:**
1. set helm configuration variable `postgresqlUsername` to some name, in our example clair
2. deploy
3. inspect pod to confirm that the POSTGRES_USER env variable is defined for the pod specification. 
4. attempt to log into postgres with the provided username. failure will occur

**Describe the results you received:**

No user was created on the postgres instance

**Describe the results you expected:**

the user in the POSTGRES_USER env var would be created on the postgres instance. 

**Additional information you deem important (e.g. issue happens only occasionally):**

![image](https://user-images.githubusercontent.com/5642902/58513724-25148c00-816e-11e9-8a51-192be0e788c2.png)
Screenshot describes a pod where the POSTGRES_USER env has been set, but the user has not been created in the postgres instance.

**Comment by ldelossa** [comment]
I was able to reproduce this with a very minimal helm repository.


```
~/git/helm/postgrestest
❯ tree
.
├── Chart.yaml
├── charts
│   └── postgresql-5.1.0.tgz
├── requirements.lock
├── requirements.yaml
├── templates
└── values.yaml

2 directories, 5 files

~/git/helm/postgrestest
❯ cat values.yaml
# Default values for postgrestest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  postgresqlUsername: clair
  postgresqlDatabase: clair
  postgresqlPassword: clair

~/git/helm/postgrestest
❯ cat requirements.yaml
dependencies:
  - name: postgresql
    version: "5.1.0"
    condition: postgresql.enabled
    repository: "alias:stable"
```

**Comment by miguelaeh** [comment]
Hi @ldelossa ,
Thanks for reporting, you are right. There is an error on the configuration, if you provide a username but not a database the user is not set.
We are working to fix it.
Again, thank you.

**Comment by javsalgar** [comment]
Hi,

I tried to reproduce it but I couldn't

```
❯ helm install stable/postgresql --set postgresqlDatabase=clair --set postgresqlUsername=clair --set postgresqlPassword=clair
```

```
❯ kubectl exec -ti plucking-camel-postgresql-0 bash

I have no name!@plucking-camel-postgresql-0:/$
I have no name!@plucking-camel-postgresql-0:/$ psql -U clair
Password for user clair:
psql (11.3)
Type "help" for help.

clair=>
```

**Comment by ldelossa** [comment]
@javsalgar 

Will this PR take effect on the latest helm chart version?

**Comment by miguelaeh** [comment]
You need to update your deployment if you want this pull request to take effect.
