### ISSUE TITLE
New feature: allow init scripts run by superuser

### ISSUE THREAD

**Issue by sebastien-prudhomme** [bitnami/bitnami-docker-postgresql#155]
**Description**

My use case is to run `CREATE EXTENSION` in an init script in /docker-entrypoint-initdb.d and using POSTGRESQL_USERNAME so that my application doesn't use the superuser account.

Currently the inits scripts are launched with the POSTGRESQL_USERNAME account, not the superuser account, and the `CREATE EXTENSION` command fails with `Must be superuser to create this extension` error.

I can't see any solution to do that with the current Docker image.

Having another directory dedicated to init scripts executed by the superuser account would be a solution.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

I'm using the "stable" PostgreSQL Helm chart.

**Comment by javsalgar** [comment]
Hi,

Did you try running the scripts with the `postgres` user instead? The user we create does not have superuser privileges.

**Comment by sebastien-prudhomme** [comment]
@javsalgar I've tried with a shell script but `psql`command is not usable, i guess because of this trick to make the image compatible with OpenShift: #103

I got this error: `local user with ID 1001 does not exist̀`

So i see no way to become a Postgresql superuser in the container.

**Comment by javsalgar** [comment]
Hi,

Could you try entering the container and doing the following?

```
cat $NSS_WRAPPER_PASSWD
```

**Comment by sebastien-prudhomme** [comment]
@javsalgar The variable doesn't exists when i exec a shell in the container, but PID 1 have it.

So i have done what it is done in /entrypoint.sh, not that intuitive.

psql returns no error now but is asking for a password.

I've checked pg_hba.conf and it's not trusting local connexion, so impossible to connect as superuser.

I don't understand why postgresql_restrict_pghba function set only md5 auth on host access and keep trust on local access.

**Comment by javsalgar** [comment]
Hi,

In order to set that password, you need to use the `PGPASSWD` environment variable. Maybe it makes sense to keep trust when accessing through localhost, but I would like to have more input from the community to know which option is best. 

What I would do for your case is to set POSTGRES_USERNAME as `postgres` so POSTGRESQL_PASSWORD is set for the user `postgres`. Then, in your init scripts, you can create the username and databases you want. Would that work for your case?

**Comment by sebastien-prudhomme** [comment]
@javsalgar Yes the solution you suggest will work for my use case. Thanks.

Two things i've noticed by comparing this image and the "official" PostgreSQL image from Docker hub:
- the "official" Docker image trust localhost connexion even when POSTGRESQL_PASSWORD is set
- the "official" Docker image set POSTGRES_USERNAME as a superuser account

So i suggest adding 2 new env parameters that control these behaviours, that is whether to trust localhost connexion (default to false) and whether POSTGRES_USERNAME as a superuser account (default to false).

Should i close this issue?

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. We will evaluate these features for future releases of the container. Also, as the code is available, feel free to create a PR so we can include that logic in the container

**Comment by palashgoel7** [comment]
I had a similar issue. This worked for me:

`initdbScripts:
  my_init_script.sh: |
     #!/bin/sh
     export PGPASSWORD=$POSTGRESQL_PASSWORD # Set appropriately
     psql -Upostgres rivigo_zoom -c "create extension if not exists postgis;"`

Make sure that your admin user is postgres. Could not get this to work when I changed the name of admin user

**Comment by rolep** [comment]
Hi,

+1 for superuser

Am mostly using docker-images in small scale projects, and in local / dev / testing environment is it nice to have correct setup with just one `docker-compose up`.
For this user just needs to customize env vars (or accept using defaults) - custom image with custom entrypoints is already set in compose file.

So, I have 2 custom scripts in docker.entrypoint.init.d: one to trust local connections, one to setup custom superuser with custom database (creating other users optionally, as pg_dump backups contains database-level statements, extensions etc but not users).

For this purpose figured out trick with env variables, settings both `POSTGRES_USER` and `POSTGRESQL_USERNAME` and similar vars - first ones with my custom user, second ones with `postgres` user:

App container (django app in my case) works with short form / alias vars, like `POSTGRES_USER`, `POSTGRES_DB`. Timescaledb container also happened to work with short format.
These alias vars are set to custom superuser/database name, and all containers can share the same set of env vars / file.

To prevent bitnami/postgresql from creating custom user (and not having postgres password set, not having superuser permissions on custom user) additionally "full / long format" vars are supplied to postgres container to configure `postgres` user instead: `POSTGRESQL_USERNAME=postgres`, `POSTGRESQL_PASSWORD=some_password`.
Some digging into [libpostgresql.sh](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh) shows that long format vars take precedence first, thus only postgres user and db is configured while short / alias format vars are still available and used in my custom entrypoint script to setup superuser / database.

Downside of such approach - it seems to be dependent on bitnami/postgresql libpostgresql.sh internals.

The trick was to create superuser account with known credentials which would allow to create custom user / db in one go.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. We will consider this feature in future releases. As soon as it is ready. I will update this ticket

**Comment by rewt** [comment]
> I had a similar issue. This worked for me:
> 
> Make sure that your admin user is postgres. Could not get this to work when I changed the name of admin user
> 
> ```
>   my_init_script.sh: |
>      #!/bin/sh
>      export PGPASSWORD=$POSTGRESQL_PASSWORD # Set appropriately
>      psql -Upostgres rivigo_zoom -c "create extension if not exists postgis;"
> ```

did you place this in `initdbScripts:` section of yaml?

**Comment by palashgoel7** [comment]
yes
Thanks,
Palash Goel

**Comment by risayew** [comment]
Hi ! i habe the same issue but in the helm chart. The only solution, which i see at the moment is to remove the database, remove persistent volumes, start the database with postgres user and restore the data from backups. But i don't want to do it on production.
@javsalgar could you, please, explain your way to set the password to postgres user? Any help is appreciated.

**Comment by javsalgar** [comment]
Hi,

In the container, we now have the option to specify a password for the postgres user. 

https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-9/rootfs/libpostgresql.sh

In the case of the helm chart, I would set the postgresqlUsername value to postgres, and then have init scripts that, using the `postgres` user, create the proper users with their privileges.

**Comment by rolep** [comment]
Hi,

Nice option.

For some reason _docker-entrypoint-initdb.d_ `.sql` script ignores _POSTGRESQL_INITSCRIPT_USERNAME_ (=postgres in test case, POSTGRESQL_USER/DB=custom) vars, and runs as _POSTGRESQL_USER_, while `.sh` script (and `printenv`) reports it =postgres.

P.S. Currently am sticking to just using postgres user localy and in dev environment (mainly to simplify things), with adding initial setup step in prod (although api (django) user has full access so can't see many reasons not to use postgres role on prod, unless for direct db access reasons) (but deep inside prefer to use separate roles and it is the reason to like bitnami image)

**Comment by javsalgar** [comment]
Hi,

Make sure that you are using the latest version of the image that supports the POSTGRESQL_INITSCRIPT_VARIABLE. @miguelaeh could you also check if there's anything missing in the container logic? AFAIK it should work.

Anyways, as a workaround you can try using a bash script instead that creates the SQL file and then runs the query with whatever option and credentials you consider.

**Comment by dardanos** [comment]
I'm using the [helm chart](https://bitnami.com/stack/postgresql/helm) `v7.5.0` with tag: 
```
docker.io/bitnami/postgresql:11.5.0-debian-9-r84
```

##### `values.yml`:
```yml
  postgresqlDatabase: 'store'
  postgresqlUsername: 'postgres'
  postgresqlPassword: 'this_is_a_fake_passw0rd!'
```

##### Rendered values
I can validate that the helm chart has the values above:
```yml
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: w1-store
                  key: postgresql-password
            - name: POSTGRES_DB
              value: "botdb"
```


<details>
 <summary>The logs I see from the database pod</summary>

```
postgresql 06:04:56.28
postgresql 06:04:56.29 Welcome to the Bitnami postgresql container
postgresql 06:04:56.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 06:04:56.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 06:04:56.29 Send us your feedback at containers@bitnami.com
postgresql 06:04:56.29
postgresql 06:04:56.30 INFO  ==> ** Starting PostgreSQL setup **
postgresql 06:04:56.34 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 06:04:56.34 INFO  ==> Loading custom pre-init scripts...
postgresql 06:04:56.35 INFO  ==> Initializing PostgreSQL database...
postgresql 06:04:56.35 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 06:04:56.36 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 06:04:57.50 INFO  ==> Starting PostgreSQL in background...
postgresql 06:04:57.85 INFO  ==> Changing password of postgres
postgresql 06:04:57.86 INFO  ==> Configuring replication parameters
postgresql 06:04:57.87 INFO  ==> Configuring fsync
postgresql 06:04:57.88 INFO  ==> Loading custom scripts...
postgresql 06:04:57.88 INFO  ==> Enabling remote connections
postgresql 06:04:57.89 INFO  ==> Stopping PostgreSQL...

postgresql 06:04:58.90 INFO  ==> ** PostgreSQL setup finished! **
postgresql 06:04:58.94 INFO  ==> ** Starting PostgreSQL **
2019-11-18 06:04:58.952 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-11-18 06:04:58.952 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2019-11-18 06:04:58.956 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-11-18 06:04:58.971 GMT [207] LOG:  database system was shut down at 2019-11-18 06:04:57 GMT
2019-11-18 06:04:58.974 GMT [1] LOG:  database system is ready to accept connections
2019-11-18 06:06:39.707 GMT [342] FATAL:  password authentication failed for user "postgres"
2019-11-18 06:06:39.707 GMT [342] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2019-11-18 06:07:38.577 GMT [432] FATAL:  password authentication failed for user "postgres"
2019-11-18 06:07:38.577 GMT [432] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
2019-11-18 06:07:38.726 GMT [433] FATAL:  password authentication failed for user "postgres"
2019-11-18 06:07:38.726 GMT [433] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

</details>

**Comment by juan131** [comment]
Hi @dardanos 

The issue doesn't seem to be related cd .

Did you face this issue after upgrading an existing PostgreSQL chart release or did you face it while installing a new release (from scratch)? Please note that you must ensure you're using the same credentials when running an upgrade (as it's detailed in the link below): 

- https://github.com/helm/charts/tree/master/stable/postgresql#upgrade

> ####  Environment:
> helm chart v7.5.0
> docker image: docker.io/bitnami/postgresql:11.5.0-debian-9-r84

- Did you mean `7.2.0`? The latest published version of this chart is that one (see https://github.com/helm/charts/blob/master/stable/postgresql/Chart.yaml)
- We're also packaging a different version of PostgreSQL on that chart version: **11.6.0-debian-9-r0**

**Comment by dardanos** [comment]
Hi @juan131, thanks for the information you provided. I helped me find the problem.

Here is what I did to fix the problem:
1. Delete the previous installation
    ```
    helm delete <name> --purge
    ```
1. Update helm chart to `7.2.0`
1. Set the following variables in `values.yml`
    ```    
    postgresqlDatabase: 'mydbname'
    postgresqlUsername: 'postgres'
    postgresqlPassword: 'really-string-password-here'
    ```
1. Helm install
1. My app can now run commands like 
    ```
    CREATE EXTENSION IF NOT EXISTS "pgcrypto";
    ```

**Comment by juan131** [comment]
Hi @dardanos 

I'm glad you could solve the issue.

There a couple of things you need into account when using this chart:

- PVCs are not removed (even after removing the char using `helm delete <name> --purge`).
- The init scripts are exclusively executed the 1st time the PostgreSQL container is booted. If it's restarted, it will detect data in the PV, and it will skip running those scripts and reuse the data.

**Comment by dmlond** [comment]
this affects users of the docker hub image as well. as context, ruby on rails applications often use pgcrypto to autogenerate uuid primary keys on their models. In addition, they typically add the pgcrypto extension if it does not exist a db migration. Using the bitnami image, if I run it with a POSTGRESQL_DATABASE and POSTGRESQL_PASSWORD, but not a POSTGRESQL_USERNAME (or POSTGRES_USER), and I use the 'postgres' user in the application database connection parameters, this works. I can also pass POSTGRESQL_USERNAME=postgres and it works. BUT, if I pass POSTGRESQL_USERNAME=appuser (or anything other than postgres), it does not work, because the user generated by the image inititialization does not have the right privileges to add the extension.

**Comment by juan131** [comment]
Hi @dmlond 

You're right. That user won't have privileges to perform those changes.

However, you can always connect to PostgreSQL using the `postgres` user and do it. I mean, using the environment variables below, you have two users: one for the Ruby app, and the 'postgres' user:

- POSTGRESQL_USERNAME= appuser
- POSTGRESQL_DATABASE=appdatabase
- POSTGRESQL_PASSWORD=XXXXX (password for 'appuser' user)
- POSTGRESQL_POSTGRES_PASSWORD=YYYYYY (password for 'postgres' user)

**Comment by dmlond** [comment]
Thanks. For some reason I didnt even see that part of the documentation. 

I would say that is is normal for ruby on rails application db users to be able to add extensions to their specific db. Is there some kind of role that can be granted to the POSTGRES_USER to allow this?

**Comment by javsalgar** [comment]
Hi,

I'm no expert in PostgreSQL, so I do not know the specific grant that you need to give the user to be able to create extensions. What it makes sense to me is to create the extension as the super user and then have the normal user use it. With init scripts you should be able to do it.

**Comment by dmlond** [comment]
I appreciate your consideration. Unfortunately, there are many rails+Postgresql projects out there that use this pattern, including my own, and these will fail when trying to use this postgresql container unless they use the postgres user in their application. There is even a rake db:migrate function called enable_extension exclusively for this purpose:
https://stackoverflow.com/questions/16611226/how-to-install-postgres-extensions-at-database-creation

**Comment by dmlond** [comment]
To be fair, the pgcrypto extension is configured to require a superuser. I have been able to run my rake tasks with this enable extension feature in the official postgres image, and in any of the databases that I get from Heroku Database. That suggests to me that these are configured to make the user that we use in our rake tasks (e.g. POSTGRES_USER in the official postgres image, and whatever random user we get from Heroku) is a superuser.

**Comment by javsalgar** [comment]
So, if I understand correctly, even though you enable the pgcrypto extension in the database, every operation would require a super user as well? I thought that just enabling the extension as a super user should be enough.

**Comment by bittner** [comment]
I wonder if there is a way to preconfigure extensions for all databases (e.g. make them part of the `template0` [template database](https://www.postgresql.org/docs/12/manage-ag-templatedbs.html)).

If that were easily possible, say, in the file system we could run our own `Dockerfile`s that would inherit `FROM` this image and activate the extensions we need. Using the resulting image afterwards, there would be no need to run init scripts with elevated privileges at startup at all.

**Comment by javsalgar** [comment]
Hi,

I imagine that enabling the preload libraries is not enough for that, right? 

https://github.com/bitnami/bitnami-docker-postgresql#preloading-shared-libraries

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
