### ISSUE TITLE
Add uuid-ossp extension

### ISSUE THREAD

**Issue by irizzant** [bitnami/bitnami-docker-postgresql#156]
Hello
I tried to run a pg_restore containing:
`CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;`

and I get the error:
`function public.uuid_generate_v4() does not exist`

After further investigations I realized that bitnami/postgresql:10-debian-9 does NOT contain this extension by default.

I want to underline that the official postgres image DOES contain this extension for postgres:10 tag, because the pg_restore runs without any issue on that image.

Is it possible to add uuid-ossp to this image too?

Thank you

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 59
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: uk71hoqowcj96o5vqjyovobj3
 Is Manager: true
 ClusterID: mk8qq34ub7j0fl81nko2ehyqq
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.118.102.228
 Manager Addresses:
  10.118.102.228:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-54-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.21GiB
Name: pclnxdev22
ID: D372:OWDS:SZT3:OLYW:XB77:TONZ:ELT5:QG4C:DJ3D:KKY6:2UCK:MRQB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

**Comment by andresbono** [comment]
Hi @irizzant, thanks for filling this issue. We are going to evaluate the addition of the extension to the image and we will get back to you.

**Comment by yxxhero** [comment]
I also need this uuid-ossp extension @andresbono. thanks!!

**Comment by irizzant** [comment]
Hello @andresbono , any news and/or planned intervention?

**Comment by andresbono** [comment]
Hi @irizzant, this task is still in our backlog. As soon as we have any news we will update this issue. Thanks for your patience.

**Comment by devypt** [comment]
any updates?

**Comment by andresbono** [comment]
Hi @devypt, we couldn't address it yet. We will update this issue as soon as we include it.

**Comment by fenos** [comment]
It's an important extension widely used, I'd love to see it included

**Comment by marcosbc** [comment]
Hi @fenos, just wanted to let you know we have started working on this and expect to release a container with the extension later today. We'll keep this issue open with further updates.

**Comment by irizzant** [comment]
Hello @marcosbc that's definitively good news. Thank you

**Comment by marcosbc** [comment]
Hi all (@irizzant @fenos @devypt @yxxhero), just wanted to update this issue to let you know that the Bitnami PostgreSQL containers were updated to include support for the mentioned extension.

Thanks for your patience!

**Comment by drewwells** [comment]
tagging the commit/PR will help us figure out what version of the container includes this fix.

**Comment by alemorcuq** [comment]
Hi, @drewwells.

You are right, we should have specified which versions include the fix since now it's very difficult to track it. Any release from Aug 23 onward should include the fix. Those were:

```
11.5.0-debian-9-r15
9.6.15-debian-9-r16
11.5.0-ol-7-r16 
11.5.0-centos-7-r11
10.10.0-centos-7-r16
10.10.0-ol-7-r16
9.6.15-ol-7-r16
9.6.15-centos-7-r16
10.10.0-debian-9-r16
```

Anything newer than that will also include the extension.

Regards,
Alejandro
