### ISSUE TITLE
Explicit postgres Password

### ISSUE THREAD

**Issue by 1995parham** [bitnami/bitnami-docker-postgresql#158]
Is there any environment variable for setting the Postgres password in the case when we use `PG_USER` and `PG_PASS` to create application user?

**Comment by miguelaeh** [comment]
Hi, 
thank you very much for the PR, we will review it soon.

**Comment by 1995parham** [comment]
@miguelaeh We have a database and we set application password and username with the following environments:

- `POSTGRESQL_USERNAME=my_user`
- `POSTGRESQL_PASSWORD=password123`

But for maintaining the database we need `postgres` user we need to set a password for it too. In our environment docker container runs with a random user so we cannot use `psql -U postgres` for accessing the database.

**Comment by miguelaeh** [comment]
Ah, okay, I understand thank you for the clarification.

**Comment by andresbono** [comment]
@1995parham, we have just merged #159.

I hope you find it useful!
