### ISSUE TITLE
Kubernetes helm stable bitnami postgresql deployment - DB read/write traffic split-up

### ISSUE THREAD

**Issue by erdarun** [bitnami/bitnami-docker-postgresql#161]
**Version of Helm and Kubernetes:**
Helm - 2.12
Kubernetes - 1.13.2

**Which chart:**
stable/postgresql

**What happened:**
We have deployed 3 instances of postgresql with the setup of 1 master and 2 slaves

We can see below services up and running,

> pg-ha-v1-postgresql 5432/TCP
> pg-ha-v1-postgresql-headless 5432/TCP
> pg-ha-v1-postgresql-metrics 9187/TCP
> pg-ha-v1-postgresql-read 5432/TCP

**What you expected to happen:**
As per the bitnami documentation,
https://engineering.bitnami.com/articles/worried-about-big-data-scale-up-with-bitnami-secure-fault-tolerant-postgresql-cluster.html

> Data automatically replicates from the master node to all slave nodes. The master node receives all write operations, while the slave nodes repeat the operations performed by the master node on their own copies of the data set and are used for read operation. This model improves the overall performance of the solution. It also simplifies disaster recovery, because a copy of the data is maintained on each node in the cluster.

**Need to know how the above concept of query parsing implemented using headless service and read service on helm stable/postgresql chart deployment?**

**Expectation is that application read request should be served by slave nodes for performance gain while write operations restricted only to master**

_values.yaml: synchronousCommit: "on", numSynchronousReplicas: 1_

> pg-ha-v1-postgresql endpoints only to master
> pg-ha-v1-postgresql-read endpoints only to slaves
> pg-ha-v1-postgresql-headless endpoints points to all 3 instances of master & slaves

**_Please share more details on whether read/write traffic split is implemented in helm bitnami postgresql chart if so how it's done to know more background details on the same._**

**Comment by erdarun** [comment]
@andresbono Please explain how the concept of query parsing implemented in helm stable/postgresql kubernetes deployment so that to differentiate read/write queries split-up for serving either from master or slave nodes for performance gain

**Comment by juan131** [comment]
> Need to know how the above concept of query parsing implemented using headless service and read service on helm stable/postgresql chart deployment?

The "headless" service is not used to provide an endpoint to access "read endpoints" but to provide a unique stable network identifier to each of the pods associated to the "read" statefulset. Learn more about Headless Services in the link below: 

- https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

Therefore, when you want to do queries ("read") you need to target the "read" service. For instance, in your example, you need to target `pg-ha-v1-postgresql-read`. However, when you need to do "write" operations, target the `pg-ha-v1-postgresql` service.

Please note that you **shouldn't use the headless service** to access your pods! It's exclusively used to guarantee the pods have a unique stable network identifier.

**Comment by erdarun** [comment]
@juan131 Do you mean from our application side we need to implement query parsing logic to separately target write transactions to `pg-ha-v1-postgresql` and read transactions to `pg-ha-v1-postgresql-read`.

If application doesn't have the capability to do it, Is there any alternative solution to split queries and target read/write operations specific to `pg-ha-v1-postgresql-read/pg-ha-v1-postgresql` services?

**Comment by juan131** [comment]
> Do you mean from our application side we need to implement query parsing logic to separately target write transactions to pg-ha-v1-postgresql and read transactions to pg-ha-v1-postgresql-read?

Yes, I mean exactly that

> Is there any alternative solution to split queries and target read/write operations specific to pg-ha-v1-postgresql-read/pg-ha-v1-postgresql services?

You can use [PGPool](https://www.pgpool.net/mediawiki/index.php/Main_Page). It's a kind of proxy you put between your client and your PostgreSQL cluster and if I'm not wrong, you can configure it to balance the requests depending of the type (write or read operations).

Indeed, we're exploring this tool at this moment and it's very likely that we'll add support for it on this chart so you won't have to worry about the setup in the near future.

**Comment by erdarun** [comment]
@juan131 If master instance goes down pointing to `pg-ha-v1-postgresql` will the existing streaming replicated slave will take it's position automatically? Parallelly a new streaming replication db instance for slave will be created under `ha-v1-postgresql-read` services?

Please suggest any guide for PGPool implementation in kubernetes cluster between application & db instances if you have already explored on then same.

**Comment by juan131** [comment]
> @juan131 If master instance goes down pointing to pg-ha-v1-postgresql will the existing streaming replicated slave will take it's position automatically? Parallelly a new streaming replication db instance for slave will be created under ha-v1-postgresql-read services?

At this very moment, no. We need the [Replication Manager for PostgreSQL](https://repmgr.org/) to coordinate that operation. It's something we're working on at this moment and we'll soon have a new chart including this feature.

**Comment by erdarun** [comment]
@juan131 So what happens as of now if master instance goes down? If application points only to pg-ha-v1-postgresql.

In case of bitnami postgresql helm chart deployment on kubernetes cluster, Kubernetes can bring up master/slave node if any goes down by replication controller/replica set? But Im worried if new instance other than slave take master position data directory will be empty instead of existing streaming replication node which already have data synched.

**Comment by juan131** [comment]
> @juan131 So what happens as of now if master instance goes down? If application points only to master pg-ha-v1-postgresql.

The service will be down until K8s creates a new master pod

> In case of existing bitnami postgresql helm chart deployment on kubernetes cluster, Kubernetes can bring up master/slave node if any goes down by inbuilt mechanism of replication controller/replica set? If so then statefulset pvc will be mounted with existing data committed to master/slave right.

Yes, K8s should be able to create new pods when any of the master/slave pods fail and mount the existing data. New pods will detect the existing data and restore the containers.

> Is there an option to promote existing slave to master in current setup?

No, AFAIK
