### ISSUE TITLE
Setting up a streaming replication

### ISSUE THREAD

**Issue by datbv** [bitnami/bitnami-docker-postgresql#162]
postgresql-master_1  | INFO  ==> ** Starting PostgreSQL setup **
postgresql-master_1  | INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-master_1  | INFO  ==> Initializing PostgreSQL database...
postgresql-master_1  | INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-master_1  | INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql-master_1  | mkdir: cannot create directory ‘/bitnami/postgresql/data’: Permission denied
postgresql-master_1  | INFO  ==> Stopping PostgreSQL...

**Comment by alemorcuq** [comment]
Hi, @datbv.

Can you give us some context? How are you deploying this?

Regards,
Alejandro
