### ISSUE TITLE
running bootstrap script

### ISSUE THREAD

**Issue by Lebronbingcheng** [bitnami/bitnami-docker-postgresql#166]
**Description**
Hello. I am faced of a problem when 'initdb'. (I remove  ">/dev/null 2>&1" when initdb)
'''
running bootstrap script ... ok
performing post-bootstrap initialization ... ok

'''
It costs about 20 minutes to process these two steps. What are they used for ? and Could I skip it by and configurations?

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @Lebronbingcheng.

It shouldn't take 20 minutes to complete those steps. How are you deploying the database? Is it possible that you are using a slow machine/storage? [Looking at PostgreSQL's source code](https://doxygen.postgresql.org/initdb_8c_source.html) it looks like it does a bunch of stuff needed for PostgreSQL's setup, so I don't think you can skip them.

Regards,
Alejandro

**Comment by Lebronbingcheng** [comment]
Hi, @alemorcuq

Thanks for your respond.
 
I add an ''strace" before the command.
'''
'strace "$POSTGRESQL_BIN_DIR/initdb" -E UTF8 -D "$POSTGRESQL_DATA_DIR" -U "postgres"'

'''
Then I found the program hangs on a strange step.

'''
write(5, "ANALYZE;\n\nVACUUM FREEZE;\n\n", 26) = 26
write(5, "CREATE DATABASE template0 IS_TEM"..., 73) = 73
write(5, "UPDATE pg_database SET datlastsy"..., 107) = 107
write(5, "REVOKE CREATE,TEMPORARY ON DATAB"..., 60) = 60
write(5, "REVOKE CREATE,TEMPORARY ON DATAB"..., 60) = 60
write(5, "COMMENT ON DATABASE template0 IS"..., 65) = 65
write(5, "VACUUM pg_database;\n\n", 21) = 21
write(5, "CREATE DATABASE postgres;\n\n", 27) = 27
write(5, "COMMENT ON DATABASE postgres IS "..., 79) = 79
close(5)  
'''
Could you figure out what it happened?
--

**Comment by alemorcuq** [comment]
Hi, @Lebronbingcheng.

I can't figure it out without some steps to reproduce the issue. How are you deploying the database? Again, is it possible that you are using a slow machine or storage? That behaviour is not normal.

Regards,
Alejandro
