### ISSUE TITLE
Feature request: Postgres 12 support

### ISSUE THREAD

**Issue by qjcg** [bitnami/bitnami-docker-postgresql#170]
It would be great to have a quality Bitnami image available now that [Postgres 12 has been released](https://www.postgresql.org/docs/12/release-12.html).

**Comment by carrodher** [comment]
Thanks for the suggestion @qjcg, we already have a task included in our board. Although I can't provide you an exact date, it should be ready during the next week. We will update this thread as soon as we have more news.

**Comment by carrodher** [comment]
Hi @qjcg , we released PostgreSQL 12 for Debian, Centos and Oracle 10 days ago, you can find the code [here](https://github.com/bitnami/bitnami-docker-postgresql/tree/master/12) and the images in [DockerHub](https://hub.docker.com/r/bitnami/postgresql/tags).

I'm closing this issue. Thanks!
