### ISSUE TITLE
Crash on unset POSTGRESQL_PASSWORD

### ISSUE THREAD

**Issue by swalladge** [bitnami/bitnami-docker-postgresql#174]
**Description**

A recent change caused a regression that results in a crash when `POSTGRESQL_PASSWORD` is unset, even if `ALLOW_EMPTY_PASSWORD`. The regression was introduced in https://github.com/bitnami/bitnami-docker-postgresql/commit/ca69be263ce06c6040e0a1a8a90417fef12ca943#diff-4401ba855e23507ce0dfe7bf9ada9425R149 (and other recent commits by bitnami-bot that change this line for other releases, not just 11-debian). The crash happens because `nounset` is set and `$POSTGRESQL_PASSWORD` is referenced without checking that it exists.

A solution would be to add a default for this variable where other defaults are set up:

```
export POSTGRESQL_PASSWORD="${POSTGRESQL_PASSWORD:-}"
```

Or alternately, fall back to the default where the new usage is:

```
if [[ -z "${POSTGRESQL_INITSCRIPTS_PASSWORD:-}" ]]; then
    export POSTGRESQL_INITSCRIPTS_PASSWORD="${POSTGRESQL_PASSWORD:-}"
```

**Steps to reproduce the issue:**

1. set `ALLOW_EMPTY_PASSWORD=yes` in the env. do not set `POSTGRESQL_PASSWORD`
2. launch the container
3. container crashes
4. view the logs and see `/entrypoint.sh: line 60: POSTGRESQL_PASSWORD: unbound variable`

**Describe the results you received:**

Container crashes and stops with `/entrypoint.sh: line 60: POSTGRESQL_PASSWORD: unbound variable`

**Describe the results you expected:**

No crash. Previously everything has been fine with POSTGRESQL_PASSWORD unset and ALLOW_EMPTY_PASSWORD=yes.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.4-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        9013bf583a
 Built:             Sat Oct 19 04:40:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 32
  Running: 30
  Paused: 0
  Stopped: 2
 Images: 183
 Server Version: 19.03.4-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.8-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 47.01GiB
 Name: archdesk
 ID: 47QZ:HZGD:2W5D:RR62:FCGQ:KF6M:JLTS:E5VS:A6AY:3U3A:YLIT:OETE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build unknown
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker on ArchLinux.

**Comment by juan131** [comment]
Hi @swalladge 

Thanks so much for reporting this bug! I'll work on fixing it in the image so we can release a new revision that addresses it.

**Comment by swalladge** [comment]
@juan131 Thanks. :+1: 

By the way, what's the process to submit a PR, since the changes must be duplicated across all (or most of) the different platforms? I see many commits are by the bitnami-bot, so do you have a  process/template for the 'master' for changes?

**Comment by juan131** [comment]
Hi @swalladge 

You can submit a PR to this repo and we'll be glad to review it.

Then, we need to ensure those changes are applied to our internal pipeline too (we'll do that after merging the PR). From that moment on, the daily releases will include your changes and `bitnami-bot` won't overwrite them.

**Comment by swalladge** [comment]
@juan131 Thanks, I'll remember that in future. :)
