### ISSUE TITLE
BUG: initdb error with multiple args

### ISSUE THREAD

**Issue by killmeplz** [bitnami/bitnami-docker-postgresql#178]
**Description**
I was trying to install posgtresql stable chart on my k8s cluster with pg version 11.6.0-debian-9-r5
The only difference from default values is this:
```
        extraEnv:
          - name: POSTGRESQL_INITDB_ARGS
            value: "--lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'"
```
As a result i get this error:
`initdb: invalid locale name "en_US.UTF-8 --lc-ctype=en_US.UTF-8"`

I guess the issue must be somewhere in quotes, but i just couldn't figure it out

**Comment by rafariossaa** [comment]
Hi @killmeplz,
  Could you try with ?
`value: --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'`

**Comment by killmeplz** [comment]
Hi @rafariossaa . Thanks for suggestion.
`initdb: invalid locale name "'en_US.UTF-8' --lc-ctype='en_US.UTF-8'"`
But unfortunately it didn't help. Probably because of the yaml -> json translation.

**Comment by rafariossaa** [comment]
Hi, @killmeplz 
  There is a bug in the initialization script.
   I am fixing it, I will come back to you as soon it is fixed and released.

**Comment by rafariossaa** [comment]
Hi @killmeplz,
  We have made a new release fixing this.
  Could you give it a try ?

**Comment by killmeplz** [comment]
Sure, what's the release tag?

**Comment by carrodher** [comment]
Tags are incremental, so you can use the latest one at this time and it should contain the fix:
https://github.com/bitnami/bitnami-docker-postgresql#supported-tags-and-respective-dockerfile-links

**Comment by killmeplz** [comment]
it worked with latest version.
Thanks for help
