### ISSUE TITLE
Server doesn't bind to port and doesn't start listening after restart.

### ISSUE THREAD

**Issue by MisterTimn** [bitnami/bitnami-docker-postgresql#179]
**Description**
We deploy the bitnami postgres image as part of the stable postgresql chart, as backend for a keycloak deployment (all in Kubernetes).
After upgrading Kubernetes from 1.13 tot 1.14 we noticed the postgres pod didnt come 
back up as it should.

It seems to hang after the setup phase, not binding to any ports and starting to listen for incoming requests (see logs)

_Logs_

```
postgresql 10:28:11.34 DEBUG ==> Configuring libnss_wrapper...
postgresql 10:28:11.35 INFO  ==> ** Starting PostgreSQL setup **
postgresql 10:28:11.41 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:28:11.42 INFO  ==> Loading custom pre-init scripts...
postgresql 10:28:11.45 INFO  ==> Initializing PostgreSQL database...
postgresql 10:28:11.75 DEBUG ==> Ensuring expected directories/files exist...
postgresql 10:28:11.76 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 10:28:11.77 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 10:28:11.77 INFO  ==> Generating local authentication configuration
postgresql 10:28:11.85 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 10:28:11.85 INFO  ==> Configuring replication parameters
postgresql 10:28:11.88 INFO  ==> Configuring fsync
postgresql 10:28:12.22 INFO  ==> Loading custom scripts...
postgresql 10:28:12.23 INFO  ==> Enabling remote connections
postgresql 10:28:12.24 INFO  ==> Stopping PostgreSQL...
postgresql 10:28:12.24 INFO  ==> ** PostgreSQL setup finished! **

postgresql 10:28:12.29 INFO  ==> ** Starting PostgreSQL **
```

**Steps to reproduce the issue:**

1. Setup postgresql with stable helm chart in K8s
2. Scale down statefulset to 0 replicas
3. Scale it back up to desired replicas

**Describe the results you received:**
Postgresql hangs and doesnt become ready, doesn't respond to requests. We are also not able to use psql from inside the container to access the database

**Describe the results you expected:**
Postgresql comes back up without issue.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 38
 Running: 17
 Paused: 0
 Stopped: 21
Images: 632
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-54-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.64GiB
Name: kubernetes-node3
ID: H73T:5ZA2:QZ2L:3NDE:QGF4:G3AF:46MX:QKYV:OARD:AYEI:VWJD:YXXA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes (self-hosted)

**Comment by andresbono** [comment]
Thanks for filling this issue, @MisterTimn. We will try to reproduce the issue on our side. Does it happen in your environment with a new, from-scratch helm deployment or with one in which you have already populated with data? Are you using the default `values.yaml`?

**Comment by MisterTimn** [comment]
Thanks for the quick response. However we seem to have resolved the issue after some restarts and reboots... Still not clear what exactly happened.

It was an existing deployment which was restarted, so it had to restore the database from the PV. Except for some password/user values we used the default values file.

After some digging I think we have an issue with docker/kubelet coordination and them not cleaning up containers and unmounting volumes correctly.

Strange however that postgres provided no log output and kept hanging on the starting postgresql line...

**Comment by andresbono** [comment]
Ok thanks for confirming it works now. It is indeed strange. Please, let us know again if you find issues that you think are related to the container itself so we can try to improve it.
