### ISSUE TITLE
Kubernetes slave replication fails 

### ISSUE THREAD

**Issue by boopathykpm** [bitnami/bitnami-docker-postgresql#180]
**Description**
When installing the PostgreSQL on the Kubernetes cluster, the slave replication fails when trying to do the pg_basebackup, below is the error 

```
postgresql 1:1:3.8 INFO  ==> Replicating the initial database
pg_basebackup: initiating base backup, waiting for checkpoint to complete
pg_basebackup: checkpoint completed
pg_basebackup: write-ahead log start point: 0/3000028 on timeline 1
pg_basebackup: starting background WAL receiver
pg_basebackup: created temporary replication slot "pg_basebackup_345"
    0/23668 kB (0%), 0/1 tablespace (...ami/postgresql/data/backup_label)
   42/23668 kB (0%), 0/1 tablespace (.../postgresql/data/global/1262_fsm)
  345/23668 kB (1%), 0/1 tablespace (...nami/postgresql/data/global/2698)
  600/23668 kB (2%), 0/1 tablespace (...l/data/pg_multixact/offsets/0000)
 1309/23668 kB (5%), 0/1 tablespace (...stgresql/data/base/13068/2606_vm)
 2015/23668 kB (8%), 0/1 tablespace (.../postgresql/data/base/13068/2657)
 2465/23668 kB (10%), 0/1 tablespace (...stgresql/data/base/13068/2602_vm)
 3365/23668 kB (14%), 0/1 tablespace (.../postgresql/data/base/13068/2754)
 3833/23668 kB (16%), 0/1 tablespace (.../postgresql/data/base/13068/3599)
 4253/23668 kB (17%), 0/1 tablespace (.../postgresql/data/base/13068/2840)
 4262/23668 kB (18%), 0/1 tablespace (.../postgresql/data/base/13068/2606)
 4646/23668 kB (19%), 0/1 tablespace (.../postgresql/data/base/13068/2690)
 5444/23668 kB (23%), 0/1 tablespace (.../postgresql/data/base/13068/2601)
 6263/23668 kB (26%), 0/1 tablespace (.../postgresql/data/base/13068/2685)
 7494/23668 kB (31%), 0/1 tablespace (...tgresql/data/base/13068/1247_fsm)
 7772/23668 kB (32%), 0/1 tablespace (.../postgresql/data/base/13068/3440)
 8106/23668 kB (34%), 0/1 tablespace (.../postgresql/data/base/13068/2607)
 8943/23668 kB (37%), 0/1 tablespace (...nami/postgresql/data/base/1/2833)
 9708/23668 kB (41%), 0/1 tablespace (...nami/postgresql/data/base/1/3467)
10177/23668 kB (42%), 0/1 tablespace (...nami/postgresql/data/base/1/3603)
11115/23668 kB (46%), 0/1 tablespace (...nami/postgresql/data/base/1/2664)
11641/23668 kB (49%), 0/1 tablespace (...nami/postgresql/data/base/1/2659)
12053/23668 kB (50%), 0/1 tablespace (...i/postgresql/data/base/1/3603_vm)
12650/23668 kB (53%), 0/1 tablespace (...nami/postgresql/data/base/1/2663)
13783/23668 kB (58%), 0/1 tablespace (.../postgresql/data/base/1/2617_fsm)
14699/23668 kB (62%), 0/1 tablespace (...nami/postgresql/data/base/1/3604)
15304/23668 kB (64%), 0/1 tablespace (...nami/postgresql/data/base/1/3079)
rpc error: code = Unknown desc = Error: No such container: 7802f93dc0df9fb59ebbeac6f5ce34f586dd58ff816a8b5a1058d9d4b5376607
```
After the above failure, the slave is getting crashed frequently with below error message

```
postgresql 1:3:2.1 INFO  ==> ** Starting PostgreSQL **
2019-12-12 14:43:20.207 GMT [1] LOG:  skipping missing configuration file "/bitnami/postgresql/data/postgresql.auto.conf"
postgres: could not find the database system
Expected to find it in the directory "/bitnami/postgresql/data",
but could not open file "/bitnami/postgresql/data/global/pg_control": No such file or directory
```
Even scaling down and scaling up the slave stateful set is not helping. The master is getting restarted after the slave gains the connection and trying to initialize the pg_basebackup, by that time the master getting restarted 

```
2019-12-12 14:21:30.461 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-12-12 14:21:30.461 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2019-12-12 14:21:30.479 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-12-12 14:21:30.642 GMT [325] LOG:  database system was shut down at 2019-12-12 14:21:30 GMT
2019-12-12 14:21:30.783 GMT [1] LOG:  database system is ready to accept connections
2019-12-12 14:22:03.027 GMT [345] LOG:  unexpected EOF on standby connection
2019-12-12 14:22:03.028 GMT [342] LOG:  could not receive data from client: Connection reset by peer
```
Suddenly the master's Readines and Liveness probe get failed
```
Warning  Unhealthy         13m (x4 over 14m)  kubelet, ip-10-16-28-16.test.com Liveness probe failed: 127.0.0.1:5432 - no response
  Warning  Unhealthy         13m (x7 over 14m)  kubelet, ip-10-16-28-16.test.com  Readiness probe failed: 127.0.0.1:5432 - no response
```

**Steps to reproduce the issue:**

1. Install PostgreSQL with the latest helm chart
2. Enabled EFS for persistence volume mount
 
**Describe the results you received:**

PostgreSQL slave is not starting as expected. 

**Describe the results you expected:**

PostgreSQL slave should start and should be pinging master for the replication, the master should not restart while the slave is trying to replicate. 

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes (AWS)

**Comment by andresbono** [comment]
Hi @boopathykpm, can you confirm that you experience the issue only when you use EFS volumes to persist the data?

What happens if you use a different provisioner storage class or even if you disable persistence in the chart?

**Comment by boopathykpm** [comment]
@andresbono It's happening with EFS, by disabling persistence and changing the different provisioner(EBS) it's working as expected.

**Comment by andresbono** [comment]
Oh ok, thanks for confirming it. Is it possible for you to use EBS volumes? I'm afraid that there is not so much we can do on our side if the issue is related to the performance of the persistent volumes.

**Comment by boopathykpm** [comment]
Thanks for the quick response, can I get a whole background kind what had happened, why the above-mentioned error is thrown?

On master, after the step `Generating local authentication configuration` there was a long wait. What is happening in the background? Why the wait is not happening when the persistence volume type is EBS?

**Comment by andresbono** [comment]
There is not so much I can tell you. This is the line of code that prints the message that you mention:

https://github.com/bitnami/bitnami-docker-postgresql/blob/fb4fb177687918fe2223a66f6c141cd4c281a562/11/debian-9/rootfs/libpostgresql.sh#L363

The next line is just a simple file write operation. All the app initialization of the container is in the file linked above.

Maybe those write operations, for some reason, can't be done in the EFS?

You can uncomment the following line in order to obtain a more detailed view of what is happening:

https://github.com/bitnami/bitnami-docker-postgresql/blob/fb4fb177687918fe2223a66f6c141cd4c281a562/11/debian-9/rootfs/entrypoint.sh#L6

Note that you will need to rebuild the container or mount the file.

**Comment by boopathykpm** [comment]
@andresbono  Thanks for the info, in EFS because of the burstable limit it happened, will check with provisioned IOPS for EFS to test it out. 

Thanks again for jumping in quickly and helping me out.

**Comment by opadron** [comment]
Hello, we've recently switched our postgres deployments to using replication and I believe we are being affected by this issue.  In our case, we are using `gp3` volumes provisioned by AWS EBS CSI driver.  I'm reasonably confident that provisioned IOPS is not an issue in our case, since we're provisioning the maximum IOPS allowed, but I'm not certain.

In any case, any troubleshooting assistance would be greatly appreciated.

**Comment by javsalgar** [comment]
Hi,

As this ticket is too old, could you create a new ticket with the logs and the steps to reproduce the issue?
