### ISSUE TITLE
Running bitnami/postgresql:12 as root does not work

### ISSUE THREAD

**Issue by blumfontein** [bitnami/bitnami-docker-postgresql#184]
**Description**

Running bitnami/postgresql:12 as root does not work. The same is on versions 10 and 11.

**Steps to reproduce the issue:**

1. Install this docker image: naimi/postgresql:v3.0 or bitnami/postgresql:12 with configured root user.
2. Container runs but postgresql starts and shuts down immediately without any error.

**Describe the results you received:**

Here is log from Rancher

12/23/2019 6:52:30 PMpostgresql 12:52:30.64 Welcome to the Bitnami postgresql container
12/23/2019 6:52:30 PMpostgresql 12:52:30.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
12/23/2019 6:52:30 PMpostgresql 12:52:30.64 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
12/23/2019 6:52:30 PMpostgresql 12:52:30.64 Send us your feedback at containers@bitnami.com
12/23/2019 6:52:30 PMpostgresql 12:52:30.65 
12/23/2019 6:52:30 PMpostgresql 12:52:30.65 INFO  ==> ** Starting PostgreSQL setup **
12/23/2019 6:52:30 PMpostgresql 12:52:30.71 INFO  ==> Validating settings in POSTGRESQL_* env vars..
12/23/2019 6:52:30 PMpostgresql 12:52:30.72 INFO  ==> Loading custom pre-init scripts...
12/23/2019 6:52:30 PMpostgresql 12:52:30.72 INFO  ==> Initializing PostgreSQL database...
12/23/2019 6:52:30 PMpostgresql 12:52:30.74 INFO  ==> postgresql.conf file not detected. Generating it...
12/23/2019 6:52:30 PMpostgresql 12:52:30.75 INFO  ==> pg_hba.conf file not detected. Generating it...
12/23/2019 6:52:30 PMpostgresql 12:52:30.75 INFO  ==> Generating local authentication configuration
12/23/2019 6:52:30 PMpostgresql 12:52:30.78 INFO  ==> Stopping PostgreSQL...

**Describe the results you expected:**

Running container is expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 13
  Running: 10
  Paused: 0
  Stopped: 3
 Images: 10
 Server Version: 18.09.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-72-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.65GiB
 Name: ds10-cirp
 ID: HIMN:5GNR:7BII:SANR:E3VB:6SZ7:NFLP:EPKQ:OUP6:4MPA:5L2W:3EWI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alemorcuq** [comment]
Hi, @blumfontein.

Thanks for reporting this. Setting the `BITNAMI_DEBUG` variable to `true` reveals that `initdb` can't be run as root:

```
❯ docker run --rm -ti -e "POSTGRESQL_PASSWORD=bitnami123" -e "BITNAMI_DEBUG=true" -u root bitnami/postgresql:12
postgresql 15:56:42.49
postgresql 15:56:42.49 Welcome to the Bitnami postgresql container
postgresql 15:56:42.49 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 15:56:42.50 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 15:56:42.50 Send us your feedback at containers@bitnami.com
postgresql 15:56:42.50
postgresql 15:56:42.50 INFO  ==> ** Starting PostgreSQL setup **
postgresql 15:56:42.53 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 15:56:42.59 INFO  ==> Loading custom pre-init scripts...
postgresql 15:56:42.59 INFO  ==> Initializing PostgreSQL database...
postgresql 15:56:42.59 DEBUG ==> Ensuring expected directories/files exist...
postgresql 15:56:42.60 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 15:56:42.60 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 15:56:42.60 INFO  ==> Generating local authentication configuration
initdb: error: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
postgresql 15:56:42.62 INFO  ==> Stopping PostgreSQL...
```

I will create an internal task to take care of this.

**Comment by blumfontein** [comment]
Hi,

Thank you for your assistance. Could you give some advice for now until fix, how can I do some OS installations? Generally, I want to install some locales. Here is my Dockerfile:

```

**Comment by marcosbc** [comment]
Hi @blumfontein, why don't you want to run as user 1001? In your case you could do it like this:

```FROM bitnami/postgresql:12.1.0

USER root

RUN echo 'ru_RU.UTF-8 UTF-8' >> /etc/locale.gen && \
    echo 'kk_KZ.UTF-8 UTF-8' >> /etc/locale.gen && \
    locale-gen

# reset user so PostgreSQL is run by 1001
USER 1001
```

Currently our container doesn't seem to support running as a root user. I've created an internal task for fixing this, but unfortunately I cannot give an ETA for when it will be completed.

It should not be difficult to implement that behavior, and since the initialization logic is open-source (you can find it inside the `rootfs` directory in this repository, i.e. [version 12 on Debian 9](https://github.com/bitnami/bitnami-docker-postgresql/tree/master/12/debian-9/rootfs)), feel free to contribute a fix if you identify the issue.

**Comment by blumfontein** [comment]
Hi @marcosbc 

Oh, I didn't know, that it is possible to redeclare user in Dockerfile. I will try to do this trick. Thank you.

**Comment by pacificsky** [comment]
I encountered this issue last night when running as a non-root user. `initdb` failed at exactly the same place. In my situation, pointing the postgres 'data' directory to the root of the bind volume in my `docker-compose.yml` resulted in the setup script unable to fix permissions for the non-root user. Instead of providing a descriptive error I would get a silent "exited with code 1" error. 

This works:
```
- postgres-data-volume:/bitnami/postgresql
```

This fails hard, silently:
```
- postgres-data-volume:/bitnami/postgresql/data
```

`BITNAMI_DEBUG` was the lifesaver after tearing my hair out for 2 hours. It should really be documented as part of the readme for every bitnami container image.

**Comment by marcosbc** [comment]
Thanks @pacificsky! You're totally right about that. We have created an internal task for documenting it.

**Comment by utkinpol** [comment]
Hi, could you pls explain - i am trying to run this from Rancher and all the available versions acts the same way, no matter how to alter the directory name:

postgresql 21:14:23.14 
postgresql 21:14:23.14 Welcome to the Bitnami postgresql container
postgresql 21:14:23.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 21:14:23.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 21:14:23.14 Send us your feedback at containers@bitnami.com
postgresql 21:14:23.14 
postgresql 21:14:23.15 DEBUG ==> Configuring libnss_wrapper...
postgresql 21:14:23.15 INFO  ==> ** Starting PostgreSQL setup **
postgresql 21:14:23.18 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 21:14:23.19 INFO  ==> Loading custom pre-init scripts...
postgresql 21:14:23.19 INFO  ==> Initializing PostgreSQL database...
postgresql 21:14:23.19 DEBUG ==> Ensuring expected directories/files exist...
postgresql 21:14:23.20 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 21:14:23.21 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 21:14:23.21 INFO  ==> Generating local authentication configuration
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".
Data page checksums are disabled.
fixing permissions on existing directory /bitnami/postgresql/data2 ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
2020-05-20 21:14:23.465 UTC [169] FATAL:  data directory "/bitnami/postgresql/data2" has wrong ownership
2020-05-20 21:14:23.465 UTC [169] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/bitnami/postgresql/data2"
postgresql 21:14:23.48 INFO  ==> Stopping PostgreSQL...
running bootstrap script ...

**Comment by utkinpol** [comment]
I am really just curious how is it possible for such a thing to be completely broken like this... :( 
Ignoring all the complexities - by a direct vanilla helm deployment from the: 
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install postgres1234 bitnami/postgresql

[rancher@rancher ~]$ kubectl get pods -w
NAME                        READY   STATUS        RESTARTS   AGE
postgres1234-postgresql-0   0/1     Terminating   6          6m37s
postgres1234-postgresql-0   0/1     Terminating   6          6m39s
postgres1234-postgresql-0   0/1     Terminating   6          6m39s
postgres1234-postgresql-0   0/1     Pending       0          0s
postgres1234-postgresql-0   0/1     Pending       0          0s
postgres1234-postgresql-0   0/1     ContainerCreating   0          0s
postgres1234-postgresql-0   0/1     ContainerCreating   0          1s
postgres1234-postgresql-0   0/1     Running             0          2s
postgres1234-postgresql-0   0/1     Error               0          3s
postgres1234-postgresql-0   0/1     Error               1          4s
postgres1234-postgresql-0   0/1     CrashLoopBackOff    1          5s
postgres1234-postgresql-0   0/1     Running             2          18s
postgres1234-postgresql-0   0/1     Error               2          19s
postgres1234-postgresql-0   0/1     CrashLoopBackOff    2          24s

What am i missing in this?

**Comment by marcosbc** [comment]
Hi @utkinpol, if you run a non-root container, there are some cases in which you need to set the proper permissions of data files before starting the container (i.e. when using NFS volumes). We have implemented `volumePermissions.enabled` which will enable an initContainer to do this automatically, you should be able to set it when deploying the chart via Rancher.

For more information see: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L48

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
