### ISSUE TITLE
POSTGRESQL_USERNAME can not drop POSTGRESQL_DATABASE

### ISSUE THREAD

**Issue by yelhouti** [bitnami/bitnami-docker-postgresql#187]
**Description**

**Steps to reproduce the issue:**

1. [Create container]
```
docker run --name postgresql -e POSTGRESQL_USERNAME=my_user -e POSTGRESQL_PASSWORD=password123 -e POSTGRESQL_DATABASE=my_database bitnami/postgresql:latest
```
2. [Enter container]
```
docker exec -it postgresql /bin/bash
```
3. [log into db as POSTGRESQL_USERNAME]
```
psql -U my_user
```
4. [try to drop POSTGRESQL_DATABASE]
```
DROP DATABASE my_database;
ERROR:  must be owner of database my_database
```
**Describe the results you received:**

As you can see POSTGRESQL_USERNAME is not the owner of POSTGRESQL_DATABASE

**Describe the results you expected:**

I expected POSTGRESQL_USERNAME to be the owner and not just have all the permissions for this database as described in documentation.

**Comment by juan131** [comment]
Hi @yelhouti 

As you mentioned, the user you specify is not the owner of the database, but a user with admin privileges on it. Everything is detailed in the link below:

- https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-user-on-first-run

To drop database, you need to use the `postgres` user (admin user) as shown below:

```console
$ docker run --name postgresql \
    -e POSTGRESQL_USERNAME=my_user \
    -e POSTGRESQL_PASSWORD=password123 \
    -e POSTGRESQL_DATABASE=my_database \
    -e POSTGRESQL_POSTGRES_PASSWORD=adminpassword123 \
    bitnami/postgresql:latest
$ docker exec -it postgresql /bin/bash
:/$ PGPASSWORD=$POSTGRESQL_POSTGRES_PASSWORD psql -U postgres
psql (11.6)
Type "help" for help.

postgres=# DROP DATABASE my_database;
DROP DATABASE
```

**Comment by yelhouti** [comment]
@juan131 don't you think it should be teh owner since it has all permissions? to allow backup restore...

**Comment by sameersbn** [comment]
@yelhouti If you drop the database as the user, you will not be able to create it again as the same user. you would need to escalate your privileges to the admin `postgres` user. Considering this; for backup/restore operations that DROP the existing database, you would have to use the `postgres` user instead.
