### ISSUE TITLE
Is there a way to create two DB on init?

### ISSUE THREAD

**Issue by psykidellic** [bitnami/bitnami-docker-postgresql#197]
This is not really an issue but rather a help question.

Our app use two database. One for configuration and one for actual data. Is it possible to initialize with two database on postgres startup? 

I see, I can do one database.

**Comment by dani8art** [comment]
Hi @psykidellic , thank you for opening this issue.

As I understand, you can do it using this: https://github.com/bitnami/bitnami-docker-postgresql#initializing-a-new-instance, you will need to create them manually using sql scripts. You could use our scripts as a reference https://github.com/bitnami/bitnami-docker-postgresql/blob/master/12/debian-10/rootfs/libpostgresql.sh#L555, I hope that fits your requirements.

Regards.

**Comment by psykidellic** [comment]
Thanks. I will look into this steps. This is probably what we want.
