### ISSUE TITLE
How to change postgres user password

### ISSUE THREAD

**Issue by pcm32** [bitnami/bitnami-docker-postgresql#199]
We use this image as part of the postgresql helm chart for kubernetes. We have a database running on one cluster, we stopped and rsync-ed the PVC to another cluster (following docs). The problem we have is that the postgres user password is set to some value that we cannot figure out (is the the same value as available on the $POSTGRES_PASSWORD variable (possibly because it was restarted at some point). How can we reset the password? Thanks!

**Comment by Mauraza** [comment]
Hello @pcm32,

for change the password you have to enter in the pod of the database:

`kubectl exec -ti release-postgresql-pod -n the-namespace bash`

In the pod, you have to change the password,;
Fist access to PostgreSQL with the user you want to change the password

`psql -Uyour-user`

Now use the following command to change the password for your current user

`\password`

If you have a secret for the database you have to update with the new password.

I hope that helps you.
