### ISSUE TITLE
Unable to set Server Configuration Options from command line

### ISSUE THREAD

**Issue by vaughnmb** [bitnami/bitnami-docker-postgresql#204]
**Description**
Unable to set server configuration options from the command line

**Steps to reproduce the issue:**

1. docker run --name postgres bitnami/postgresql:12.2.0 -c 'max_connections=150

**Describe the results you received:**

postgresql 18:23:26.34 Welcome to the Bitnami postgresql container
postgresql 18:23:26.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 18:23:26.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 18:23:26.34 Send us your feedback at containers@bitnami.com
postgresql 18:23:26.35 

/opt/bitnami/scripts/postgresql/entrypoint.sh: line 31: exec: max_connections=150: not found

**Describe the results you expected:**
I expected the container to start up and allow 150 max connections

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
```
Docker version 18.09.2, build 6247962
```

- Output of `docker info`:

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 33
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: sprbiwg7rg4meja6zsoxct4oq
 Is Manager: true
 ClusterID: f2n2o822csysb4vjuy11ppbfy
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.0.225
 Manager Addresses:
  192.168.0.225:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Linux Mint 19
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.55GiB
Name: brent-Latitude-7490
ID: DPXI:BOSX:K34Q:MK62:SU3E:EF2V:6RW7:LJKH:55C5:DK7U:H7MS:NB6I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by Mauraza** [comment]
Hi @vaughnmb,

to increasing `max_connection` you have to change in the file`postgresql.conf`. Please check you  how to do it in [https://github.com/bitnami/bitnami-docker-postgresql#configuration-file](https://github.com/bitnami/bitnami-docker-postgresql#configuration-file)

**Comment by vaughnmb** [comment]
That is a little disappointing from a deployment stand point.  Since this image doesn't support command line server configuration options, you have to either keep a  customized version of this image or upon deployment you have to copy a .conf file to the remote machine and mount it as a volume.  Any chance that command line Server Configuration options will be supported in the future?

**Comment by Mauraza** [comment]
Maybe, you can use something like  'docker run -ti --name postgres bitnami/postgresql:12.2 bash'  or something similar, you can get more information in [docker documentation](https://docs.docker.com/engine/reference/run/#block-io-bandwidth-blkio-constraint).
I hope that information can help you.

**Comment by mirekphd** [comment]
> 
> That is a little disappointing from a deployment stand point. Since this image doesn't support command line server configuration options, you have to either keep a customized version of this image or upon deployment you have to copy a .conf file to the remote machine and mount it as a volume. Any chance that command line Server Configuration options will be supported in the future?

I second that feature request. As a model solution, see how `bitnami/mariadb` has this solved: one can pass to the container any string of startup parameters recognized by the db server, using an environment variable `MARIADB_EXTRA_FLAGS` (e.g value: MARIADB_EXTRA_FLAGS="--max_connections=600"), as documented [here](https://hub.docker.com/r/bitnami/mariadb/). This will also help solve: https://github.com/bitnami/bitnami-docker-postgresql/issues/114

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the input. I agree that, if it worked for other solutions like MariaDB or MongoDB, here it would be helpful. I will create a task for evaluating it. I cannot guarantee a strict ETA, but I will update the ticket when we have more news.

**Comment by MrGraversen** [comment]
Hi @javsalgar, any news on this matter?

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. I will forward this to the team to see if it can be prioritized.

**Comment by ITJamie** [comment]
bump. same request to allow setting of startup commandline args

> > That is a little disappointing from a deployment stand point. Since this image doesn't support command line server configuration options, you have to either keep a customized version of this image or upon deployment you have to copy a .conf file to the remote machine and mount it as a volume. Any chance that command line Server Configuration options will be supported in the future?
> 
> I second this feature request of @vaughnmb. As a model solution, see how `bitnami/mariadb` has solved this issue: one can pass any string of startup parameters recognized by the db server to the container using an environment variable called `MARIADB_EXTRA_FLAGS` (e.g value: `MARIADB_EXTRA_FLAGS="--max_connections=600"`), as documented [here](https://hub.docker.com/r/bitnami/mariadb/).
> 
> Adding this new env (called e.g. `POSTGRESQL_EXTRA_FLAGS`) will also help solve #114.

**Comment by javsalgar** [comment]
I will forward this to the engineering team for re-prioritization

**Comment by jozefrebjak** [comment]
@javsalgar Same request here. I don't understand why we can't configure some paramters within ENV. Especially `max_connections` is something what is edited very often. We are trying to use this image with MAAS in HA where we have two controllers and every one is producing 40 connections and we are getting a lot of time Error:

```
FATAL: remaining connection slots are reserved for non-replication superuser connections
```

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. I forwarded to the team to see if it can be re-prioritized. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by alemorcuq** [comment]
Hi everyone. We have added the `POSTGRESQL_EXTRA_FLAGS` [environment variable](https://github.com/bitnami/bitnami-docker-postgresql#passing-extra-command-line-flags-to-postgresql) to the image.

**Comment by mhyousefi** [comment]
Hey @alemorcuq
Good day to you.
I've been fooling around with `POSTGRESQL_EXTRA_FLAGS` to set `max_connection` but have failed. Based on what I read at [this doc](https://www.postgresql.org/docs/9.5/app-postgres.html), I set  `POSTGRESQL_EXTRA_FLAGS` to `-c 'max_connections=201'` and `-c max_connections=201`, but it makes no difference. I suspect that the version I'm using (`13.4.0`) isn't hooked up with this beautifully useful env. Could you shed some light please?

**Comment by mhyousefi** [comment]
Alright so I verified that what I was doing does work for version 14. I'll probably upgrade then...
