### ISSUE TITLE
Feature request: Support for RUM indexes

### ISSUE THREAD

**Issue by ThomasLagace** [bitnami/bitnami-docker-postgresql#206]
**Description**
I have a program that takes advantage of Postgresql's [RUM access method](https://github.com/postgrespro/rum), however your image doesn't have support for it built in. I'd love to take advantage of your image for deployment on Kubernetes, and this is the only thing that's holding me back.

Thanks!

**Comment by miguelaeh** [comment]
Hi @ThomasLagace ,
Thank you very much for requiring this feature. We will create a task on our side to evaluate it.
Regards
