### ISSUE TITLE
Throughput issue

### ISSUE THREAD

**Issue by thegeeekdb** [bitnami/bitnami-docker-postgresql#207]
I have experienced using this image a throughput issue, when using postgresql image I am able to get double the throughput I am getting with bitnami images, can you please help in identifying the issue

**Comment by thegeeekdb** [comment]
Looks like the issue is coming from version 11.7 to 12.
When using 12 I can see half the throughput, is this a known issue ?

**Comment by juan131** [comment]
Hi @thegeeekdb 

Could you please provide more information about this issue? What specific steps did you perform to measure the throughput between the different images?
