### ISSUE TITLE
stable postgis support tag. (6.5.7) ??

### ISSUE THREAD

**Issue by naxaamulya** [bitnami/bitnami-docker-postgresql#210]
https://github.com/bitnami/charts/tree/master/bitnami/postgresql
according to docs In this version, the chart will use PostgreSQL with the Postgis extension included.(6.5.7). The documents show few information about postgis. I want to know is this only postgis image tag.??
thank you.

**Comment by beltran-rubo** [comment]
Hi,

PostGIS is included in all the PostgreSQL container images. It is included in the version of the Chart 6.5.7 and newer versions. Let us know if you have any other questions about this.

**Comment by naxaamulya** [comment]
thank you @beltran-rubo 
so https://hub.docker.com/r/bitnami/postgresql/
all these docker images tags have postgis support automatic.
I can use any images tag. 
Thank you for your time and consideration.

**Comment by rafariossaa** [comment]
Hi @naxaamulya ,
  No all the container versions have support for postgis, it was include at [these](https://github.com/bitnami/bitnami-docker-postgresql#9615-r82-9615-ol-7-r92-9615-centos-7-r91-10100-r82-10100-ol-7-r90-10100-centos-7-r91-1150-r80-1150-centos-7-r87-1150-ol-7-r92-1200-r11-1200-centos-7-r17-and-1200-ol-7-r17) postgres container releases.

Best regards

**Comment by naxaamulya** [comment]
Thank you very much.

**Comment by rafariossaa** [comment]
I am closing this issue.
