### ISSUE TITLE
Can we use some other user other than 1001

### ISSUE THREAD

**Issue by infinitedeep** [bitnami/bitnami-docker-postgresql#211]
Can we use a user other than 1001.
As 1001 might already be used on the host.Is updating dockerfile the only option ?

**Comment by andresbono** [comment]
Hi @infinitedeep, you can use UIDs different than 1001. For instance, with `docker run`, you can do:

```
docker run --user 1002 -e POSTGRESQL_PASSWORD=my_password bitnami/postgresql
```

**Comment by infinitedeep** [comment]
@andresbono Even if we run with docker user flag, [this](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/12/debian-10/Dockerfile#L36) line should be changed to 1002 or is that fine.
