### ISSUE TITLE
POSTGRES_PASSWORD can't contain "$" (dollar sign) character.

### ISSUE THREAD

**Issue by caiges** [bitnami/bitnami-docker-postgresql#213]
**Description**

Running the container including a `POSTGRES_PASSWORD` that contains a `$` character should work but the entrypoint fails, mostly likely due to expansion in the `postgresql_env` function.

**Steps to reproduce the issue:**

1. Run the postgres container including a `POSTGRES_PASSWORD` with a `$` character.

**Describe the results you received:**

```
docker run -e POSTGRES_PASSWORD='$tacos' docker.io/bitnami/postgresql:11.4.0                                             
/entrypoint.sh: line 14: tacos: unbound variable
```

**Describe the results you expected:**

The entrypoint should accept my password.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

`docker.io/bitnami/postgresql:11.4.0` does not work.

- Output of `docker version`:

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 2
  Paused: 0
  Stopped: 7
 Images: 221
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-26-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 38.81GiB
 Name: xipi
 ID: KOR7:Z6BJ:TA2T:6RBA:6M7R:X63V:P23E:H2QI:RU5J:PDO5:EJK3:DGYB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: caiges
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by javsalgar** [comment]
Hi!

Thanks for letting us know. We've had issues with several characters in the passwords and I'm not sure if we came across this one before. I will forward it for evaluation so we can consider it for future releases. However, as it is not a critical feature, we cannot guarantee an ETA.

**Comment by Syntaf** [comment]
I ran into this bug while using the `bitnami/postgresql` chart as a dependency to another chart in my kubernetes cluster.

After hours of going down the rabbit hole I realize now it was all from simply having a `$` in my password. I had a values override file that specified a password:

```
# secrets.yaml

postgresql:
  postgresqlPassword: 12Kdjf52KKnv$8
```

However when I deployed the chart with `helm upgrade -f secrets.yaml k8s/my-project-chart` I kept encountering what seemed to be a really odd error causing the postgresql pod to get stuck in a `CrashLoopBackOff` state:

```
2020-05-27 16:28:09 /opt/bitnami/scripts/postgresql/entrypoint.sh: line 18: $8: unbound variable
```

I confused `$8` for a specific argument in `entrypoint.sh` and cue hours of digging around. After stumbling across this ticket I realize `$8` only refers to the end of the password \*facepalm\*

Just posting this comment in hopes that the next pour soul who goes down this path finds it and realizes they just need to remove the dollar sign from their password.

**Comment by javsalgar** [comment]
Thank you very much for sharing your experience!! The community will benefit from this

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
