### ISSUE TITLE
touch /tmp/postgresql.trigger.5432 does not work

### ISSUE THREAD

**Issue by blumfontein** [bitnami/bitnami-docker-postgresql#214]
**Description**

As mentioned in documentation I should create a file /tmp/postgresql.trigger.5432 to reconfigure slave to act as master, but nothing happens. Postgresql version: 11.6

**Steps to reproduce the issue:**

1. Configure master-slave replication
2. run "touch /tmp/postgresql.trigger.5432" on slave
3. Try to insert some row to some table to slave database

**Describe the results you received:**

"ERROR:  cannot execute INSERT in a read-only transaction" happens

**Describe the results you expected:**

The row is inserted to the table

**Additional information you deem important (e.g. issue happens only occasionally):**

Master-slave was configured at Rancher 2, which uses Kubernetes as orchestration system.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 45
  Running: 33
  Paused: 0
  Stopped: 12
 Images: 24
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-99-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.9GiB
 Name: ds02-naimi
 ID: CGGB:V23U:WBYZ:XDRQ:JCRN:E3ZN:6NLJ:CNNR:JXJ5:WTPW:KUSN:K5OR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

This was for the case that the master goes down. Did you also restart all the other containers changing the link so the rest use this new node as the master?  From the documentation

> Note: The configuration of the other slaves in the cluster needs to be updated so that they are aware of the new master. This would require you to restart the other slaves with --link postgresql-slave:master as per our examples.

**Comment by blumfontein** [comment]
Hi,

> This was for the case that the master goes down. 

Yes, master container was down at that moment. 

> Did you also restart all the other containers changing the link so the rest use this new node as the master?

No, I didn't restart other containers because I can't switch one of the slaves as being master first.

I also tried to setup master-slave configuration on Rancher 1, which uses Cattle orchestration, and reconfigure slave and it seems to work there. Maybe it is Kubernetes related issues.

If there is no chance to fix this, could you provide instructions, how to reconfigure slave manually?

Regards

**Comment by blumfontein** [comment]
Hi,

Could you explain what "touch /tmp/postgresql.trigger.5432" actually does in configuration or filesystem? I will do same by hands

Regards

**Comment by javsalgar** [comment]
Hi,

I was able to do the promotion just like the documentation says:

This is in one of the slaves, launched like this

```
docker run --name postgresql-slave2   --link postgresql-master:master   -e POSTGRESQL_REPLICATION_MODE=slave   -e POSTGRESQL_MASTER_HOST=master   -e POSTGRESQL_MASTER_PORT_NUMBER=5432 -e POSTGRESQL_POSTGRES_PASSWORD=password123  -e POSTGRESQL_REPLICATION_USER=my_repl_user   -e POSTGRESQL_REPLICATION_PASSWORD=my_repl_password -e POSTGRESQL_PASSWORD=password123   bitnami/postgresql:12
```

```
I have no name!@742c2aa84032:/opt/bitnami/postgresql/conf$ touch /tmp/postgresql.trigger.5432
I have no name!@742c2aa84032:/opt/bitnami/postgresql/conf$ PGPASSWORD=password123 psql -U postgres
psql (12.2)
Type "help" for help.

postgres=# create database dbarranco;
CREATE DATABASE
postgres=#
```


What you can see in the logs:

```
2020-05-05 08:46:35.634 GMT [172] LOG:  promote trigger file found: /tmp/postgresql.trigger.5432
2020-05-05 08:46:35.634 GMT [176] FATAL:  terminating walreceiver process due to administrator command
2020-05-05 08:46:35.637 GMT [172] LOG:  invalid record length at 0/4000060: wanted 24, got 0
2020-05-05 08:46:35.637 GMT [172] LOG:  redo done at 0/4000028
2020-05-05 08:46:35.648 GMT [172] LOG:  selected new timeline ID: 2
2020-05-05 08:46:35.719 GMT [172] LOG:  archive recovery complete
2020-05-05 08:46:35.739 GMT [1] LOG:  database system is ready to accept connections
```

This is something supported in PostgreSQL: https://www.postgresql.org/docs/12/pgstandby.html

**Comment by blumfontein** [comment]
Hi

```
pg_ctl promote -D /bitnami/postgresql/data
```

helped me to resolve my issue

**Comment by javsalgar** [comment]
Hi,

That could be another option, thanks for sharing!
