### ISSUE TITLE
Initdb fails because the current user is root

### ISSUE THREAD

**Issue by mplescano** [bitnami/bitnami-docker-postgresql#218]
https://github.com/bitnami/bitnami-docker-postgresql/blob/e8453e1cd4758807ca7e0bd5f071d8183ab181cb/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L883

it's needed to change this line by:
exec gosu "$POSTGRESQL_DAEMON_USER" "$POSTGRESQL_BIN_DIR/initdb" -E UTF8 -D "$POSTGRESQL_DATA_DIR" -U "postgres"

**Comment by javsalgar** [comment]
Hi,

I guess that you are running the container as root, am I right?

**Comment by mplescano** [comment]
Yes, but the root problem is that my container doesn't have the user 1001 created beforehand. I had to add this inside of my container and restart:
/usr/sbin/useradd -ms /bin/bash -g root 1001

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. I'm working on a fix. I will update the ticket when I have more details. Thanks for reporting.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision of the container that should addres the issue.

https://github.com/bitnami/bitnami-docker-postgresql/commit/76db2cef912dcef02d678a2f45eb17af3a5ba877
