### ISSUE TITLE
Use of bitnami/postgresql with AWS RDS Postgresql

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-postgresql#223]
Rather than host the database myself I'd like to use AWS's RDS Postrgesql. I already have an account and have set up the table. I can access this table from two standard applications on my laptop. However I need to access it from my php application running in bitnami/php-fpm. But the php.ini built into bitnami/php-fpm doesn't have postgresql enabled! Can I use bitnami-docker-postgresql to access AWS RDS Postgresql? Is there any documentation on how to do this?

**Comment by dani8art** [comment]
Hi @richb201, what would you want to do? I think you can enable postgresql in `bitnami/php-fmp` adding your custom config like this https://github.com/bitnami/bitnami-docker-php-fpm#add-additional-ini-files

BTW, you also can execute queries against your own postgresql instance using `bitnami/postgresql`. Could you try this?

```console
docker run --rm -ti bitnami/postgresql psql --help
```

**Comment by richb201** [comment]
Thanks for the response. I ended up hiring a consultant who got my
connection to RDS postgress working. Now I am working on trying to get my
phpCRUD to access RDS Postgres. Specifically I am trying to store images
and it seems that phpCrud wants to use file storage for images (with a
path). I want to use a database field (up to 1G per field). This is to
allow  AWS to take care of the backups.

**Comment by dani8art** [comment]
That sounds good, I like you finally found the solution and thank you for keeping us updated with the status.
