### ISSUE TITLE
mkdir: cannot create directory ‘/bitnami/postgresql/data’: File exists

### ISSUE THREAD

**Issue by yaakov-berkovitch** [bitnami/bitnami-docker-postgresql#224]
**Description**
I perform a migration from non kubernetes environment, to a kubernetes environment, and i want to reuse the postgresql data storage lcoated on the file system.

Deploy the postgresql chart (version 8.10.5), with postgres image bitnami/postgresql:12.3.0-debian-10-r18 on kubernetes cluster v1.18.
During the init of the postgresql pod, an error raise:
mkdir: cannot create directory ‘/bitnami/postgresql/data’: File exists

**Steps to reproduce the issue:**

1. run postgresql and create databases
2. deploy kubernetes, postgresql chart, and persistent volume that reuse the postgresql data folder created in (1)

**Describe the results you received:**

Following the log of the postgresql pod:
```
postgresql 07:56:52.59
postgresql 07:56:52.59 Welcome to the Bitnami postgresql container
postgresql 07:56:52.59 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 07:56:52.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 07:56:52.60
postgresql 07:56:52.61 INFO  ==> ** Starting PostgreSQL setup **
postgresql 07:56:52.68 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 07:56:52.68 INFO  ==> Loading custom pre-init scripts...
postgresql 07:56:52.69 INFO  ==> Initializing PostgreSQL database...
mkdir: cannot create directory ‘/bitnami/postgresql/data’: File exists
postgresql 07:56:52.71 INFO  ==> Stopping PostgreSQL...

```

**Describe the results you expected:**

Postgresql chart will deploy and the data of the previous run will be available.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:13:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @yaakov-berkovitch ,
It seems that PostgreSQL is trying to initialize the databases again, could you share how have you provided the existing PVCs?
