### ISSUE TITLE
docker build - download URL "stacksmith" not working

### ISSUE THREAD

**Issue by mzwettler2** [bitnami/bitnami-docker-postgresql#229]
I tried a docker build but got an error because the download URL is not working.

bitnami-docker-postgresql/12/debian-10/prebuildfs/opt/bitnami/scripts/libcomponent.sh:
...
DOWNLOAD_URL="https://downloads.bitnami.com/files/stacksmith"
...

Any idea?

-Markus

**Comment by rafariossaa** [comment]
Hi,
  I have just built postgresql 12 and I got no issues.
  Could you try again and paste the log of the building ?

Thanks

**Comment by mzwettler2** [comment]
Hi,

Putting this URL into a web browser gives error 404.

Running docker build shows:
...
Step 8/22 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql" "12.3.0-9" --checksum 877ebace3f64a532aa4b9dfc6078729c0082dd5885139d15aa6208d4dbc21968
 ---> Running in 323df00e2f17
Downloading postgresql-12.3.0-9-linux-amd64-debian-10 package
Verifying package integrity
sha256sum: postgresql-12.3.0-9-linux-amd64-debian-10.tar.gz: No such file or directory
sha256sum: WARNING: 1 listed file could not be read
postgresql-12.3.0-9-linux-amd64-debian-10.tar.gz: FAILED open or read
tar (child): postgresql-12.3.0-9-linux-amd64-debian-10.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'postgresql-12.3.0-9-linux-amd64-debian-10.tar.gz': No such file or directory
Removing intermediate container 323df00e2f17
 ---> 1e5f4e45a0b4
Step 9/22 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.12.0-1" --checksum 51cfb1b7fd7b05b8abd1df0278c698103a9b1a4964bdacd87ca1d5c01631d59c
 ---> Running in 623090e028dc
Downloading gosu-1.12.0-1-linux-amd64-debian-10 package
Verifying package integrity
gosu-1.12.0-1-linux-amd64-debian-10.tar.gz: FAILED open or read
sha256sum: gosu-1.12.0-1-linux-amd64-debian-10.tar.gz: No such file or directory
sha256sum: WARNING: 1 listed file could not be read
tar (child): gosu-1.12.0-1-linux-amd64-debian-10.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove 'gosu-1.12.0-1-linux-amd64-debian-10.tar.gz': No such file or directory
Removing intermediate container 623090e028dc
 ---> 8e60e54199f9
...

-Markus

**Comment by mzwettler2** [comment]
Hi,
It worked. The problem was based on our proxy ssl certificate.
Sorry for any inconvinience.
-Markus
