### ISSUE TITLE
How to integrate a wal based backup solution?

### ISSUE THREAD

**Issue by mzwettler2** [bitnami/bitnami-docker-postgresql#231]
Hi,

We are in need for wal based backups including a full backup catalog.
Therefore we want to use a backup solution like "barman"  or "pgbackrest".
What's the best way to integrate them?
Any idea?

-Markus

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but I have not experience with those backup solutions, but I have taken a quick look at their documentation. I seems that depending on the configuration you want to set you will need to access to the files and the configuration files.
  As general rule, you can provide a configuration file as indicated [here](https://github.com/bitnami/bitnami-docker-postgresql#user-content-configuration-file), and the data files directory is at `/bitnami/postgresql/data`. Also, you can add scripts to the initialization to perform certain actions.

  Maybe if you indicate what it is needed I can be more helpful.

**Comment by mzwettler2** [comment]
Hi,
It's not that trouble to containerize such a backup service. Both services are pull based (barman: pg_basebackup or ssh; pgbackrest: ssh). The backup configuration has be scheduled at the backup service container. I'm not sure how to configure this with the backup service container while provisioning a new postgres container? Any idea?
-Markus

**Comment by rafariossaa** [comment]
Hi,
  If those tools only need access to the filesystem, you can use the current container for postgresql, a new one where the backup tools are, and mount the postgesql data file system in this container too.
  I am not very sure if this is what is needed for these backup tools to work.

**Comment by mzwettler2** [comment]
Hi,
You don't need any direct access to the filesystem as this is done by ssh/scp or pg_basebackup remotely.
But you need some entries in the backup server config files for every container you are creating.
I'm not sure how to edit config files into container 1 (backup server) while while creating container 2 (postgres cluster).
That's my question.
-Markus

**Comment by marcosbc** [comment]
> But you need some entries in the backup server config files for every container you are creating.

In that case you would either need to have the hardcoded list of existing DBs, or use some service discovery tool for detecting them (or implement it on your side).

>  I'm not sure how to edit config files into container 1 (backup server) while while creating container 2 (postgres cluster).

You could always mount the configuration files externally, into the container, i.e.:

```yaml
      - './myfile:/path/to/file.conf'
```

And whenever you need to change it, do it from your computer and re-deploy the Docker image.

**Comment by mzwettler2** [comment]
We are using Kubernetes, Helm + Docker. Developers dynamically (un-)deploy on their own. We are in need for some kind of fully automated configuration mechanism. Meaning the backup configuration entries have to be added by "???" but not by hand. I'm searching for this "???".
-Markus

**Comment by marcosbc** [comment]
Unfortunately I'm not familiar of any tool that offers the functionality of backups creation for any database deployed by developers, without the need for knowing the specific list of endpoints for databases.

The only thing that occurs to me, is for you to workaround the problem in another way:

* Create a shell script in a machine with access to all DB pods, so it loops through the list of DB pods and run the backup commands.
* Create a K8s cron job per DB to back them up in a periodic manner.

If that's not valid for you, then unfortunately I don't think there's much I can do to help. If you know of that solution, we'd appreciate to let us know to evaluate adding support for it in our catalog.

**Comment by mzwettler2** [comment]
Thanks. I will talk to the barman and pgbackrest guys.
