### ISSUE TITLE
Kintohub console not printing Postgres Connection URL.

### ISSUE THREAD

**Issue by Fitzpa** [bitnami/bitnami-docker-postgresql#232]
**Description**
After deploying Postgres through Kintohub, the console never logs out the Postgres connection URL. It just says 'listening to console logs...'
The overview tab shows that the instance was created and says that it is healthy. Not sure what to do.

**Steps to reproduce the issue:**

1. Click create service
2. Click "from Catalog" tab
3. Click PostgreSQL
4. Generate a random password and a random root password as well as create a name.
5. Click Deploy

**Describe the results you received:**

The console never displays the connection URL.

**Describe the results you expected:**

The console to display the connection URL.

**Comment by joancafom** [comment]
Hi @Fitzpa ,

Thanks for your issue. Are yo using the container solution or the Chart? I am not very familiar with Kintohub, but did you succeed in deploying other bitnami containers there? Can you provide with the exact logs the console outputs? In theory, you should be able to see something similar to this (container):

```console
$ docker-compose up
bitnami-docker-postgresql_postgresql_1 is up-to-date
Attaching to bitnami-docker-postgresql_postgresql_1
postgresql_1  | postgresql 13:42:13.59
postgresql_1  | postgresql 13:42:13.59 Welcome to the Bitnami postgresql container
postgresql_1  | postgresql 13:42:13.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql_1  | postgresql 13:42:13.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql_1  | postgresql 13:42:13.60
postgresql_1  | postgresql 13:42:13.61 INFO  ==> ** Starting PostgreSQL setup **
postgresql_1  | postgresql 13:42:13.62 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql_1  | postgresql 13:42:13.62 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
postgresql_1  | postgresql 13:42:13.63 INFO  ==> Loading custom pre-init scripts...
postgresql_1  | postgresql 13:42:13.63 INFO  ==> Initializing PostgreSQL database...
postgresql_1  | postgresql 13:42:13.66 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql_1  | postgresql 13:42:13.66 INFO  ==> Generating local authentication configuration
postgresql_1  | postgresql 13:42:14.93 INFO  ==> Starting PostgreSQL in background...
...
```
Thanks!
