### ISSUE TITLE
Multiple master-slave failover with bitnami image results in postgresql checkpoint error making the cluster unavailable.

### ISSUE THREAD

**Issue by varsraja** [bitnami/bitnami-docker-postgresql#233]
Setup:
We have 3 node cluster where we deploy the bitnami postgres containers in docker. The nodes are in different machines but reachable to each other in same network.
Assume Node A , Node B , Node C 
We have a script which based on a condition makes one of the nodes as Master and rest as slaves.  It also ensures that the Master postgres always runs in same IP address ensuring the primary conninfo need not be changed in slaves. 
The data volumes are also persisted.

The env we set for master : 
    export POSTGRESQL_REPLICATION_MODE="master"                                                                                         
    export POSTGRESQL_SYNCHRONOUS_COMMIT_MODE="on"                                                                                      
    export POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS="0"  

The env we set for slave : 
    export POSTGRESQL_REPLICATION_MODE="slave"

The replication is in async mode and default bitnami postgres conf is applied.

Scenario:
1. When we do 1 -2 failovers , the docker containers come up properly  in the sense 1 Master and 2 slaves are running and replication is also working fine. 
Failure: After another random set of failovers , the  master postgres doesnt start saying :  

2020-07-20 02:57:48.966 GMT [72] LOG:  invalid resource manager ID in primary checkpoint record
2020-07-20 02:57:48.966 GMT [72] PANIC:  could not locate a valid checkpoint record
2020-07-20 02:57:49.090 GMT [73] LOG:  incomplete startup packet
2020-07-20 02:57:49.148 GMT [1] LOG:  startup process (PID 72) was terminated by signal 6: Aborted
2020-07-20 02:57:49.148 GMT [1] LOG:  aborting startup due to startup process failure
2020-07-20 02:57:49.152 GMT [1] LOG:  database system is shut down

Is there any way to recover the setup.

**Comment by dani8art** [comment]
Hi @varsraja, are you using docker-compose or just docker to run your containers? if you are using docker-compose, please, could you share with us the YAML file in order to try the same as you are doing in your machines? otherwise, if you are using docker only, please, could you share de docker commands that you executed?. 

Thanks!

**Comment by varsraja** [comment]
We are run docker commands to run the containers across the different machines . 
We use the go docker api to achieve this.
An equivalent docker run would be
For master 
docker run -d  -p 5432:5432  --image bitnami/postgresql:12.3-10  --env POSTGRESQL_MASTER_HOST=x.x.x.x --env POSTGRESQL_REPLICATION_USER=replica --env POSTGRESQL_REPLICATION_PASSWORD=test123 --env  POSTGRESQL_REPLICATION_MODE=master  -v /home/varsraja/data:/bitnami/postgresql/  --name master 

For slaves 
docker run -d  -p 5432:5432  --image bitnami/postgresql:12.3-10  --env POSTGRESQL_MASTER_HOST=x.x.x.x --env POSTGRESQL_REPLICATION_USER=replica --env POSTGRESQL_REPLICATION_PASSWORD=test123 --env  POSTGRESQL_REPLICATION_MODE=slave  -v /home/varsraja/data:/bitnami/postgresql/  --name master 

When we switch the volume remains the same but the role changes and the postgresql master host ip remains the same x.x.x.x .

**Comment by dani8art** [comment]
Hi @varsraja it maybe could be related to the volume, I tried to replicate your environment for both scenarios: 1. keeping the same volume and changing the role and 2. moving the master's volume to the one that gets the role master.

1. Getting the same as you, an error when some invalid resource manager ID in primary checkpoint record.
2. Keep working fine, but I don't know if it is going to fit your requirements

BTW, A would like to suggest to take a look at our HA solution for postgresql https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/docker-compose.yml and also combined with https://github.com/bitnami/bitnami-docker-pgpool

**Comment by varsraja** [comment]
Hi dani8art, 
Thanks a lot. 
Yeah 2 doesnt fit our requirement. 
The problem with repmgr is that we dont know beforehand the slaves that will be part of cluster. Is it mandatory for master to know who all will be the slaves? 
Our requirement is for master to come up and then  the slaves come up at random time and attach themselves to cluster.
We would be interested to use the repmgr if 
1. It will allow any slave to attach to the cluster.

**Comment by dani8art** [comment]
It seems the problem comes when you switch the role but keep the volume between a master and slave node, so you could fix your problem keeping the master with its own volume always. 

Regarding repmgr, you are right this solution needs to know who is going to be the slaves. However, is there any possibility to identify your nodes? even if they are not connected yet you can pass them to the master.

**Comment by varsraja** [comment]
> It seems the problem comes when you switch the role but keep the volume between a master and slave node, so you could fix your problem keeping the master with its own volume always.
>  **But the master role keeps shifting between the 3 instances.  Is there a way within bitnami data folder that helps us segregating them. Our idea was to replicate the contents of db to be available. For instance if master node goes down, the failover to new slave node getting elected to master and continue to have db for updates.**

> Regarding repmgr, you are right this solution needs to know who is going to be the slaves. However, is there any possibility to identify your nodes? even if they are not connected yet you can pass them to the master.

**Comment by dani8art** [comment]
> But the master role keeps shifting between the 3 instances. Is there a way within bitnami data folder that helps us segregating them. Our idea was to replicate the contents of db to be available. For instance if master node goes down, the failover to new slave node getting elected to master and continue to have db for updates.

Can you try to initialize all of them as master? after that reconfigure it using the logic of shifting between the 3 instances, let's see if the problem is just changing slave -> master or also master -> slave

**Comment by varsraja** [comment]
If I initialize all of the mas master, the identifier generated are different and the once i move one of them to slave, it starts complaining about the primary identifier being different from slave expected identifier.

**Comment by dani8art** [comment]
> it starts complaining about the primary identifier being different from slave expected identifier.

So I would say this confirms my suspicious, you cannot change the role just changing the env vars since the persisted data will save also information about the role and it will fail at some point. Could you try executing any command before changing the roles, I mean, first execute a command that changes the role gracefully between all the postgresql instances then shut them down and change the roles.

**Comment by varsraja** [comment]
Hi dani8art,
Yes , we are also thinking the same. When we use the bitnami/ postgresql with repmgr , what does the repmgr effectively do when a failover is triggered. Our understanding is when master node goes to slave, we have remove the whole data and sync up again from new master. What should we do for the rest of the slaves/backup. Do they also have to remove their data and pg_basebackup with the new master or pg_rewind sufficient.
It would be helpful if you can confirm what needs to be done on other backups when new master with same primary ip comes up.

**Comment by dani8art** [comment]
> Do they also have to remove their data and pg_basebackup with the new master or pg_rewind sufficient.

I would sync all the new slaves from the new master as it is going to be the new source of truth.
