### ISSUE TITLE
Upstream chart uses POSTGRES_PASSWORD, Docker image uses POSTGRESQL_PASSWORD

### ISSUE THREAD

**Issue by dustinmm80** [bitnami/bitnami-docker-postgresql#234]
**Description**

I am testing upgrading the GitLab Helm chart to use PostgreSQL version 12 ([gitlab issue](https://gitlab.com/gitlab-org/charts/gitlab/-/issues/2194)). We are pulling in the `bitnami/postgresql` chart as a Helm dependency at version 8.9.4. When updating the `postgresql.image.tag` value from `11.7.0` to `12`, the `postgresql` pod fails to start, giving this error message:

```
CrashLoopBackOff "The POSTGRESQL_PASSWORD environment variable is empty or not set."
```

There is no `POSTGRESQL_PASSWORD` environment variable on the pod, but there is `POSTGRES_PASSWORD`, which is set to the correct value. `POSTGRES_PASSWORD` [is used downstream in the Helm chart](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml#L210), so it seems there is a mismatch between environment variables with new images from this repository.

Since the `11.7.0` tag works with `POSTGRES_PASSWORD`, it appears that [postgresql-env.sh](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh) is resetting variables set by [libpostgresql.sh](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh). `postgres-env.sh` is now sourced after `libpostgresql.sh` [in the Dockerfile](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/postgresql/run.sh#L15). The `postgresql-env.sh` was added with [this commit](https://github.com/bitnami/bitnami-docker-postgresql/commit/543bbe34f9047f0524d8e32c7debf8e067ad8bdc#diff-e52440646458a3be1a6fcac9cc39e2cf).

**Steps to reproduce the issue:**

1. Deploy the GitLab chart: `helm upgrade --install --set postgresql.image.tag=12 gitlab gitlab/gitlab`

**Describe the results you received:**

`postgresql` pod is failing and in `CrashLoopBackOff`. Error logs show "The POSTGRESQL_PASSWORD environment variable is empty or not set."

**Describe the results you expected:**

`postgresql` pod starts successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

This also happens with `postgresql.image.tag=11` since the tag `11` is continuously built and newer than the `11.7.0` tag.

**Comment by dani8art** [comment]
Hi @dustinmm80 thanks for reporting this issue.

I was researching it and I found this line https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh#L190 where we are doing like an "alias" for `POSTGRESQL_PASSWORD` so if we are using `POSGRES_PASSWORD` then we will fill it as well. 

I was also trying to reproduce the issue but I couldn't reproduce it

```bash
$ helm install pg-894 bitnami/postgresql --set image.tag=12 --version 8.9.4
```

```bash
k logs -f pg-894-postgresql-0 
postgresql 16:20:30.11 
postgresql 16:20:30.12 Welcome to the Bitnami postgresql container
postgresql 16:20:30.12 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 16:20:30.12 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 16:20:30.12 
postgresql 16:20:30.25 INFO  ==> ** Starting PostgreSQL setup **
postgresql 16:20:30.27 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 16:20:30.28 INFO  ==> Loading custom pre-init scripts...
postgresql 16:20:30.43 INFO  ==> Initializing PostgreSQL database...
postgresql 16:20:30.55 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 16:20:30.56 INFO  ==> Generating local authentication configuration
postgresql 16:20:33.40 INFO  ==> Starting PostgreSQL in background...
postgresql 16:20:33.54 INFO  ==> Changing password of postgres
postgresql 16:20:33.56 INFO  ==> Configuring replication parameters
postgresql 16:20:33.59 INFO  ==> Configuring fsync
postgresql 16:20:33.60 INFO  ==> Loading custom scripts...
postgresql 16:20:33.61 INFO  ==> Enabling remote connections
postgresql 16:20:33.62 INFO  ==> Stopping PostgreSQL...
postgresql 16:20:34.67 INFO  ==> ** PostgreSQL setup finished! **

postgresql 16:20:34.69 INFO  ==> ** Starting PostgreSQL **
2020-08-03 16:20:34.708 GMT [1] LOG:  starting PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-08-03 16:20:34.709 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-08-03 16:20:34.709 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-08-03 16:20:34.713 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-08-03 16:20:34.730 GMT [104] LOG:  database system was shut down at 2020-08-03 16:20:33 GMT
2020-08-03 16:20:34.739 GMT [1] LOG:  database system is ready to accept connections
```

**Comment by dustinmm80** [comment]
Thanks for looking into this @dani8art. The above Helm install works fine on my end as well.

We are setting `usePasswordFile` to `true` [in the GitLab chart](https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml#L636), so the password is loaded from a mounted secret and not the environment. 

These are the env vars and mounts for the `postgresql` pod stuck in `CrashLoopBackoff`:

```
│     Environment:                                                                                                                                                                                                 │
│       BITNAMI_DEBUG:                    false                                                                                                                                                                    │
│       POSTGRESQL_PORT_NUMBER:           5432                                                                                                                                                                     │
│       POSTGRESQL_VOLUME_DIR:            /bitnami/postgresql                                                                                                                                                      │
│       PGDATA:                           /bitnami/postgresql/data                                                                                                                                                 │
│       POSTGRES_POSTGRES_PASSWORD_FILE:  /opt/bitnami/postgresql/secrets/postgresql-postgres-password                                                                                                             │
│       POSTGRES_USER:                    gitlab                                                                                                                                                                   │
│       POSTGRES_PASSWORD_FILE:           /opt/bitnami/postgresql/secrets/postgresql-password                                                                                                                      │
│       POSTGRES_DB:                      gitlabhq_production                                                                                                                                                      │
│       POSTGRESQL_ENABLE_LDAP:           no                                                                                                                                                                       │
│     Mounts:                                                                                                                                                                                                      │
│       /bitnami/postgresql from data (rw)                                                                                                                                                                         │
│       /dev/shm from dshm (rw)                                                                                                                                                                                    │
│       /docker-entrypoint-initdb.d/ from custom-init-scripts (rw)                                                                                                                                                 │
│       /docker-entrypoint-preinitdb.d/init_revision.sh from custom-init-scripts (rw,path="init_revision.sh")                                                                                                      │
│       /opt/bitnami/postgresql/secrets/ from postgresql-password (rw)                                                                                                                                             │
│       /var/run/secrets/kubernetes.io/serviceaccount from default-token-96gd6 (ro)                                                                                                                                │
```

There are no `POSTGRESQL_PASSWORD` or `POSTGRES_PASSWORD` env variables on the pod, I was mistaken when I said that earlier.

The `postgresql-password` secret contains the `postgresql-password` and `postgresql-postgres-password` keys as expected.

I don't see any references to `POSTGRES_POSTGRES_PASSWORD_FILE` or `POSTGRES_PASSWORD_FILE` in https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/postgresql-env.sh. Could it be the case that these environment variables are not checked in the script?

**Comment by dani8art** [comment]
Hi @dustinmm80, yes this is the cases, I was able to reproduce it now

We would need to fix it, I think the best way would be using `POSTGRESQL_.*` always. There is a workaround https://github.com/bitnami/charts/issues/3331#issuecomment-670496619. Also, if you have a chance and would like to contribute, we are open to PRs and we will be very happy to handle it.

**Comment by javsalgar** [comment]
Closing this as it seems to be solved as explained here https://github.com/bitnami/bitnami-docker-postgresql/pull/239
