### ISSUE TITLE
Non-root image with root init container 

### ISSUE THREAD

**Issue by gardnerdev** [bitnami/bitnami-docker-postgresql#236]
**Description**

**Steps to reproduce the issue:**

1. Deploy postgres via helm chart
2. Wait for initalizing
3. Deployment fail because of security 

**Describe the results you received:**
```
Warning  FailedCreate  104s (x21 over 10m)  statefulset-controller  create Pod airflow-postgresql-0 in StatefulSet airflow-postgresql failed error: pods "airflow-postgresql-0" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden]
issue for the user
```

**Describe the results you expected:**
Working deployment without need to run any part of it as root

**Additional information you deem important (e.g. issue happens only occasionally):**

What is the point for providing 
```
volumePermissions.securityContext.runAsUser
```
for init container, if it can not run without UID=0 , which means root?

**Comment by carrodher** [comment]
Hi, I'm sorry but I don't fully understand the issue. Are you deploying postgresql chart or airflow chart? Can you paste here what `helm install ...` command are you using to deploy the chart?
