### ISSUE TITLE
Some questions regarding Bitnami PostgreSQL

### ISSUE THREAD

**Issue by mzwettler2** [bitnami/bitnami-docker-postgresql#240]
Question 1)
What is the exact difference between the (Bitnami) community path and the (VMWare Tanzu) enterprise path? Is it only the 24x7 enterprise class support?

Question 2)
Will Bitnami ever offer / integrate some kind of enterprise class backup solution for PostgreSQL like Barman or pgbackrest?

**Comment by dani8art** [comment]
Hi @mzwettler2 ,

We offer the same applications from Bitnami Community Catalog in our Tanzu Application Catalog (TAC) product, which allows customers to get the same trusted applications while gaining the ability to get them on their custom base image, apply security requirements, and get automated updates sent directly to your repo.

At this moment, we do not offer 24/7 support for BCC or TAC, and neither comes with application support. We rely on the ISVs to provide support directly for the applications. There is nothing on our roadmap right now to offer backup services for applications. 

Thanks!
