### ISSUE TITLE
[bitnami/postgresql] Liveness probe failed issue:postgresql 

### ISSUE THREAD

**Issue by sumit180591** [bitnami/bitnami-docker-postgresql#241]
I have deployed PostgreSQL pod on aks with StatefulSet and applied autoscaling(hpa) but I noticed that my pod crashed with following error:- 
Readiness probe failed: 127.0.0.1:9000 - rejecting connections
Liveness probe failed: 127.0.0.1:9000 - rejecting connections

While describing the pod I have found the error attached in screenshot
![error_postgresql](https://user-images.githubusercontent.com/65972884/90906094-c1b7ef00-e3ee-11ea-9b67-e42c4ad6863c.PNG)

HPA yaml is also attached
![postgresql-hpa](https://user-images.githubusercontent.com/65972884/90906432-4c005300-e3ef-11ea-9533-603f4391258c.PNG)

Here is the namespace detail 👍 
![NS DETAIL](https://user-images.githubusercontent.com/65972884/90907278-6555cf00-e3f0-11ea-937a-baeab9495452.PNG)

Replying soon will be highly apprecipated

Thanks,
Sumit

**Comment by andresbono** [comment]
Hi @sumit180591, thanks for opening this issue. Could you please share the values that you are using to deploy the chart? Can you tell us the version of the chart that you are using?

I understand that after you deploy the chart, then you create the HorizontalPodAutoscaler, right? Is the error appearing before or after creating the HPA?

In the second screenshot all the pods seem healthy and without restarts. Is it from a different deployment?
