### ISSUE TITLE
[Postgres 11 Cascading Replication]: Adding optional field "recovery_target_timeline" in recovery.conf

### ISSUE THREAD

**Issue by skyrain** [bitnami/bitnami-docker-postgresql#244]
**Description**
Currently, in recovery.conf file, we only have fixed field setup, and it does not covers field like 'recovery_target_timeline' which is very important for cascading replication.

Cascading replication asks for "recovery_target_timeline" to be set with value of 'latest' in 'recovery.conf' file as requirement as below:
https://www.postgresql.org/docs/11/warm-standby.html#CASCADING-REPLICATION
```
If an upstream standby server is promoted to become new master, downstream servers will continue to stream from the new master if recovery_target_timeline is set to 'latest'.
```

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

Have an environment variable to set up 'recovery_target_timeline' field.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by joancafom** [comment]
Hi @skyrain 

This container supports the use of a custom configuration file, so that you can tailor it to your needs 😁. Could you please take a look at [this section](https://github.com/bitnami/bitnami-docker-postgresql#configuration-file) and tell me if it works for you?

Thanks!

**Comment by skyrain** [comment]
> Hi @skyrain
> 
> This container supports the use of a custom configuration file, so that you can tailor it to your needs 😁. Could you please take a look at [this section](https://github.com/bitnami/bitnami-docker-postgresql#configuration-file) and tell me if it works for you?
> 
> Thanks!

Unfortunately, I do not think it works for me. The link you show me is for adding configuration files under `config` directory of postgres. However, `recovery.conf` is in `$PGDATA` directory, I need to be able to modify the `recovery.conf` in `$PGDATA`

**Comment by joancafom** [comment]
Hi @skyrain 

I might be wrong, but I recall that $PGDATA is the directory where configuration files for Postgres can be found (e.g. `pg_hba.conf`, `postgresql.conf` or `recovery.conf` in this case). You can mount any configuration file to the `/bitnami/postgresql/conf` folder and the container will copy them to the right location. For example:

```console
$ echo "Example!" > example.conf
$ cat docker-compose.yml
version: '2'

services:
  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    volumes:
      - './example.conf:/bitnami/postgresql/conf/example.conf'
   ...

$ docker-compose up
$ docker exec bitnami-docker-postgresql_postgresql_1 ls /opt/bitnami/postgresql/conf
conf.d
example.conf
pg_hba.conf
postgresql.conf
```

I think this might solve your issue 😄 Thanks!

**Comment by skyrain** [comment]
> conf

Hi @joancafom ,

Thanks for your information. I think that `recovery.conf` is a little bit special. As I checked the code, this file is created in hardcoded with env variables in `11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh` file's function

```
postgresql_configure_recovery() {
    info "Setting up streaming replication slave..."
    local -r psql_major_version="$(postgresql_get_major_version)"
    if (( psql_major_version >= 12 )); then
        postgresql_set_property "primary_conninfo" "host=${POSTGRESQL_MASTER_HOST} port=${POSTGRESQL_MASTER_PORT_NUMBER} user=${POSTGRESQL_REPLICATION_USER} password=${POSTGRESQL_REPLICATION_PASSWORD} application_name=${POSTGRESQL_CLUSTER_APP_NAME}" "$POSTGRESQL_CONF_FILE"
        postgresql_set_property "promote_trigger_file" "/tmp/postgresql.trigger.${POSTGRESQL_MASTER_PORT_NUMBER}" "$POSTGRESQL_CONF_FILE"
        touch "$POSTGRESQL_DATA_DIR"/standby.signal
    else
        cp -f "$POSTGRESQL_BASE_DIR/share/recovery.conf.sample" "$POSTGRESQL_RECOVERY_FILE"
        chmod 600 "$POSTGRESQL_RECOVERY_FILE"
        postgresql_set_property "standby_mode" "on" "$POSTGRESQL_RECOVERY_FILE"
        postgresql_set_property "primary_conninfo" "host=${POSTGRESQL_MASTER_HOST} port=${POSTGRESQL_MASTER_PORT_NUMBER} user=${POSTGRESQL_REPLICATION_USER} password=${POSTGRESQL_REPLICATION_PASSWORD} application_name=${POSTGRESQL_CLUSTER_APP_NAME}" "$POSTGRESQL_RECOVERY_FILE"
        postgresql_set_property "trigger_file" "/tmp/postgresql.trigger.${POSTGRESQL_MASTER_PORT_NUMBER}" "$POSTGRESQL_RECOVERY_FILE"
    fi
}

```

According to above code, it makes me think that adding new env variables to insert new entry in `recovery.conf` file might be the solution. Please let me know your idea.

**Comment by joancafom** [comment]
Hi @skyrain 

You are right this is a little bit special file, indeed, its correct location is in `/bitnami/postgresql/data/recovery.conf` not in the `conf` folder! Thanks for pointing that out.

Still I do think this can be carried out in other ways 😄 . Here are two that comes to my mind:

1. Replace the base `recovery.conf.sample` with a file that already has your custom values

     The code uses this file as a base, so by tailoring it to your needs before you will end up with your desired result:

    ```yaml
    services:
      postgresql:
        image: 'docker.io/bitnami/postgresql:11-debian-10'
        volumes:
          - './my_conf.conf:/opt/bitnami/postgresql/share/recovery.conf.sample'
   ```

2. This container also supports the execution of custom scripts at initialization. You can mount a custom script that changes these values. Checkout https://github.com/bitnami/bitnami-docker-postgresql#configuration 

I have tried option 1 and it seems to work.

```console
$ cat /bitnami/postgresql/data/recovery.conf | grep recovery_target_timeline
recovery_target_timeline = 'latest'
```

Could this work for you? This way, we can avoid adding an endless number of variables to map each of the configuration parameters in each file and preserve the main and more important ones.

Thanks!
