### ISSUE TITLE
Unable to get TLS working

### ISSUE THREAD

**Issue by guillaumelamirand** [bitnami/bitnami-docker-postgresql#247]
**Description**

Using image tag bitnami/postgresql:11.9.0, I am not able to enable TLS using env variables.
I did tried to override host owner or permission without success.
Bellow the output log from container :
```
postgresql 13:59:08.93 INFO  ==> ** Starting PostgreSQL setup **
postgresql 13:59:08.95 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 13:59:08.96 WARN  ==> A CA X.509 certificate was not provided. Client verification will not be performed in TLS connections
postgresql 13:59:08.99 INFO  ==> Loading custom pre-init scripts...
postgresql 13:59:09.01 INFO  ==> Loading user's custom files from /docker-entrypoint-preinitdb.d ...
postgresql 13:59:09.09 INFO  ==> Initializing PostgreSQL database...
postgresql 13:59:09.16 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 13:59:09.17 INFO  ==> Generating local authentication configuration
postgresql 13:59:13.17 INFO  ==> Starting PostgreSQL in background...
postgresql 13:59:13.35 INFO  ==> Changing password of postgres
postgresql 13:59:13.44 INFO  ==> Configuring replication parameters
postgresql 13:59:13.50 INFO  ==> Configuring fsync
postgresql 13:59:13.51 INFO  ==> Configuring TLS
postgresql 13:59:13.56 INFO  ==> Loading custom scripts...
postgresql 13:59:13.57 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 13:59:13.58 INFO  ==> Starting PostgreSQL in background...
CREATE DATABASE
CREATE ROLE
REVOKE
GRANT
REVOKE
GRANT
REVOKE
GRANT
ALTER DEFAULT PRIVILEGES
postgresql 13:59:14.03 INFO  ==> Enabling remote connections
postgresql 13:59:14.06 INFO  ==> Stopping PostgreSQL...
postgresql 13:59:15.07 INFO  ==> ** PostgreSQL setup finished! **

postgresql 13:59:15.09 INFO  ==> ** Starting PostgreSQL **
2020-09-15 13:59:15.131 GMT [1] FATAL:  private key file "/opt/bitnami/postgresql/certs/server.key" has group or world access
2020-09-15 13:59:15.131 GMT [1] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
2020-09-15 13:59:15.131 GMT [1] LOG:  database system is shut down
```

Thank you.

**Steps to reproduce the issue:**

1. Create a sample docker-compose
2. Set POSTGRESQL_ENABLE_TLS to yes
2. Set POSTGRESQL_TLS_CERT_FILE to /opt/bitnami/postgresql/certs/server.crt
2. Set POSTGRESQL_TLS_KEY_FILE to /opt/bitnami/postgresql/certs/server.key

**Describe the results you received:**

I got an error complaining about permission:
```
2020-09-15 13:59:15.131 GMT [1] FATAL:  private key file "/opt/bitnami/postgresql/certs/server.key" has group or world access
2020-09-15 13:59:15.131 GMT [1] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
2020-09-15 13:59:15.131 GMT [1] LOG:  database system is shut down

```
**Describe the results you expected:**

TLS should be working as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 6
  Paused: 0
  Stopped: 5
 Images: 874
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.78GiB
 Name: docker-desktop
 ID: JQC4:GF35:IF53:OKHG:XA6G:HUHF:AFKT:52AQ:BQ7Z:ZLUX:Y56E:NIYZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 90
  Goroutines: 94
  System Time: 2020-09-15T14:04:46.815044393Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.26.2, build unknown
docker-py version: 4.3.1
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):** Docker on WSL

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. The issue with PostgreSQL and TLS is that the certificate files need to have very strict permissions in order for the daemon to work.

```
2020-09-15 13:59:15.131 GMT [1] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
```

Could you change the permissions to 0600 using chmod before launching the docker-compose?

**Comment by guillaumelamirand** [comment]
Hi,

Thank you for your answer. 
Yes, I noticed the root cause however there is a piece of code in a script launched when the image boot which should do the job, see here:
https://github.com/bitnami/bitnami-docker-postgresql/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L390

Of course I have tried to set the right permission or even to force the owner to 1001 without success.

**Comment by javsalgar** [comment]
Hi,

What do you get when you enter the container? Which permissions does it have? Could it be because of the root filesystem that you are mounting/?

**Comment by guillaumelamirand** [comment]
The file has 666 as permissions and the owner is root whatever I set on my host.
I am mounting a folder as I always did, but I was thinking that it could be an issue with Docker on Windows.

**Comment by javsalgar** [comment]
Hi,

It looks to me that it could be an issue with the windows filesystem. I've tried multiple times mounting on Linux and Mac and never got these errors. Maybe it is something to report to the Docker for Windows team? Maybe, as a workaround, you could try creating an init script (mounting it in `/docker-entrypoint-init.d` that creates a self signed certificate inside the container or downloads your certificate from another location.

**Comment by guillaumelamirand** [comment]
Yes, I agree. I found this in there documentation : 

> Can I change permissions on shared volumes for container-specific deployment requirements?
No, at this point, Docker Desktop does not enable you to control (chmod) the Unix-style permissions on shared volumes for deployed containers, but rather sets permissions to a default value of 0777 (read, write, execute permissions for user and for group) which is not configurable.

As I have to shared the certificate with another container, It will be difficult to generate in from within the postgresql container.
But anyway thank you for your help.
