### ISSUE TITLE
Can't resest postgres password

### ISSUE THREAD

**Issue by sfxworks** [bitnami/bitnami-docker-postgresql#248]
**Description**
No way to reset the postgresql password?

**Describe the results you received:**
Instructions such as https://docs.bitnami.com/aws/infrastructure/postgresql/administration/change-reset-password/ show adjusting the pg_hba.conf file. Although `./opt/bitnami/postgresql/conf/pg_hba.conf` exists I can't reload. Since it isn't mounted changes won't persist. 

```
$ sed -ibak 's/^\([^#]*\)md5/\1trust/g' /opt/bitnami/postgresql/conf/pg_hba.conf
$ postgres pg_ctl reload
postgres: invalid argument: "pg_ctl"
Try "postgres --help" for more information.
```

**Describe the results you expected:**
Expect to be able to reset the password in the container or have the new env var defined reset it for me. 

```
bitnami/postgresql                      9.4.1           11.9.0          Chart for PostgreSQL, an object-relational data..
```

```
helm version --short
v3.2.4+g0ad800e

kubectl version --short
Client Version: v1.19.0
Server Version: v1.19.0
```

**Comment by javsalgar** [comment]
Hi,

Being able to redefine passwords in a declarative way is in our backlog. Right now, for the time being, you will need to enter the container, just as you were doing. Note that the command you used is for the cloud images, not the container, could you retry the command like this? 

```
pg_ctl reload
```

**Comment by sfxworks** [comment]
Hi there.
Thanks that appears to work.
I could possibly set up a quick PR that runs a pre-upgrade helm-hook to change the password. It would of off the assumption that it is the same password defined in a secret though.

**Comment by javsalgar** [comment]
Hi,

We would need to discuss the proper way. I believe that it should be in the container itself rather than creating a helm hook. However, now with the `extraDeploy` section in the chart you could deploy any yaml you would like so, in the meantime, you could add the job to your deployments.
