### ISSUE TITLE
PostgreSQL 13

### ISSUE THREAD

**Issue by Konard** [bitnami/bitnami-docker-postgresql#251]
When the latest stable version will be available?

**Comment by miguelaeh** [comment]
Hi @Konard ,
We are currently working on it. Nevertheless, we cannot provide an estimated date to have it ready.
We will update this thread once we have news.
Regards.

**Comment by Mauraza** [comment]
Hi @Konard, 

We've just released the lasted stable version.
Closing this out now, feel free to open another issue if you have any other questions

Regards.
