### ISSUE TITLE
Support major languages

### ISSUE THREAD

**Issue by enote-kane** [bitnami/bitnami-docker-postgresql#252]
**Description**

Please support major procedural languages that are [documented officially upstream](https://www.postgresql.org/docs/current/server-programming.html), namely:

* PL/Tcl
* PL/Perl
* PL/Python (python3u should be enough since Python 2 is EOL'd)

**Steps to reproduce the issue:**

1. Login into a database of choice running in a container
2. Execute the following:
```sql
CREATE LANGUAGE plpython3u;
CREATE LANGUAGE plperl;
CREATE LANGUAGE pltcl;
```

**Describe the results you received:**

```
2020-10-05 13:05:32.583 GMT [113] ERROR:  could not access file "$libdir/plpython3": No such file or directory
2020-10-05 13:05:32.583 GMT [113] STATEMENT:  CREATE LANGUAGE plpython3u;
2020-10-05 13:05:37.600 GMT [113] ERROR:  could not access file "$libdir/plperl": No such file or directory
2020-10-05 13:05:37.600 GMT [113] STATEMENT:  CREATE LANGUAGE plperl;
2020-10-05 13:05:41.548 GMT [113] ERROR:  could not access file "$libdir/pltcl": No such file or directory
2020-10-05 13:05:41.548 GMT [113] STATEMENT:  CREATE LANGUAGE pltcl;
```

**Describe the results you expected:**

Languages can be loaded.

**Additional information you deem important (e.g. issue happens only occasionally):**

As a workaround, I am currently doing this hack (which might break for some functions, since the Bitnami PostgreSQL is not equal to the official Debian version from PGDG and not APT-installed either):

```dockerfile
FROM postgres:12.4 AS extensions

RUN \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends postgresql-plpython3-12

FROM bitnami/postgresql-repmgr:12.4.0-debian-10-r55

USER 0

RUN \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends python3 libpython3.7 && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives

COPY --from=extensions /usr/share/postgresql/12/extension/*plpython3u* /opt/bitnami/postgresql/share/extension/
COPY --from=extensions /usr/lib/postgresql/12/lib/*plpython3* /opt/bitnami/postgresql/lib/

USER 1001
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 250
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.5.0-kane
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31GiB
 Name: kane
 ID: DBZY:4WFE:K34X:KYWC:AWWY:LMW3:J6S4:QSJQ:TT7V:PFZC:4FX2:LS7U
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback! I will open a task for evaluation. We try to be conservative about the extensions we add in order to not increase too much the image size. As soon as we have more news, I will update this ticket.

**Comment by enote-kane** [comment]
@javsalgar Thanx for the early feedback. I am personally only interested in Python, but the main point for opening this ticket here is that I couldn't find any docs about how to "properly" add extensions. If there would be information about how you compile and package the PostgreSQL itself on your side (because it is getting just downloaded, not package-installed), it would make it easier to apply the same for extensions.

Extensions for specific purposes are a major use-case for choosing PostgreSQL over alternatives in the first place.

**Comment by javsalgar** [comment]
Hi,

This is something we'd like to work on, as extending PostgreSQL with extensions is a common use case. I will forward this to the rest of the engineering team for discussion.

**Comment by Hubbitus** [comment]
Sorry, do you plan to bring such languages into the image?

**Comment by javsalgar** [comment]
Hi,

For the time being, we don't have plans to extend the size of the image adding more language support. Our recommendation for now would be to fork the image and add the language runtimes you require.

**Comment by enote-kane** [comment]
@javsalgar The major issue here is that we don't know how you are building the "components" and in which environment you're doing that. So whenever someone needs to add an extension, it's a pure gamble of whether that will actually work.

I'd like to see a script for how the PostgreSQL component is being compiled, so that the community at least knows how to properly create an environment to add other extensions.

**Comment by javsalgar** [comment]
Hi,

If I remember correctly, we did something similar in nginx. I think it makes sense to add a guide on how to build extensions in PostgreSQL. I will forward this to the engineering team. To give you an idea of how you would compile an extension, I think that in most cases what you need is an existing PostgreSQL installation and the build-essential tools. In this sense, you could use the PostgreSQL twice in a multi-stage container build pipeline. In the first PostgreSQL container you would install the compilation tools and do the compilation of the plugin, and then in the new container you would just copy the plugin files from the previous container.

**Comment by enote-kane** [comment]
Yes, using a multi-stage build sounds like a starting point. I also saw that the component includes the headers, but to compile extensions which are part of the PostgreSQL official code base, we'd need the exact source code which was used to create the component. If you are using the official code base from the Git tag (e.g. [13.2](https://git.postgresql.org/gitweb/?p=postgresql.git;a=shortlog;h=refs/tags/REL_13_2) for component version `13.2.0-8`) without any modifications, we'd just need the configure options you have used to get started.

**Comment by javsalgar** [comment]
Thanks for the information. I will forward this to the documentation team.

**Comment by remcoboerma** [comment]
While searching i found this thread, as well as  https://github.com/haohello/bitnami-postgresql-extensions. Hope it helps

**Comment by rafariossaa** [comment]
Thanks for the reference.  I will forward this to the documentation team.

**Comment by enote-kane** [comment]
@remcoboerma @rafariossaa While that approach should work most of the time, it doesn't necessarily work when the configuration for how PostgreSQL itself was built doesn't match. Therefore, what we at least need to be able to download is the build configuration and exact commit hash it was built from by Bitnami.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
