### ISSUE TITLE
pg_isready should include postgres port

### ISSUE THREAD

**Issue by Jacq** [bitnami/bitnami-docker-postgresql#259]
The active wait for postgres ready in: https://github.com/bitnami/bitnami-docker-postgresql/blob/479be56ee80c97863174225b45bdf3b91cc5e439/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L801
, should include the port parameter "-p POSTGRESQL_PORT_NUMBER", otherwise if POSTGRESQL_PORT_NUMBER is changed pg_isready never notifies the postgres as ready and the container stops.

Jacq
Cheers

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback. We will work on fixing it. If you want to speed up the process, feel free to contribute with a PR.

I'm also curious, could you explain your use case that requires changing the default port inside the container? I'm interested in the different ways the container is used :D

**Comment by Jacq** [comment]
Hi
We use in the past some docker images for DB in docker swarm and kubernetes. Either docker-compose configurations (post-dock), manual stand alone docker-compose in different hosts, helm charts and looked also to operators but did not try them yet.

We experience some issues with the manage of dynamic loads, the extra complexity for setup and debug did not help either specifically for some colleagues that are not so much into kubernetes.  The overall load of the DB (usually attached to the node) did not ease the management as we had worker nodes (mostly disposables with network volumen mounts) and DB workers which needed special care (as they usually had the DB files on the local host).

So we move to other more traditional solutions with more static isolated DB nodes. To simplify these deployment as much as possible while having the benefits of docker, we find that using a VM as a DB node (with the setup and configuration via docker containers not binary packages) is for us the sweet spot in the middle between having to install al packages manually (and upgrade them manually or with ansible or similar tools) versus having everything dynamic (swarm/kubernetes playing with resource limitations, node affinity, local volumes...), this without too much complexity and less moving parts that can give issues.

So following this approach, we have several VMs, each one with one postgres DB installed using a container with the minimum complexity (one static docker-compose per host with network mode host and only one local data volume). We plan to run in the same host a proxy for the queries, similar than proxysql for mariadb-galera, but for postgres probably pgpool-2. To do this and perform a quick migration of already setup connections while encorage for the future to use the pgpool instead of the postgres service, we are planning to configue pgpool in the standard postgres 5432 port and move the postgres container to other port. In the latter is where we hit the bug, as with network_mode host we do not have any kind of NAT possible.

I hope this bring some light into our use case, any comments are very welcome as we are continuing evaluating other options for simplify the DB management while ensure its continuous operation and in the worst case ease the recovery in case of failure.

Cheers,
Jacq

**Comment by javsalgar** [comment]
Hi,

Thanks for the information! I'm working on adding the fix, I will ping you when it is ready

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that a new revision of the container is available, this should fix the issue you reported.

https://github.com/bitnami/bitnami-docker-postgresql/commit/1dcefb228fb4ece83daa76c042a5d096c13352c2

Please let us know if you find any other issue.
