### ISSUE TITLE
Invalid authentication method "ldap": not supported by this build

### ISSUE THREAD

**Issue by aogb** [bitnami/bitnami-docker-postgresql#264]
**Description**

We did install postgresql using a Source build
Below is the link where the postgresql was downloaded.
https://www.postgresql.org/ftp/source/v12.2/postgresql-12.2.tar.gz
Now we are trying to integrate with LDAP and facing the error "Invalid authentication method "ldap": not supported by this build"

**Steps to reproduce the issue:**

Modify pg_hba.conf and include the ldap configuration details
Restart Postgresql 
Postgresql refuses to come on and throw error Invalid authentication method "ldap": not supported by this build"

**Describe the results you received:**

**Describe the results you expected:**

Postgres should start normally and i should be able to connect with my LDAP 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  That message indicates that you need to enable LDAP when building postgresql. 
  Could you check the building parameters ?.

**Comment by aogb** [comment]
Please how do I go about this? Could you please guide?
I have only use
./configure --prefix=/LDM/postgres/
gmake
gmake install

**Comment by aogb** [comment]
Compilations gives these errors:

conftest.c:17:28: fatal error: ac_nonexistent.h: No such file or directory
conftest.c:17:28: fatal error: ac_nonexistent.h: No such file or directory
conftest.c:67:17: fatal error: dld.h: No such file or directory
conftest.c:34:17: fatal error: dld.h: No such file or directory
conftest.c:67:22: fatal error: fp_class.h: No such file or directory
conftest.c:34:22: fatal error: fp_class.h: No such file or directory
conftest.c:68:20: fatal error: ieeefp.h: No such file or directory
conftest.c:35:20: fatal error: ieeefp.h: No such file or directory
conftest.c:75:23: fatal error: sys/pstat.h: No such file or directory
conftest.c:42:23: fatal error: sys/pstat.h: No such file or directory
conftest.c:80:24: fatal error: sys/sockio.h: No such file or directory
conftest.c:47:24: fatal error: sys/sockio.h: No such file or directory
conftest.c:80:21: fatal error: sys/tas.h: No such file or directory
conftest.c:47:21: fatal error: sys/tas.h: No such file or directory
conftest.c:83:19: fatal error: ucred.h: No such file or directory
conftest.c:50:19: fatal error: ucred.h: No such file or directory
conftest.c:90:23: fatal error: sys/ucred.h: No such file or directory
conftest.c:111:29: fatal error: machine/vmparam.h: No such file or directory

**Comment by marcosbc** [comment]
Hi @aogb, it seems you are finding issues compiling PostgreSQL, which is independent from the Bitnami PostgreSQL Docker image. I'm afraid we will not be able to be of much help for your case. Also, your issue seems to be related to compiling in a non-standard architecture or distro. 

If you were to use the `bitnami/postgresql` Docker image, LDAP would already be enabled by default meaning no need to compile.
