### ISSUE TITLE
ear

### ISSUE THREAD

**Issue by denysobukh** [bitnami/bitnami-docker-postgresql#265]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi, since this issue looks like it was created by mistake, I'm going to close it. Feel free to create a new one if you were actually going to report anything.
