### ISSUE TITLE
Is there a way can let us install postgresql-repmgr and pg_es_fdw together?

### ISSUE THREAD

**Issue by thomas-reinhold-de** [bitnami/bitnami-docker-postgresql#266]
I tried many ways. It seems like there is no capable for installing postgresql-12-python3-multicorn. Since, the basic docker image cannot find it. And, I found there is impossible to add deb repository for some special packages. Is this problem can be solved? Or there is another way the problem can be solved?

**Comment by marcosbc** [comment]
Hi @thomas-reinhold-de, maybe you are looking for this? https://github.com/bitnami/bitnami-docker-postgresql-repmgr

As for multicorn, it is not included with bitnami/postgresql but you could always build it on your side following these instructions: https://github.com/bitnami/bitnami-docker-postgresql/issues/249#issuecomment-699037416
