### ISSUE TITLE
Question on comment in documentation regarding limiting reads from read only replicas

### ISSUE THREAD

**Issue by skuirrels** [bitnami/bitnami-docker-postgresql#269]
Hi, the docs state _"In a replication cluster you can have one master and zero or more slaves. When replication is enabled the master node is in read-write mode, while the slaves are in read-only mode. For best performance its advisable to limit the reads to the slaves."_

Is this referring to synchronous replies only?   I would have thought it standard to use an async replica for heavy reads to take a load off the master, but maybe I am missing something in this context?

**Comment by miguelaeh** [comment]
Hi @skuirrels ,
That means to avoid reads from the master, since it is the only one that is able to write, use it only for write purpose and send all the read requests to the slaves.

**Comment by skuirrels** [comment]
Hi @miguelaeh 
Ok thanks.  Do you think the docs should be updated as it says "limit the reads to the slaves"

**Comment by miguelaeh** [comment]
Hi @skuirrels ,
What do you suggest?
