### ISSUE TITLE
Does the postgresql image contains cryptominer?----My cloud provider informed me.

### ISSUE THREAD

**Issue by lushtech** [bitnami/bitnami-docker-postgresql#272]
**Description**
Alibaba the cloud provider  informed me.

remarks
Malicious process (cloud killing) - accessing malicious IP to be processed

The alarm is detected by  some engines:

Central control IP: 136.243.90.99

Central control port: 8080

Process path: bitnami / PostgreSQL / data / 5054f6add68e8d059df4ddaef001e801 (deleted)

Command line parameters: 1onzihqs

Event description: the detection model found that the process on your server is trying to access a suspicious malicious IP, which may be the hacker's central control IP, mine pool IP and other high-risk IP, and the process initiating the connection behavior may be the malicious file implanted by the hacker.

  

**Steps to reproduce the issue:**

1. [First Step]
I have two ECS(like Amazon ECS) which provided by Alibaba, running the odoo with postgresql.The images version:
* bitnami/odoo:13.0.20201210
* bitnami/postgresql:11.10.0-debian-10-r24 
The same thing happened on two ECS
 
2. [Second Step]
  Anybody Has anyone been in this situation？
3. [and so on...]

**Comment by beltran-rubo** [comment]
Hi @lushtech 

We do not have any evidence a malicious tool was included into any of the Bitnami container image. Part of our process is to pass CVE and Antivirus scans before publishing any new image. You can download the same container image & tag and scan it on your own.

Could you please check the deployment configuration in your "ECS" was secure enough? E.g. PostgreSQL credentials were properly configured, the port is not publicly available, the firewall configuration was properly done.

**Comment by lushtech** [comment]
@beltran-rubo 
Thank you for your reply.
I tested  it on the third ECS that was only running Odoo and PostgrSQL container which were base on  the images version mentioned above，and  nothing was happened. 
So it is not because of bitnami images, it is another cause.

**Comment by beltran-rubo** [comment]
Thanks @lushtech, if you get more insights it would be great to post them here what happened. We will evaluate if there is anything in our docs or guidelines to reinforce about deploying the Container Images in a secure way.
