### ISSUE TITLE
Bitnami Postgres Pgbackrest retsore

### ISSUE THREAD

**Issue by anees-muhammed** [bitnami/bitnami-docker-postgresql#273]
Hello,

I am using the Bitnami PostgreSQL docker image. I using PG-Backrest backup option to page backups. But during restore, I found an error. The PostgreSQL service needs to be stopped to perform a pgbackrest restore. But the Postgres service running as a container with PID 1 the container needs to stop to restore the backup. 

![image](https://user-images.githubusercontent.com/78351586/106445949-abd24e00-64a5-11eb-8c11-d8efc8e20772.png)

Since we need to execute the restore command inside the container so the PostgreSQL container can't be stopped. I also tried restoring by stopping the PostgreSQL container and spin up a new container using the below command

docker run --rm -v postgresql_data:/bitnami/postgresql -v pgbackrest_data:/bitnami/postgresql/pgbackrest -v /opt/docker-compose/postgresql/postgres-conf.d:/opt/bitnami/postgresql/conf/conf.d  bitnami/postgresql:12.4.0_pgbackrest pgbackrest --stanza=BACKUP  restore

The restore command got the successful output
![image](https://user-images.githubusercontent.com/78351586/106446166-e9cf7200-64a5-11eb-9292-4fd58c7205f4.png)

But the PostgreSQL container is not starting after the restore

![image](https://user-images.githubusercontent.com/78351586/106446271-0f5c7b80-64a6-11eb-9703-5bea89c7dc67.png)

Please help.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I'm trying to reproduce the issue. Did you perform the initial backup using pgbackrest as well? Which command did you execute?

**Comment by anees-muhammed** [comment]
Hei,

**Comment by anees-muhammed** [comment]
> Hi,
> 
> Thank you for using Bitnami. I'm trying to reproduce the issue. Did you perform the initial backup using pgbackrest as well? Which command did you execute?

I used the below command to take backup

`docker exec -it -u postgres postgresql pgbackrest --stanza=BACKUP  backup`

**Comment by javsalgar** [comment]
Hi,

I tried using this command and got this

```
❯ docker exec -it 3295 pgbackrest --stanza=BACKUP backup
ERROR: [037]: backup command requires option: pg1-path
       HINT: does this stanza exist?
```

Is there anything that I'm missing?

**Comment by anees-muhammed** [comment]
> Hi,
> 
> I tried using this command and got this
> 
> ```
> ❯ docker exec -it 3295 pgbackrest --stanza=BACKUP backup
> ERROR: [037]: backup command requires option: pg1-path
>        HINT: does this stanza exist?
> ```
> 
> Is there anything that I'm missing?

You have to create a stanza before taking the backup.

docker exec -it -u root 3295  chown postgres:postgres -R /bitnami/postgresql/pgbackrest

docker exec -it -u postgres 3295 pgbackrest --stanza=BACKUP --pg1-path=/bitnami/postgresql/data stanza-create

**Comment by javsalgar** [comment]
Hi,

I tried again, and the stanza create command worked, but  saw this error now when running the backup command. 

```
ERROR: [087]: archive_mode must be enabled
```

Are you sure there's no other setting I need to enable?
