### ISSUE TITLE
Possibility of having a multi master replication

### ISSUE THREAD

**Issue by Thangamh** [bitnami/bitnami-docker-postgresql#274]
Can we deploy a multi master replication from this?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but that configuration is not currently supported by our initialization scripts. Maybe you can use this as a base and build your own image to add that feature. Also, we have this other image [postgresql-repmgr](https://github.com/bitnami/bitnami-docker-postgresql-repmgr) but I don't know if it will be suitable for your needs.

**Comment by Thangamh** [comment]
Hi, 
postgresql-repmgr is a great option, But how can I build a production style environment?

example: 
have 1 primary node and 3 standby nodes
All are different vms
How can I deploy this without using a docker network?
REPMGR_NODE_NETWORK_NAME this env shouldnt be there since we should be connecting through ips, isnt that right?

**Comment by rafariossaa** [comment]
Hi,
  Maybe you cloud take a look to the [docker-compose.yml of the pgpool container](https://github.com/bitnami/bitnami-docker-pgpool/blob/master/docker-compose.yml) and evaluate if that is what you need.
