### ISSUE TITLE
Cannot use empty password for replication function

### ISSUE THREAD

**Issue by DingDino** [bitnami/bitnami-docker-postgresql#276]
**Description**
I'm running with the suggested way to enable replication function. 
So that I can use the 'pg_basebackup'
I followed the guide to run the container 
https://github.com/bitnami/bitnami-docker-postgresql
![image](https://user-images.githubusercontent.com/44087574/111023142-46616d80-8412-11eb-9519-c6974fecc691.png)

Only re-tagged the image, using the bitnami:postgresql:11.5.0. 
But as you see I have added the empty password flag. 
Shows a warning first which makes sense, t**hen reports the error. and failed to start the container.**
![image](https://user-images.githubusercontent.com/44087574/111023119-2467eb00-8412-11eb-8a1f-7fe7f1c09a54.png)

Checked the code, it's like never will pass the empty passed case.
https://github.com/bitnami/bitnami-docker-postgresql/blob/781298a265879f2e8ef7786ac032bd47752c8012/11/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L94-L97

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @DingDino 

This is expected, the password for replication is mandatory even if you use `ALLOW_EMPTY_PASSWORD=yes`.

That environment variable only allows you setting an empty value for the "root" password (see `POSTGRESQL_POSTGRES_PASSWORD`) and the password custom user you choose (see `POSTGRESQL_USERNAME` and `POSTGRESQL_PASSWORD`).
