### ISSUE TITLE
FEATURE REQUEST : Add rescue mode to image

### ISSUE THREAD

**Issue by scoopex** [bitnami/bitnami-docker-postgresql#280]
Dealing with problematic situations of a postgresql database can be very time consuming and of sophisticated difficulties because there is a lot of logic which performs the startup/the launch of the postgresql service. Typical rescue operations which are performed on virtual machines/physical machines can currently only be only used in a very complicated way.

In problematic situations i would be great to have the following possibilities:

- the possibility to launch the image (and its storage volume) without starting the database itself
- to inspect/change the database files (i.e. i you want to restore a base backup)
- to use/inspect the environment and the start parameters of the database instance
- to add additional launch parameters for the executable for problem solution
- to start/stop debug the database

It would be great to have a feature toggle which enables the rescue mode in the following way:
- launch the image with the normal entrypoint/run infrastructure and output the final start parameters to STDOUT instead of really starting the database (alternatively create a simple start script which can be accessed, inspected or used by operations)
- launch `/bin/sleep infinty` and wait for someone entering the container by "exec"
- add documentation to the image which provides a good advise how to perform rescue, analysis and recovery operations
- add documentation and support to the bitnami postgres chart (i.e. disable health/readiness checks if debug mode is activated)

**Comment by rafariossaa** [comment]
Hi @scoopex ,
  Thanks for suggesting all these ideas.
  I would like to know a little bit more about the scenarios you found and how did you proceed or needed to proceed. That would give us a better understanding of the situations and procedures and perhaps something more can be included in the container logic.

**Comment by scoopex** [comment]
Many thanks for your fast response, i think it is is not really necessary to add specific support for error/maintenance scenarios for exceptional situations because there are so various situations where this feature might be very useful.  

From a operator view it would be very useful to have the option to decouple the lifecycle of the container and the execution of the postgresql instance temporarily for emergency or engineering situations.

Situation where I would have been very happy about this feature.

- Start PostgreSQL in single user modus (https://www.postgresql.org/docs/13/app-postgres.html, `--single`) to repair a crashed "pg_statistic" table. "pg_statistics" only can be recreated in singe user mode
- Execute "pg_resetwal" before starting the database after a a major AKS outage with unclean  unmount of the database volume
- Perform optimizations of the database configuration in a emergency situation (high time pressure, where you can't want to wait for ci/cd and pvc attach/mount of large for pvs on every optimization iteration)
- Manual restore of a base backup (https://www.postgresql.org/docs/10/continuous-archiving.html#BACKUP-PITR-RECOVERY)
- Optimize the settings of the database while developing a system

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for describing the scenarios. It is very interesting to have this kind of requests.
  I am creating an internal task to study this and see what can be done to improve the usability in those scenarios.
  I am sorry, but right now, I can not provide an ETA or what would be done.

Regards,

**Comment by InteNs** [comment]
hi @scoopex 

we needed similar funtionality so in our swarm we actually have 2 services for postgres

- a postgres_pg_server running the default command
- a postgres_pg_tasks service running `sleep infinity`

these services share the postgres_data, docker preinit and docker init directories.

we have a custom image extending bitnami-docker-postgresql that includes some scripts like `maintenance_mode` `recovery_mode` etc.

these scripts can `cp` and `rm` conf files to the shared directories and restarting the postgres server instance can take those config files into effect.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for sharing.
  Also I would like to indicate that we added `diagnosticMode.enabled` in [our chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql). That would start a pod and mount the volumes but without starting the services. That should help in those situations.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
