### ISSUE TITLE
Restore database 

### ISSUE THREAD

**Issue by vhico07** [bitnami/bitnami-docker-postgresql#281]
Wondering how to restore database specify with params password. I already try with 
`cat dump.sql | docker exec -i <container-name> psql -U <db-user> -d <database-name>`

Got an error :

Password for user <db-user>: 
psql: error: FATAL:  password authentication failed for user "<db-user>"

Does anyone know params for entering password on restore database command?
Tested with 

`cat dump.sql | docker exec -e PGPASSWORD=<password> <container-name> psql -U <db-user> -d <database-name>`

Still not working. 

Thank you

**Comment by alemorcuq** [comment]
Hi, @vhico07.

Have you tried mounting your `.sql` file to `/docker-entrypoint-initdb.d`? When the container is started for the first time it will execute the files in that directory. See: https://github.com/bitnami/bitnami-docker-postgresql#initializing-a-new-instance

**Comment by vhico07** [comment]
> Hi, @vhico07.
> 
> Have you tried mounting your `.sql` file to `/docker-entrypoint-initdb.d`? When the container is started for the first time it will execute the files in that directory. See: https://github.com/bitnami/bitnami-docker-postgresql#initializing-a-new-instance

Not yet, but i already figure it out, by changing pg_hba.conf in `/opt/bitnami/postgresql/conf` from
```
host     all             all             0.0.0.0/0               md5
host     all             all             ::/0                    md5
local    all             all                                     md5
host     all             all        127.0.0.1/32                 md5
host     all             all        ::1/128                      md5
```
to 
```
host     all             all             0.0.0.0/0               trusted
host     all             all             ::/0                    trusted
local    all             all                                     trusted
host     all             all        127.0.0.1/32                 trusted
host     all             all        ::1/128                      trusted
```

But, Thanks for advice.
