### ISSUE TITLE
Will there be a docker image that supports Apple silicon in the future?

### ISSUE THREAD

**Issue by chengshiwen** [bitnami/bitnami-docker-postgresql#286]
Will there be a docker image that supports Apple silicon in the future?

**Comment by alvneiayu** [comment]
hi @chengshiwen 

Yes, it is in our roadmap to release ARM images in our catalog, but I can not give you an ETA on when they will be available.

At the moment only our base image [bitnami/minideb](https://hub.docker.com/r/bitnami/minideb) has support for ARM.

Sorry again and thanks

Álvaro

**Comment by chengshiwen** [comment]
Thx!
