### ISSUE TITLE
PostGIS installation missing address_standardizer

### ISSUE THREAD

**Issue by logicbomb421** [bitnami/bitnami-docker-postgresql#287]
**Description**

I am trying to utilize the `address_standardizer` extension, which is a [part of the PostGIS extension](https://postgis.net/docs/postgis_installation.html#installing_pagc_address_standardizer) in PostGIS 2.2+, but am unable to create the extension.

**Steps to reproduce the issue:**

1. Create a docker container from a Bitnami PostgreSQL image (I've tested 9.6 and 13)
2. Connect to the database running at this container
3. Attempt to install the `address_standardizer` extension with `create extension address_standardizer;`

**Describe the results you received:**

This will result in the following error:

```
ERROR:  could not open extension control file "/opt/bitnami/postgresql/share/extension/address_standardizer.control": No such file or directory
```

**Describe the results you expected:**

The extension is successfully created.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have played around with manually installing this in a custom image based off the Bitnami images and can get it sort of half-way there by installing from a [different source](https://trac.osgeo.org/postgis/wiki/UsersWikiPostGIS24UbuntuPGSQL10Apt), however this doesn't seem to jive with the Bitnami instance since it lives in a different location.

Is there a way to go about adding this to a Bitnami PostgreSQL image?

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: MKLM:FZLP:TH5N:LWP7:EW67:TF66:GNWN:RNVN:CFRB:BJB4:DUS7:LBAU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable): N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):** N/A

**Comment by marcosbc** [comment]
Hi @logicbomb421, we are not currently building PostgreSQL with the `--with-pcredir` option. Let me look into this and see if this is feasible.

**Comment by marcosbc** [comment]
Hi, just wanted to let you know that we have been able to include the module in the PostgreSQL container and are working on getting the images released. We expect the releases to happen in the next 2-3 days.

**Comment by logicbomb421** [comment]
@marcosbc thank you very much, we'll be on the lookout!

**Comment by marcosbc** [comment]
Hi, we recently released revisions of the PostgreSQL container images that support this extension:

```
postgres=# create extension address_standardizer;
CREATE EXTENSION
```

Therefore I'm proceeding to close this issue
