### ISSUE TITLE
"latest" tag should point to the highest version only.

### ISSUE THREAD

**Issue by ravshansbox** [bitnami/bitnami-docker-postgresql#288]
`latest` tag should point to the highest version only.

**Steps to reproduce the issue:**

1. Compare hash of "latest" branch with its versioned tag
2. Ensure the versioned tag is the highest version

**Describe the results you received:**

Sometimes "latest" gives "11.x" tags hash, sometimes "12.x" or "13.x"

**Describe the results you expected:**

Always match to highest versions hash

**Comment by miguelaeh** [comment]
Hi @ravshansbox ,
I have checked it and ti seems we are publishing as latest `11.x` only, could you provide an example where this happened?

**Comment by ravshansbox** [comment]
Hi @miguelaeh, interesting, why latest points to `11.x` when there is `13` version of postgresql?

**Comment by ravshansbox** [comment]
Sorry, I was wrong when said that latest sometimes points to `12.x` or `13.x`. When I used it the first time, I was sure (no idea how) it's pointing to latest postgres version and after some updates I see it points to `11.x`.

**Comment by miguelaeh** [comment]
Maybe we should point it to version `13` but I talked about this with other members of the team and it would need some more internal changes than I thought.
We will probably do it once all the applications we have support version `13`.
Sorry for the inconveniences
