### ISSUE TITLE
Wrong owner for public schema in custom database with custom user

### ISSUE THREAD

**Issue by Sebor** [bitnami/bitnami-docker-postgresql#289]
**Description**

When I create custom database with custom user during initialization the owner of `public` schema in this DB is `postgres` instead of my user

**Steps to reproduce the issue:**

1. Create container
  ```bash
  docker run -d --name postgres -e POSTGRESQL_DATABASE=app -e POSTGRESQL_USERNAME=app -e POSTGRESQL_PASSWORD=password123 bitnami/postgresql:latest
  ```
2. Login to container
  ```
  docker exec -it postgres bash
  ```
3. Login to database
  ```
  psql -U app
  ```
4. Connect to `app` database
  ```
  \c app
  ```
5. List schemas
  ```
  \dn
  ```

**Describe the results you received:**

```
List of schemas
  Name  | Owner
--------+-------
 public | postgres
(1 row)
```

**Describe the results you expected:**

```
List of schemas
  Name  | Owner
--------+-------
 public | app
(1 row)
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The official postgres image does not have this behavior

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. Just to confirm, that means we should add something like this to the database creation. 

```
ALTER SCHEMA public OWNER TO app
```

Is that correct?

**Comment by Sebor** [comment]
> Hi,
> 
> Thanks for reporting. Just to confirm, that means we should add something like this to the database creation.
> 
> ```
> ALTER SCHEMA public OWNER TO app
> ```
> 
> Is that correct?

Hi @javsalgar!
Yes, I think it will be enough

**Comment by juan131** [comment]
Hi @Sebor 

The custom database you indicate using the `POSTGRESQL_DATABASE ` env. var is created using the function `postgresql_create_custom_database ` that you can find below:

- https://github.com/bitnami/bitnami-docker-postgresql/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L480

Then, the custom user you indicate in the `POSTGRESQL_USERNAME` env. var is created using the function `postgresql_create_admin_user` that you can find below:

- https://github.com/bitnami/bitnami-docker-postgresql/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L459

As you can see, we're granting privileges `GRANT ALL PRIVILEGES ON DATABASE ...` but it's true we're not altering the schema owner. That said, I think it makes sense what you are proposing.

Would you like to submit a PR adding this feature to our current logic?

**Comment by juan131** [comment]
Great @Sebor !! I just took a look to your changes
