### ISSUE TITLE
Allow setting wal_level

### ISSUE THREAD

**Issue by flokli** [bitnami/bitnami-docker-postgresql#292]
**Description**

I'd like to have another application connect to postgresql, with the replication user.

That application wants me to set `wal_level` to `logical`. Right now, it's [hardcoded to `hot_standby`](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L370), which is depreated and mapped to replica (see https://www.postgresql.org/docs/9.6/runtime-config-wal.html#GUC-WAL-LEVEL)

Possibly related: https://github.com/bitnami/charts/issues/6830

**Comment by Mauraza** [comment]
Hi @flokli,

Thanks for the contribution! We are going to review the PR!

**Comment by flokli** [comment]
This has been implemented, see https://github.com/bitnami/bitnami-docker-postgresql/pull/293#issuecomment-881256688.
