### ISSUE TITLE
Add EXTRA_LOCALES to the docs.

### ISSUE THREAD

**Issue by pjsofts** [bitnami/bitnami-docker-postgresql#294]
It is missing the ARG section for the EXTRA_LOCALES variable.
https://github.com/bitnami/charts/issues/6841

**Comment by Mauraza** [comment]
Hi @pjsofts,

sorry for the delay. We have an internal task to fix it.

**Comment by vahidf91** [comment]
Any update? Same issue here.

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. As soon as we have more news, we will update this ticket.

**Comment by alemorcuq** [comment]
We have added a new section in the README on [installing extra locales](https://github.com/bitnami/bitnami-docker-postgresql#installing-extra-locales).
