### ISSUE TITLE
Unable to touch recovery.signal and run recovery

### ISSUE THREAD

**Issue by timson** [bitnami/bitnami-docker-postgresql#298]
Hi! I am trying to recover database with wal-g tool. I am successfully able to fetch backup, rollout it to PGDATA folder, and to run recovery I should touch PGDATA/recovery.signal. But the problem that postgresql_clean_from_restart function delete recovery.signal file, and if trying to create it once again, in initdb.d scripts, I able to do it, only after docker trying to run postgresl and not before. Is there any workaround?

**Comment by javsalgar** [comment]
Hi,

Could you explain the need of the recovery.signal file in order to proceed with the backup? What's the target installation you are currently using and what's the process for restoring the backup?

**Comment by javsalgar** [comment]
Hi,

In the setup.sh script, we have something like this

```
# Allow running custom pre-initialization scripts
postgresql_custom_pre_init_scripts
# Ensure PostgreSQL is initialized
postgresql_initialize
# Allow running custom initialization scripts
postgresql_custom_init_scripts
```

Would it make sense to move the clean_from_restart function BEFORE the postgresql_custom_pre_init_scripts? That would avoid the issue of removing the signal file because you could set it in a pre_init script. Would that work for your case?

**Comment by InteNs** [comment]
currently we found a workaround to remove the `.user_scripts_initialized` file and putting the script that places the signal in the initdb.d directory, this means that we can't use that directory for anything else unfortunately.

as a reference here is our recover script:
```
#!/bin/bash

set -e

if    ls -1qA $PGDATA | grep -q .
then  ! echo pg data is not empty, skipping wal-g backup-fetch...
else  wal-g backup-fetch $PGDATA LATEST
fi


echo "enabling recovery mode..."
cp /opt/jobport/scripts/signal_recovery.sh /docker-entrypoint-initdb.d/
rm -f /bitnami/postgresql/.user_scripts_initialized

echo "disabling archiving and remote connections..."
cp /opt/jobport/confs/recovery_postgresql.conf /bitnami/postgresql/conf/postgresql.conf
cp /opt/jobport/confs/maintenance_pg_hba.conf /bitnami/postgresql/conf/pg_hba.conf

echo "setting ownership to our non-root user"
chown -R 1001:1001 $PGDATA
chown -R 1001:1001 /bitnami/postgresql/conf

cat <<EOF
******************
* Recovery prepration complete
* You should now restart the server container to start the recovery process.
******************
EOF
```
in the recovery postgresql.conf a post-recover script is set that removes the conf, pg_hba, and signal-placer script


this setup means due to the discrepancy between this image and the bitnami/postgresql-repmgr image that we can't "clusterize" our setup just yet :(

**Comment by javsalgar** [comment]
Hi,

As you reported the issue and you think that my proposal covers your use case, would you like to submit a PR with the change? (it only needs to be done in one of the branches, our automation would integrate with the rest). If not we will do it

**Comment by javsalgar** [comment]
Thanks! The team will take a look
