### ISSUE TITLE
How to set mem and cpu resourcing in helm chart?

### ISSUE THREAD

**Issue by magick93** [bitnami/bitnami-docker-postgresql#299]
Hello

I'm trying to modify the allocated cpu and memory resourcing.

However, we I search for CPU in the statefulset.yaml but could not see any exiting variable for this, nor for memory (except for use with `emptyDir`).

I see in the readme, the following:

```
resources | CPU/Memory resource requests/limits | Memory: 256Mi, CPU: 250m
```

However I dont understand how I can set two different values from a single variable. 

# Details

```
apiVersion: v2
appVersion: 11.12.0
```

**Comment by juan131** [comment]
Hi @magick93 

The following values allow you to define custom resources settings:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L708

If you're looking for disk storage, you need to modify the parameter below:

- https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L496

For instance, you can install the Bitnami PostgreSQL chart using the **values.yaml** below to define your custom resources limits and requests + persistence storage:

```yaml
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m
persistence:
  size: 8Gi
```

E.g:

```console
$ helm install postgresql bitnami/postgresql -f values.yaml
```
