### ISSUE TITLE
Pgroonga

### ISSUE THREAD

**Issue by sida-khalibre** [bitnami/bitnami-docker-postgresql#301]
Does this image support pgroonga extention?
Thanks

**Comment by alvneiayu** [comment]
hi @sida-khalibre 

I think that this extension is not included in our PostgreSQL container. You can verify it checking in this path /opt/bitnami/postgresql/share/extension/. I invite you to run the container and verify it.

Thanks a lot

Álvaro

**Comment by sida-khalibre** [comment]
hi @alvneiayu 

Thank you for your response. Do you have any guide to add additional extension such pgroonga ?

Thanks

**Comment by alvneiayu** [comment]
hi @sida-khalibre 

We don't have our guide to integrate a new extension but I think that you can find several guides in Google like:

https://severalnines.com/database-blog/creating-new-modules-using-postgresql-create-extension

Thanks a lot

Álvaro
