### ISSUE TITLE
Please mention POSTGRES_TIMEZONE in README

### ISSUE THREAD

**Issue by lathspell** [bitnami/bitnami-docker-postgresql#308]
Would be nice, if the environment variable POSTGRES_TIMEZONE would be mentioned in the README so that people know how to set it.

It's different from the documented "audit.logTimezone" which only affects the logging not "SELECT now();"

Please also mention it in the Helm chart.

**Comment by marcosbc** [comment]
Hi @lathspell, we're open for contributions, so feel free to send a PR adding the environment variable in the README.

**Comment by lathspell** [comment]
un-stale

**Comment by marcosbc** [comment]
Hi @lathspell, we just added the following section to the README: https://github.com/bitnami/bitnami-docker-postgresql/#configuring-time-zone
