### ISSUE TITLE
Incorrect permissions for recovery.conf in postgresql:10 images

### ISSUE THREAD

**Issue by AlexeyDemidov** [bitnami/bitnami-docker-postgresql#309]
**Description**

When using master-slave replication with `bitnami/postgresql:10` images, on the first run `postgresql-slave` container sometimes fails with the following message:

``
2021-11-05 06:54:36.845 GMT [150] LOG:  database system was interrupted; last known up at 2021-11-05 06:54:11 GMT
2021-11-05 06:54:36.919 GMT [150] FATAL:  could not open recovery command file "recovery.conf": Permission denied
``

The recovery file is owned by `root` and has `600` permissions 

``
-rw------- 1 root root 5762 Nov  5 07:11 /bitnami/postgresql/data/recovery.conf
``

Looks like `chown` is missing there 
https://github.com/bitnami/bitnami-docker-postgresql/blob/2703f19a75388b0924d2b47ca98d7ddd625f2901/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L899

Adding the following code after this line fixes the issue for me.

``` 
am_i_root && chown "$POSTGRESQL_DAEMON_USER:$POSTGRESQL_DAEMON_GROUP" "$POSTGRESQL_RECOVERY_FILE" 
```

On the subsequent runs `postgresql-slave` starts normally as the following `chown -R` fixes the ownership (but on the first `docker-compose up` this code runs before `recovery.conf` is created) https://github.com/bitnami/bitnami-docker-postgresql/blob/2703f19a75388b0924d2b47ca98d7ddd625f2901/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L580

**Steps to reproduce the issue:**

I'm unable to replicate this issue with included `docker-compose-replication.yml` and I'm unable to make my `docker-compose.yml` public. My docker-compose includes a Django app and has an artificial network delay added between master and slave PostgreSQL containers.

**Comment by carrodher** [comment]
Please take into account this is non-root container, the directories belong to the root group but a random user (that always is part of this root group). This approach is used to allow the container to be executed by random non-root users (a good practice implemented in different k8s distributions).

You can find more info about those topics by taking a look at
- https://docs.bitnami.com/kubernetes/faq/configuration/use-non-root/
- https://docs.bitnami.com/tutorials/work-with-non-root-containers/
- https://docs.bitnami.com/tutorials/bitnami-best-practices-hardening-containers/#root-and-non-root-containers

**Comment by AlexeyDemidov** [comment]
@carrodher Sorry, I forgot to mention that I modified the containers to run as root as I need to modify network settings to inject delay. Is running as root an unsupported mode for this container?

**Comment by carrodher** [comment]
The container should be able to be executed as non-root and root without any issues. If you are using directly the Docker CLI you should be able to do it by using the `--user root` without any other change; in the same way, for Docker Compose you should be able to set `user: root` at the same level than the `image:` property

**Comment by AlexeyDemidov** [comment]
@carrodher I'm using this image as a base image (`FROM bitnami/postgresql:10`) for a custom Dockerfile as I need to install some additional packages. There is no difference whether I use `USER 0` in my Dockerfile or if I use `user: root` in my `docker-compose.yml`, the problem with incorrect permissions for `recovery.conf` file is still present.

**Comment by carrodher** [comment]
Are you using local volumes for the persistence? In that case, make sure the local directory has the proper permissions.
The container is configured in a way where all the directories used by the binary/daemon should belong to the `root` group, on this way, everything should work fine either if there is a random user (that belongs to the root group as `1001`) or if it is running by the `root` user (which group is `root` as well).

**Comment by AlexeyDemidov** [comment]
@carrodher , I replicated the issue with minimal changes https://github.com/AlexeyDemidov/bitnami-docker-postgresql/commit/283396bae5cba1bd9490923270b48ee505222005 

Run `docker-compose -f docker-compose-replication.yml up` and watch the slave exit with following log:

```
postgresql-slave_1   | 
postgresql-slave_1   | postgresql 11:46:41.25 INFO  ==> ** Starting PostgreSQL **
postgresql-slave_1   | 2021-11-09 11:46:41.269 GMT [1] LOG:  pgaudit extension initialized
postgresql-slave_1   | 2021-11-09 11:46:41.269 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql-slave_1   | 2021-11-09 11:46:41.269 GMT [1] LOG:  listening on IPv6 address "::", port 5432
postgresql-slave_1   | 2021-11-09 11:46:41.275 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
postgresql-slave_1   | 2021-11-09 11:46:41.288 GMT [151] LOG:  database system was interrupted; last known up at 2021-11-09 11:46:40 GMT
postgresql-slave_1   | 2021-11-09 11:46:41.370 GMT [151] FATAL:  could not open recovery command file "recovery.conf": Permission denied
postgresql-slave_1   | 2021-11-09 11:46:41.371 GMT [1] LOG:  startup process (PID 151) exited with exit code 1
postgresql-slave_1   | 2021-11-09 11:46:41.371 GMT [1] LOG:  aborting startup due to startup process failure
postgresql-slave_1   | 2021-11-09 11:46:41.371 GMT [1] LOG:  database system is shut down
bitnami-docker-postgresql_postgresql-slave_1 exited with code 1
```

**Comment by carrodher** [comment]
Thanks, @AlexeyDemidov, I was able to reproduce the issue on my side I would like to understand what is the purpose of the `chmod 600` you mentioned. The _recovery.conf_ file has the following permissions (before and after the `chmod`):
```
postgresql-slave_1   | -rw-r--r-- 1 root root 5762 Nov 11 08:44 /bitnami/postgresql/data/recovery.conf
postgresql-slave_1   | -rw------- 1 root root 5762 Nov 11 08:44 /bitnami/postgresql/data/recovery.conf
```
the first set of permissions should be fine to read the file with any user belonging to the root group.
I tested two scenarios (`user: root` and default user) using an image with the following line removed
```diff
        cp -f "$POSTGRESQL_BASE_DIR/share/recovery.conf.sample" "$POSTGRESQL_RECOVERY_FILE"
-       chmod 600 "$POSTGRESQL_RECOVERY_FILE"
        postgresql_set_property "standby_mode" "on" "$POSTGRESQL_RECOVERY_FILE"
```
and everything seems to be working fine:
```console
# User root
$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED              STATUS              PORTS                     NAMES
97c0ef67d7f8   carrodher/postgresql   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:49174->5432/tcp   debian-10_postgresql-slave_1
671661641aef   carrodher/postgresql   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:49173->5432/tcp   debian-10_postgresql-master_1

# User 1001
$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED              STATUS              PORTS                     NAMES
cd324316561e   carrodher/postgresql   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:49176->5432/tcp   debian-10_postgresql-slave_1
c5bd3afc6729   carrodher/postgresql   "/opt/bitnami/script…"   About a minute ago   Up About a minute   0.0.0.0:49175->5432/tcp   debian-10_postgresql-master_1
```

Can you try if your use case is solved with this change? In that case I will perform the change and test the different PostgreSQL branches in our internal test & release pipeline

**Comment by AlexeyDemidov** [comment]
@carrodher recovery.conf needs 600 permissions because it contains sensitive information like a password, which is added to this file by following code: https://github.com/bitnami/bitnami-docker-postgresql/blob/2703f19a75388b0924d2b47ca98d7ddd625f2901/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L901

If you read my original post you'll find the fix which worked for me.

**Comment by carrodher** [comment]
Yeah, that's true. I had not thought of that option, would you like to create a PR implementing that solution? We will create it otherwise, just asking since you discovered the issue and provided the solution

**Comment by AlexeyDemidov** [comment]
@carrodher I have created PR https://github.com/bitnami/bitnami-docker-postgresql/pull/311

**Comment by carrodher** [comment]
Thanks! The team will test and review it on Monday. At a first glance, I would tell you that those changes can be applied to the different PostgreSQL versions (9.6, 10, 11, 12, 13, and 14). It should just be replicating the changes in the different `VERSION/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh` files

**Comment by AlexeyDemidov** [comment]
@carrodher Support for `recovery.conf` file was removed in PostgreSQL 12 and the code to create this file is skipped by the  following condition in `libpostgresql.sh` https://github.com/bitnami/bitnami-docker-postgresql/blob/2703f19a75388b0924d2b47ca98d7ddd625f2901/10/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L893

**Comment by carrodher** [comment]
Unfortunately the _libpostgresql.sh_ file is replicated for the different versions, that is why this condition checking the version is needed, otherwise the comparison could be avoided since the file is specific to the major version branch.
We used an internal templating system to generate the scripts and, in this case, this script is the same across branches
