### ISSUE TITLE
Large SQL files in /docker-entrypoint-initdb.d can't be processed.

### ISSUE THREAD

**Issue by jim-barber-he** [bitnami/bitnami-docker-postgresql#312]
**Description**

The import of a large SQL dump to initialise the database hangs (or to be so slow that it appears as a hang).
However I was able to get it working by hacking the `postgresql_execute_print_output` function of the `/opt/bitnami/scripts/libpostgresql.sh` script in a custom image (details at the end of the case).

I am using `extraVolumeMounts` and `extraVolumes` of the bitnami postgresql Helm chart ( https://github.com/bitnami/charts/tree/master/bitnami/postgresql ) to mount a hostPath directory into the `bitnami/postgresql:13` image to initialise the database.
One of the SQL files is a 498MiB `.sql.gz` file, which when uncompressed is 1.2GiB in size.
When running with debug logging enabled, I can see a line showing it is `Executing` the sql script, but it does not show the line that says `Executing SQL command:` followed by the SQL to run.
For smaller files this was fine, but for the large file it gets stuck seemingly forever (I gave it 10 hours overnight before aborting).
Using a different Helm chart and the `postgres` image from Docker Hub instead of the Bitnami image is able to import the large file in a bit over 1 minute.

**Steps to reproduce the issue:**

1. Produce a SQL dump file for a PostgreSQL database with a lot of data.
2. Configure a new Docker container using the `bitnami/postgresql` Docker image to mount the dump file in the ` /docker-entrypoint-initdb.d/` directory
3. Watch the database never become ready while it gets stuck processing the large dump.

**Describe the results you received:**

Tailing the logs of the Bitnami postgresql container shows these logs as the last line:
```
postgresql 07:23:47.99 DEBUG ==> Executing /docker-entrypoint-initdb.d/03_db_prep.sql
postgresql 07:23:48.00 DEBUG ==> Executing SQL command:
\o /dev/null
ALTER DATABASE "engine_data" SET search_path TO core_data, public;
postgresql 07:23:48.02 DEBUG ==> Executing /docker-entrypoint-initdb.d/10_important_data.sql.gz
```
It never proceeds from here, and the database never becomes ready to connect to.

**Describe the results you expected:**

The next line shown should have been along the lines of:
```
postgresql $TIMESTAMP DEBUG ==> Executing SQL command:
```
Followed by the SQL and then the import of the data to proceed and the database to become ready to connect to.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here are the files I'm trying to import into the database:
```
$ ls -l /opt/dev_init 
total 457648
-rwxr-xr-x 1 ubuntu ubuntu       695 Dec  1 05:17 00_db_config.sh*
-rw-r--r-- 1 ubuntu ubuntu       145 Dec  1 04:05 00_extra_databases.sql
-rw-r--r-- 1 ubuntu ubuntu      3505 Dec  1 05:18 00_users.sql
-rw-r--r-- 1 ubuntu ubuntu    109862 Nov 16 07:37 01_db_schema.sql.gz
-rw-r--r-- 1 ubuntu ubuntu       737 Nov 16 06:53 02_reporting_schema.sql.gz
-rw-r--r-- 1 ubuntu ubuntu        80 Nov 16 06:53 03_db_prep.sql
-rw-r--r-- 1 ubuntu ubuntu 468419651 Nov 16 06:55 10_important_data.sql.gz
-rw-r--r-- 1 ubuntu ubuntu      1235 Nov 16 06:55 11_seed_dev.sql
-rw-r--r-- 1 ubuntu ubuntu        88 Nov 16 06:55 95_refresh_materialized_views.sql
-rw-r--r-- 1 ubuntu ubuntu     45976 Nov 16 06:53 96_db_schema.sql.gz
-rw-r--r-- 1 ubuntu ubuntu       561 Nov 16 06:53 97_reporting_schema.sql.gz
-rw-r--r-- 1 ubuntu ubuntu        34 Nov 16 06:55 98_db_post_restore.sql
-rwxr-xr-x 1 ubuntu ubuntu       641 Dec  1 04:51 99_db_config.sh*
-rw-r--r-- 1 ubuntu ubuntu       484 Nov 26 07:04 he_admin_user.sql
```
It gets as far as the `10_important_data.sql.gz` file where it then gets stuck.

**Version**

- Output of `docker version`:

```
$ docker version                                                               
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:34:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~20.04.1
  GitCommit:        
 runc:
  Version:          1.0.1-0ubuntu2~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

- Output of `docker info`:

```
$ docker info                
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 58
  Running: 36
  Paused: 0
  Stopped: 22
 Images: 37
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1022-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.477GiB
 Name: ip-10-200-3-149
 ID: GQEJ:4JUW:45H5:AWJ6:L7TO:Q4TW:2SML:N442:XVMZ:GQCS:GXNG:FY5F
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

Not applicable.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is a development environment on an Ubuntu Focal Linux system running in a Kubernetes environment provided by Minikube.

The Bitnami Helm chart was provided these options to mount the files to be restored.
```
primary:
  extraVolumeMounts:
    - name: db-init
      mountPath: /docker-entrypoint-initdb.d
  extraVolumes:
    - name: db-init
      hostPath:
        path: /opt/dev_init
        type: Directory
```

As I mentioned in the description of the issue. I was able to build a custom image by making some changes to the `postgresql_execute_print_output` function of the `/opt/bitnami/scripts/libpostgresql.sh` script.
The change I made was as follows:
```
@@ -1028,11 +1028,8 @@
     [[ -n "$db" ]] && args+=("-d" "$db")
     [[ "${#opts[@]}" -gt 0 ]] && args+=("${opts[@]}")
 
-    # Obtain the command specified via stdin
-    local sql_cmd
-    sql_cmd="$(</dev/stdin)"
-    debug "Executing SQL command:\n$sql_cmd"
-    PGPASSWORD=$pass psql "${args[@]}" <<<"$sql_cmd"
+    # Execute the Query/queries from stdin
+    PGPASSWORD=$pass psql "${args[@]}"
 }
 
 ########################
```
I believe it is the act of trying to read 1.2GiB of data into the `sql_cmd` shell script variable that causes the issue.
Removing the line that does that, and the line that tries to show what SQL is being executed and just letting the `psql` command process `stdin` itself fixes the problem.

I feel like trying to show the SQL that is about to be executed probably isn't a good idea for anything beyond super small database imports.
If the import fails, the user will already know from the debugging output which file it was processing when the import died, which should be enough for them to debug the problem.

**Comment by carrodher** [comment]
Thanks for the detailed information, would you like to create a PR implementing the solution you're using? On this way the team will review it and provide feedback

**Comment by carrodher** [comment]
The PR with the solution was merged, I'm closing this issue. Thanks!
