### ISSUE TITLE
Upgrade images to use debian 11

### ISSUE THREAD

**Issue by irizzant** [bitnami/bitnami-docker-postgresql#317]
**Description**

Debian 11 docker images are available, currently this Postgresql image only supports Debian 10.

**Comment by carrodher** [comment]
We have plans for migrating the whole open-source catalog to images based on Debian 11, in fact, currently, the image used as the base image (bitnami/minideb) already has a tag for Debian 11 bullseye, you can see it at [dockerhub](https://hub.docker.com/layers/bitnami/minideb/bullseye/images/sha256-aff2830b85a0496ee40bcab39c638027a9d455dda806c761a124398aa073bb9b?context=explore).

There are more steps needed to migrate the whole catalog so we can't provide an ETA at this time, but it's on our roadmap

**Comment by DanVisan** [comment]
Any updates on this? 
libsasl2-2 and zlib1g which are part of the bitnami/postgrsql image have reported security vulnerabilities that can be easily fixed in debian 11 but not debian 10 (as today).

**Comment by carrodher** [comment]
Unfortunately, Debian 11 is not yet supported in the open-source Bitnami Application Catalog. It's in our roadmap but due to other priorities, I can't provide an ETA at this moment.

**Comment by px-kesavan** [comment]
Hi @carrodher , 
Any new updates on this ?. Debian 10 images are prone to glibc vulnerabilities as well. It's nice that you guys have already planned for migrating to Deb11. Please update us when you have an ETA on this. Thanks
