### ISSUE TITLE
Creation of initial postgresql database with additional intdb arguments fails

### ISSUE THREAD

**Issue by HarlekinSimplex** [bitnami/bitnami-docker-postgresql#324]
### Name and Version

bitnami/postgresql:latest (as of the 08. Feb 2022)

### What steps will reproduce the bug?

Create a docker-compose.yml containing the following env variable:
```
- POSTGRESQL_INITDB_ARGS=--lc_ctype=C --lc_collate=C
- POSTGRESQL_DATABASE=test
- POSTGRESQL_USERNAME=test
- POSTGRESQL_PASSWORD=test
```

Run docker-compose up -d to create container with intial db

### What is the expected behavior?

The creation of a database "test" at container startup with LC_CTYPE and LC_COLLATE set to C.

### What do you see instead?

```
...
postgresql 17:30:40.84 Welcome to the Bitnami postgresql container
postgresql 17:30:40.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 17:30:40.84 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 17:30:40.84
postgresql 17:30:40.86 INFO  ==> ** Starting PostgreSQL setup **
postgresql 17:30:40.90 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 17:30:40.90 INFO  ==> Loading custom pre-init scripts...
postgresql 17:30:40.91 INFO  ==> Initializing PostgreSQL database...
postgresql 17:30:40.93 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 17:30:40.93 INFO  ==> Generating local authentication configuration
postgresql 17:30:40.94 INFO  ==> Initializing PostgreSQL with --lc_ctype=C --lc_collate=C extra initdb arguments
...
```

This is repeated 4 times in the docker-compose log and then the container initialization terminates without even creating a volume. It looks like the container creation fails right after starting the initdb process.
After that the startup process seems to resets and tries it 4 times in a row before giving up.

**Comment by HarlekinSimplex** [comment]
I tried to use:
- POSTGRES_INITDB_ARGS=--lc_ctype=C --lc_collate=C
- POSTGRES_INITDB_ARGS="--lc_ctype=C --lc_collate=C"
- POSTGRESQL_INITDB_ARGS=--lc_ctype=C --lc_collate=C
- POSTGRESQL_INITDB_ARGS="--lc_ctype=C --lc_collate=C"

- POSTGRES_INITDB_ARGS=--lc_ctype=C
- POSTGRES_INITDB_ARGS="--lc_collate=C"
- POSTGRESQL_INITDB_ARGS=--lc_ctype=C 
- POSTGRESQL_INITDB_ARGS="--lc_collate=C"

All of them let to the same result. The creation of the container is terminated richt after starting initdb.

**Comment by juan131** [comment]
Hi @HarlekinSimplex 

Could you please add the environment variable `BITNAMI_DEBUG=true` to your Docker Compose environment and retry? Then, share the obtained logs that will obtain more information for us to debug the issue. Thanks in advance.
