### ISSUE TITLE
ENV variables not properly escaped in scripts

### ISSUE THREAD

**Issue by mavericm1** [bitnami/bitnami-docker-postgresql#330]
### Name and Version

bitnami/postgresql:13

### What steps will reproduce the bug?

```
.env.master.db:
POSTGRESQL_REPLICATION_MODE=master
POSTGRESQL_USERNAME=blah
POSTGRESQL_PASSWORD=fdsa^7^^GYdzy4#ka25
POSTGRESQL_DATABASE=blah_db
POSTGRESQL_REPLICATION_USER=blah_repl
POSTGRESQL_REPLICATION_PASSWORD=FGHN23*Ud2EYSuT7&cz

.env.slave.db:
POSTGRESQL_REPLICATION_MODE=slave
POSTGRESQL_USERNAME=blah
POSTGRESQL_PASSWORD=fdsa^7^^GYdzy4#ka25
POSTGRESQL_MASTER_HOST=db
POSTGRESQL_MASTER_PORT_NUMBER=5432
POSTGRESQL_REPLICATION_USER=blah_repl
POSTGRESQL_REPLICATION_PASSWORD=FGHN23*Ud2EYSuT7&cz
```
### What is the expected behavior?

```
postgresql.conf:
primary_conninfo = 'host=db port=5432 user=blah_repl password=FGHN23*Ud2EYSuT7&cz application_name=walreceiver'
```
### What do you see instead?

```
postgresql.conf:
primary_conninfo = 'host=db port=5432 user=blah_repl password=FGHN23*Ud2EYSuT7#primary_conninfo = ''			# connection string to sending servercz application_name=walreceiver'
```
### Additional information

It appears that env variable values aren't properly escaped which cause undesirable issues when starting and config generation.

**Comment by rafariossaa** [comment]
Hi,
  We have released a new image to address this issue `13.6.0-debian-10-r26`
  Could you give it a try ?

**Comment by mavericm1** [comment]
I've tested again with the use of &*<>| in the replication env password field and it appears that it is properly working now and generating the proper conninfo config line and working as intended.

Thank you for working on this i would have tried to track down the propagation through the startup scripts but i have had limited time lately.

-Logan

**Comment by rafariossaa** [comment]
@mavericm1 Thanks for you feedback!.
