### ISSUE TITLE
POSTGRESQL_REPLICATION_MODE

### ISSUE THREAD

**Issue by ductran-ms** [bitnami/bitnami-docker-postgresql#331]
### Name and Version

bitnami/postgresql:latest

### What is the problem this feature will solve?

POSTGRESQL_REPLICATION_MODE value is master/slave. Can this is set as master/relica for better term. This is similar to redis REDIS_REPLICATION_MODE that accepts master/replica

### What is the feature you are proposing to solve the problem?

For better terminology, I suggest that  POSTGRESQL_REPLICATION_MODE also accept replica. This is similar to REDIS_REPLICATION_MODE

**Comment by juan131** [comment]
Hi @ductran-ms 

We already substituted the "slave" term in the PostgreSQL chart by "read replica" as you can see in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/postgresql#postgresql-read-only-replica-parameters

However, the container logic still expect "slave" and we should definitely adapt this in the container too. Would you like to contribute with a PR replacing this terminology?

**Comment by ductran-ms** [comment]
Hi @juan131, sorry for the delay. I'm new to this and not sure where to start or change. Could you or someone take care fo this? Thank you.

**Comment by rafariossaa** [comment]
Hi, 
  [This is a small guide ](https://github.com/bitnami/bitnami-docker-postgresql/blob/master/CONTRIBUTING.md) on how to contribute to this repository.
  You will need to change the environment variables used and the logic in the shell scripts to act accordingly.
