### ISSUE TITLE
"stack depth limit exceeded" errors on queries with many parameters

### ISSUE THREAD

**Issue by synopsys-cookt** [bitnami/bitnami-docker-postgresql#334]
### Name and Version

bitnami/postgresql:14, bitnami/postgresql:13, bitnami/postgresql:11

### What steps will reproduce the bug?

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-postgresql/master/docker-compose.yml > docker-compose-bitnami.yaml
$ docker compose -f docker-compose-bitnami.yaml up -d
$ ./stack_depth_limit_exceeded.py | psql -h localhost -p 5432 -U postgres postgres
```
where `stack_depth_limit_exceeded.py` is
```
#!/usr/bin/env python3

import uuid

# Must be a multiple of 3.
max = 3300

print('select version();')
print('begin;')
print('create table temp_table(a uuid, b uuid, c uuid, key text);')
print('create table temp_table_2(a uuid, b uuid, c uuid, key text);')

print('prepare s1 as select * from temp_table t1 left join temp_table_2 t2 on t1.key = t2.key where (t1.a, t1.b, t1.c) in (', sep='', end='')
for i in range(1, max, 3):
	print(f'(${i},${i+1},${i+2}),', sep='', end='')
print(f'(${max+1},${max+2},${max+3})', sep='', end='')
print(');')

print('execute s1(', sep='', end='')
for i in range(1, max, 3):
	print(f"'{uuid.uuid4()}','{uuid.uuid4()}','{uuid.uuid4()}',", sep='', end='')
print(f"'{uuid.uuid4()}','{uuid.uuid4()}','{uuid.uuid4()}'", sep='', end='')
print(');')

print('rollback;')
print('deallocate s1;')
```

### What is the expected behavior?

```
                                         version                                         
-----------------------------------------------------------------------------------------
 PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

BEGIN
CREATE TABLE
CREATE TABLE
PREPARE
 a | b | c | key | a | b | c | key 
---+---+---+-----+---+---+---+-----
(0 rows)

ROLLBACK
DEALLOCATE
```

### What do you see instead?

```
                                        version                                         
----------------------------------------------------------------------------------------
 PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

BEGIN
CREATE TABLE
CREATE TABLE
ERROR:  stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

### Additional information

The error is consistently reproducible with `14-debian-10`, `13-debian-10`, `11-debian-10`, and `9.6-debian-10` using a query with 3300 parameters.

For comparison the same versions of PG using Alpine-based containers require 28k+ parameters to hit the same error, and non-containerized PG has the same parameter limits as on Alpine.

Removing the JOIN from the sample query roughly doubles the number of parameters the Bitnami images can handle, but has no effect on Alpine-based PG or non-containerized PG.

The query generated by the reproducer script mimics a production query.  Other queries run into similar problems, but they have widely varying numbers of parameters they can handle.

We have two workarounds:
1. Raise `max_stack_depth` to its maximum value.
2. Substantially reduce our query partitioning threshold, which increases the runtime of affected operations by about 2.5x.

The real problem is the unpredictable number of parameters each query can handle and the subsequent uncertainty about the largest, safe query partitioning threshold we can use.  (This is a legacy application, so it is unfortunately not possible to redesign it to avoid queries needing so many parameters.)

All tests were done with
```
$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
$ 
$ dockerd --version
Docker version 20.10.12, build 459d0df
```

**Comment by javsalgar** [comment]
Hi,

Thank you for reporting. I think we should enable an env variable that allows configuring the postgresql max_stack_depth value. Would you like to submit a PR adding the feature?

**Comment by synopsys-cookt** [comment]
I'll give it a try.

However, do you have any idea why only Bitnami images have this problem?  The smaller number of parameters (even with `max_stack_depth` maxed out) isn't really the problem; it's the per-query variability.  Do you have any insight as to what the root cause could be?  Is it due to something pulled in from upstream Debian?

**Comment by synopsys-cookt** [comment]
FWIW, the Bitnami PG 11 image at https://repo1.dso.mil/dsop/bitnami/postgres/postgresql11 exhibits the same limitations as the standard Bitnami PG 11 image.

**Comment by synopsys-cookt** [comment]
Yes, it says the exact same thing.  All the instances I tested against were using the default 2MB stack size.

**Comment by marcosbc** [comment]
I see. I'm creating a task for investigating this issue. Unfortunately I cannot provide an ETA for when it will be tackled.

If you happen to find the issue, feel free to contribute the fix! PRs are welcome, and we'd be happy to check it.

**Comment by synopsys-cookt** [comment]
@marcosbc,
It looks like the docker build downloads a pre-built set of postgresql binaries.  Where do those get built?

Comparing the output of `pg_config` from the various PG instances I tested with shows that Bitnami's PG was built without any optimization flags set, whereas the others all have `-O2`.  This may (or may not) be the source of the problem.

**Comment by marcosbc** [comment]
Hi @synopsys-cookt, currently those binaries are built with our internal pipeline. Unfortunately those scripts are not open-source as of this moment.

That said, what you point out makes sense indeed, I will update the internal task and increase its priority.

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that we released a new revision of all the PostgreSQL containers, now compiled with `-02`. We tested with python script and now it was working with values >24000

```
max = 24750

...


❯ ./stack_depth_limit_exceeded.py | psql -h localhost -p 5432 -U postgres postgres
                                        version
----------------------------------------------------------------------------------------
 PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

BEGIN
CREATE TABLE
CREATE TABLE
PREPARE
 a | b | c | key | a | b | c | key
---+---+---+-----+---+---+---+-----
(0 rows)

ROLLBACK
DEALLOCATE
```

**Comment by synopsys-cookt** [comment]
Thanks!!
