### ISSUE TITLE
Unable to run psql and other commands inside container

### ISSUE THREAD

**Issue by cawoodm** [bitnami/bitnami-docker-postgresql#335]
### Name and Version

bitnami/postgresql

### What steps will reproduce the bug?

Install postgres with this chart (tag`14.2.0-debian-10-r57`) then shell into the container and try to run `psql` or other commands.

```bash
helm install postgres-dev -n postgres \
  --set image.tag=14.2.0-debian-10-r57 \
  --set auth.postgresPassword=*** \
  --set primary.persistence.existingClaim=postgres-dev-pvc \
  --set primary.service.type=NodePort \
  --set primary.service.nodePorts.postgresql=30008 \
  bitnami/postgresql
```

### What is the expected behavior?

The commands should run.

### What do you see instead?

> error: local user with ID 1001 does not exist.

**Comment by rafariossaa** [comment]
Hi,
  Could you try this ?
```
$ helm install mypg bitnami/postgresql

$ kubectl exec -it mypg-postgresql-0 bash

I have no name!@mypg-postgresql-0:/$ . /opt/bitnami/scripts/libpostgresql.sh && postgresql_enable_nss_wrapper && psql
```

**Comment by cawoodm** [comment]
Yeah, that works.

Why is this necessary? It's quite hard to remember this every time we need to access our postgres...

Some actions like DROP DATABASE don't work reliably from tools like pgadmin so we are used to using `psql` here.

**Comment by rafariossaa** [comment]
That it needed because on openshift [user ID is random](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#use-uid). 

Maybe you can use something similar as the command that `helm install` outputs for running `psql`:

```
    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default mypg-postgresql -o jsonpath="{.data.postgres-password}" | base64 --decode)

To connect to your database run the following command:

    kubectl run mypg-postgresql-client --rm --tty -i --restart='Never' --namespace default --image docker.io/bitnami/postgresql:14.2.0-debian-10-r85 --env="PGPASSWORD=$POSTGRES_PASSWORD" \
      --command -- psql --host mypg-postgresql -U postgres -d postgres -p 5432
```
