### ISSUE TITLE
Porstgresql / Quay.io is not working anymore! 

### ISSUE THREAD

**Issue by pjgg** [bitnami/bitnami-docker-postgresql#336]
### Name and Version

quay.io/bitnami/postgresql:13.5.0

### What steps will reproduce the bug?
```console
$ docker pull quay.io/bitnami/postgresql:13.5.0                                          1 ↵
Error response from daemon: unauthorized: access to the requested resource is not authorized
```
### What is the expected behavior?

I few days ago I was able to download this image

### What do you see instead?
```
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Comment by carrodher** [comment]
The Bitnami container images are not going to be available in Quay from now on, you can use them from other registries such as DockerHub or GCR. The change should be straightforward, using the same repository (`bitnami/postgresql`) and tag (`13.5.0`) as usual, just changing the registry (i.e `quay.io` -> `docker.io`):
```console
$ docker pull docker.io/bitnami/postgresql:13.5.0
13.5.0: Pulling from bitnami/postgresql
a2b89359fa38: Pull complete
4e0b157f5a24: Pull complete
6980314e2d58: Pull complete
fb6a7d0d2f50: Pull complete
301db7cafc25: Pull complete
db04f2eae553: Pull complete
a5e67dd1479c: Pull complete
8642d8177c16: Pull complete
d31ebe5c70d9: Pull complete
05aedc96a169: Pull complete
af1dedb9176c: Pull complete
2a951d3d344d: Pull complete
70d3bb5f087a: Pull complete
142113720c81: Pull complete
Digest: sha256:847f239ac13c23fd4c5548a7ae1747f7be58d9846617d5f19746f674f690a6fe
Status: Downloaded newer image for bitnami/postgresql:13.5.0
docker.io/bitnami/postgresql:13.5.0
```

Since `docker.io` is the default registry used by Docker, you can even not specify the registry part:
```console
$ docker pull bitnami/postgresql:13.5.0
13.5.0: Pulling from bitnami/postgresql
Digest: sha256:847f239ac13c23fd4c5548a7ae1747f7be58d9846617d5f19746f674f690a6fe
Status: Image is up to date for bitnami/postgresql:13.5.0
docker.io/bitnami/postgresql:13.5.0
```

**Comment by pjgg** [comment]
Yes, but GoogleContainerRegistry and dockerHub are not open source, as far as I know. Would be great that Bitnami, that is an organization that claims to itself as an opensource promoter (and also your are opensource):

```
Bitnami makes it easy to get your favorite open source software up and running on any platform
```

doesn't force the end-user to use a proprietary solution. Instead of banning an opensource docker registry, open a discussion, push to the community to a "[Docker Verified Publishers](https://github.com/quay/quay/discussions/1274)" behavior/feature. 

Since then just continue publishing "none verified images" into Quay. Just keep informed to the end user (may be through a disclaimer in the repo) that these images are not verified.

**Comment by carrodher** [comment]
There are options to mirror the images to any other registry, such as Quay or self-hosted Harbor if as a user you prefer to maintain the storage and distribution of those container images on a different registry than the ones where those images are pushed by default

**Comment by BillDett** [comment]
Sorry to see you go- we'd definitely like to better understand your decision to leave quay.io. Please feel free to reach out directly -" bdettelb at redhat dot com"
