### ISSUE TITLE
Control script execution

### ISSUE THREAD

**Issue by ian-t-mackie** [bitnami/bitnami-docker-postgresql#338]
### Name and Version

bitnami/-docker-postgresql

### What is the problem this feature will solve?

The feature i would like is to be able to control the order of execution of scripts or manually specify one script to run others etc. Some form of control over initialization scripts. 

Is there a resource i missed?

### What is the feature you are proposing to solve the problem?

First thought is an environment variable that specifies init script, if set the auto discovery of other scripts is skipped.

### What alternatives have you considered?

naming script files in order for sorts to control execution order.

**Comment by javsalgar** [comment]
Hi,

Do you mean the use of init scripts that you mount in `docker-entrypoint.initdb`?  Did you try sorting it by name?

**Comment by ian-t-mackie** [comment]
Yes, and that works it just feels hacky. We would prefer some explicitness is all.

**Comment by ian-t-mackie** [comment]
```
├───common
│   └───refdata
│       ├───data
│       └───_tables
└───private
    ├───tenants
    │   ├───tenant_guid
    │   │   └───data
    │   ├───tenant_guid
    │   │   └───data
    │   ├───tenant_guid
    │   │   └───data
    │   └───tenant_guid
    │       └───data
    └───_tables
```
We use a structure as depicted above, at the root of this is a main entrypoint.sh that calls each required script to setup databases, users, permissions etc in all the subdirectories in the correct order.  
The issue we encountered was that this structure came from the official docker image and migrated to this image when we started deploying to other environments with certificates etc. The discovery of script files and executing them ended up crashing the image because of our entrypoint script and other scripts being called in the wrong order and databases already being setup.

Hopefully this gives a little more context as to wanting an explicit script mode i guess would be the way to describe it.

**Comment by migruiz4** [comment]
Hi @ian-t-mackie,

We use the same method for init scripts in multiple images in our catalog, and at the moment we haven't found any issues with it.

If you'd like to run your scripts in a specific order, then I would recommend naming them as follows:
```
docker-entrypoint.initdb/00-first-script.sh
docker-entrypoint.initdb/01-second-script.sh
docker-entrypoint.initdb/02-another-script.sh
...
```

If I'm not mistaken, the `postgres` image does not have an 'explicit script mode'. The main difference is they use `glob (*)` to find scripts under `docker-entrypoint.initdb/`, while we use `find` which also looks for init scripts in subdirectories:

https://github.com/docker-library/postgres/blob/master/14/bullseye/docker-entrypoint.sh#L326
https://github.com/bitnami/bitnami-docker-postgresql/blob/47d3a2a540031a7b1453b0aaee636689a5eb8b01/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L697

To solve your issue, I would suggest one of the following:
- Rename your scripts and subdirectories to be executed by alphanumeric order, therefore the main entrypoint.sh may not be needed.
- Move the other scripts to a different location and leave only your main entrypoint.sh
- Rename the scripts to not match this regex `.*\.\(sh\|sql\|sql.gz\)`, therefore they will be ignored by the `find` command.
