### ISSUE TITLE
Failed to validate connection to postgres

### ISSUE THREAD

**Issue by Ratul707** [bitnami/bitnami-docker-postgresql#342]
### Name and Version

bitnami/postgresql-repmgr:11.14

### What steps will reproduce the bug?

After transactions in the springboot container,the db rows addition should get done automatically which throws the error 2022-05-24 10:12:39.373  WARN 1 --- [ntainer#0-0-C-1] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@5111d97e (This connection has been closed.). Possibly consider using a shorter maxLifetime value.

Configmap has below entries

    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    #spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect

Also after dropping the table and restarting the springboot pod the tables  [both in spring.jpa.hibernate.ddl-auto=update and create modes] ,the table didnt get created automatically

### What is the expected behavior?

Tables and db entries should happen without any issues

### What do you see instead?

2022-05-24 11:31:17.054  WARN 1 --- [ntainer#0-0-C-1] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Failed to validate connection org.postgresql.jdbc.PgConnection@6979e70f (This connection has been closed.). Possibly consider using a shorter maxLifetime value.

**Comment by Ratul707** [comment]
Please help me on the same

**Comment by javsalgar** [comment]
Hi,

It seems that it could be related to how you configured your application, based on this kind of messages: `Possibly consider using a shorter maxLifetime value.`.

Does the same issue happen with the regular `bitnami/postgresql` chart? It could also be related with the networking configuration of your k8s cluster.
