### ISSUE TITLE
Numerous anonymous Docker Volumes created on up

### ISSUE THREAD

**Issue by fw-kgrove** [bitnami/bitnami-docker-postgresql#343]
### Name and Version

bitnami/postgresql:14

### What steps will reproduce the bug?

I am naming my own volume to mount. This is the way I have things set up in my `docker-compose.yml`:

![Screen Shot 2022-06-09 at 9 07 16 AM](https://user-images.githubusercontent.com/89661890/172854318-fd3b6d51-7888-451a-a962-8c8580cd87d3.png)

### What is the expected behavior?

No anonymous volumes created?

### What do you see instead?

Every time I put up my containers, 5 new Docker Volumes are created:

![Screen Shot 2022-06-09 at 9 48 08 AM](https://user-images.githubusercontent.com/89661890/172862860-d6130c2e-a5e7-480c-9f61-cdf1a1d9e614.png)

**Comment by fw-kgrove** [comment]
I came up with a work around to this issue. I’ve created a `line_items_db` folder where the db will be persistent and mounted to the container. Running docker-compose down -v takes down all volumes linked to the container. Seems a bit clunky, but it works.

![Screen Shot 2022-06-09 at 10 06 12 AM](https://user-images.githubusercontent.com/89661890/172869006-336f1025-b612-439b-afb8-b0a8032a5ee2.png)

**Comment by rafariossaa** [comment]
Hi,
  Have you tried if this same happens to you we using the docker-compose file provided ?.
  I think you are missing the `driver` in the volume section.

```
volumes:
  postgresql_data:
    driver: local
```

**Comment by fw-kgrove** [comment]
Unfortunately, that did not solve the problem.

**Comment by rafariossaa** [comment]
Have you tried the provided docker-compose file ?
