### ISSUE TITLE
how about add some plugin into the container

### ISSUE THREAD

**Issue by jiangxiaoqiang** [bitnami/bitnami-docker-postgresql#346]
### Name and Version

docker.io/bitnami/postgresql:13.3.0-debian-10-r75

### What is the problem this feature will solve?

I could not add the plugin into postgresql running in container, because it will loss when the container restart. 

### What is the feature you are proposing to solve the problem?

how about add some plugin from the source image?

this is the problem I am facing: https://stackoverflow.com/questions/72589224/is-it-possible-to-install-plugin-into-postgresql-13-running-in-kubernetes

**Comment by migruiz4** [comment]
Hi @jiangxiaoqiang,

The `bitnami/postgresql` image provides two mountpoints to execute initscripts:
- `/docker-entrypoint-preinitdb.d`, executed every time the container starts, runs before PostgreSQL is initialized. 
- `/docker-entrypoint-initdb.d`, executed only during the container first execution, runs after PostgreSQL is initialized. Supports `*.sh`, `*.sql` and `*.sql.gz` extensions.

You could use these mountpoints to add two scripts: one at `preinitdb` that installed your plugin and another at `initdb` that added your plugin extension.

The major downside of this method would be that Postgresql initialization will be delayed each time your container is restarted, but the alternative to this would be building your own custom image based on `bitnami/postgreql` installing your plugins.

**Comment by jiangxiaoqiang** [comment]
> Hi @jiangxiaoqiang,
> 
> The `bitnami/postgresql` image provides two mountpoints to execute initscripts:
> 
> * `/docker-entrypoint-preinitdb.d`, executed every time the container starts, runs before PostgreSQL is initialized.
> * `/docker-entrypoint-initdb.d`, executed only during the container first execution, runs after PostgreSQL is initialized. Supports `*.sh`, `*.sql` and `*.sql.gz` extensions.
> 
> You could use these mountpoints to add two scripts: one at `preinitdb` that installed your plugin and another at `initdb` that added your plugin extension.
> 
> The major downside of this method would be that Postgresql initialization will be delayed each time your container is restarted, but the alternative to this would be building your own custom image based on `bitnami/postgreql` installing your plugins.

I could not install componnet using script: https://stackoverflow.com/questions/73033918/how-to-install-wget-in-kubernetes-postgresql-pod
