### ISSUE TITLE
what is the password of the root

### ISSUE THREAD

**Issue by jiangxiaoqiang** [bitnami/bitnami-docker-postgresql#347]
### Name and Version

docker.io/bitnami/postgresql:13.3.0-debian-10-r75

### What is the problem this feature will solve?

when I install wget in the container:

```
I have no name!@reddwarf-postgresql-postgresql-0:/$ apt-get install wget
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
I have no name!@reddwarf-postgresql-postgresql-0:/$ sudo su
bash: sudo: command not found
I have no name!@reddwarf-postgresql-postgresql-0:/$ su -
Password: 
su: Authentication failure
I have no name!@reddwarf-postgresql-postgresql-0:/$ su -
Password: 
su: Authentication failure
I have no name!@reddwarf-postgresql-postgresql-0:/$ 

```

### What is the feature you are proposing to solve the problem?

what should I do to install wget in the container?

**Comment by fmulero** [comment]
Hi @jiangxiaoqiang

Most of our containers are [non-root-containers](https://docs.bitnami.com/tutorials/work-with-non-root-containers) and there is no way to elevate privileges from the container. If you want to run the image as root, you can change the user in the docker command:
```console
$ docker run -it --name psql -u root --rm docker.io/bitnami/postgresql:13.3.0-debian-10-r75 bash
```

**Comment by jiangxiaoqiang** [comment]
how about run the container as root user? I really need to install some extension for PostgreSQL 13. what should I do to run it as root user and install some extra plugin?
