### ISSUE TITLE
How to configure Dockerfile or docker-entrypoint.sh to share volume

### ISSUE THREAD

**Issue by cmardonespino** [bitnami/bitnami-docker-postgresql#77]
Hi!,

Someone can share how did you modificated the Dockerfile, entrypoint.sh file, or another thing to persist my database without permision?

I tried using the official Dockerfile and docker-entrypoint.sh file version 10, where I modificated their files. In Dockerfile, I modificated the last lines, replaced with:

> COPY ./docker-entrypoint.sh /usr/local/bin/
> RUN chmod 777 /usr/local/bin/docker-entrypoint.sh \
>     && ln -s /usr/local/bin/docker-entrypoint.sh 
> ENTRYPOINT ["docker-entrypoint.sh"]

In docker-entrypoint.sh I modificated linea 34 with the following:

`chmod 777 "$PGDATA"`

But when I does `docker-compose up`, the folder is created in my project folder, but it still with permision like root... I hope can you help me!

**docker version**
> Docker version 18.03.0-ce

**docker-compose version**
> docker-compose version 1.19.0

**S.O. machine**
> Ubuntu 16.04

**Comment by juan131** [comment]
Hi @cmardonespino 

Did you check the instruction about [Persisting your database](https://github.com/bitnami/bitnami-docker-postgresql#persisting-your-database)? You can simply attach a volume to your container so your database data is persisted on that volume.

**Comment by cmardonespino** [comment]
Hi @juan131 
Yes!, I did that, but I still have my folder of postgres with permision like root. Some suggestion?

`version: '3'
services:
    web:
      container_name: web_application
      restart: always
      build: .
      #command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
        # (HOST:CONTAINER)
      ports:
        - "8000:8000"
        # (HOST:CONTAINER)
      depends_on:
        - db
    db:
      #build: ./DockerfilePostgreSQL/
      container_name: postgres_db
      image: bitnami/postgresql:latest # Utiliza una imagen la cual en caso de no tener, la descarga
      #image: bitnami/postgresql:latest
      environment:
        POSTGRES_USER: postgres #CREA UN USUARIO Y UNA BASE DE DATOS CON PRIVILEGIOS
        POSTGRES_PASSWORD: password123 # LE ASIGNA UNA PASSWORD AL USUARIO Y SU BASE DE DATOS
      ports:
        - "5432:5432" # (HOST:CONTAINER)
      volumes:
        - ./postgres:/bitnami

#volumes:
#    api_data:
#    pgdata:

`

**Comment by juan131** [comment]
I was unable to reproduce it creating a directory to persist the data as you can check below:

```
mkdir postgres
docker-compose up
```

I used this simple `docker-compose.yaml`:

```
version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
    volumes:
      - './postgres:/bitnami'
```

Could you add the env. variable below to the environment section of postrgresql and share the output of running `docker-compose up`?

```
    environment:
      NAMI_DEBUG: "--log-level trace"
```

**Comment by cmardonespino** [comment]
Yeah, with that that environment variable its work, but folder "data" is still with permission denied :/ Sorry @juan131 but Im novice in docker, its a little hard to me!

**Comment by juan131** [comment]
Hi @cmardonespino 

Could you please paste the whole output? I just want to check the logs once you activate the Debug mode with the env. variable I suggested you.

**Comment by vjdhama** [comment]
I am trying 

```docker run --name postgres -e POSTGRESQL_USERNAME=foo -e POSTGRESQL_PASSWORD=lg9oZjbZMA -e POSTGRESQL_DATABASE=foo_db -e POSTGRESQL_REPLICATION_USER=rep_user -e POSTGRESQL_REPLICATION_PASSWORD=47i595oUSv -v /postgresql:/bitnami/postgresql/data -p 5432:5432 --restart always bitnami/postgresql:latest```

But it fails with 

```Welcome to the Bitnami postgresql container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues

nami    INFO  Initializing postgresql
postgre INFO  ==> No injected configuration files found. Creating default config file...
postgre INFO  ==> Deploying PostgreSQL from scratch...
Error executing 'postInstallation': initdb: could not change permissions of directory "/opt/bitnami/postgresql/data": Operation not permitted```

**Comment by beltran-rubo** [comment]
This error happens when the container does not have privileges to modify the folder permissions  that you mounted from your host.

Check this doc to know the difference between root & non-root containers https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/ The workaround is to use "USER root" in the docker-compose to run this container with root priveleges.

**Comment by vjdhama** [comment]
Thanks @beltran-rubo 

It works with workaround.

```
docker run --name postgres --user=root -v /postgresql:/bitnami/postgresql/data bitnami/postgresql:latest
```

**Comment by beltran-rubo** [comment]
Great! thanks for posting it.
