### ISSUE TITLE
Add option to run init_db script(s) on docker run

### ISSUE THREAD

**Issue by liyaka** [bitnami/bitnami-docker-postgresql#78]
I have an init_db.sql that creates databases, users and etc and I need it to run on docker run after postgres db is up. Running some post-run script is not an option at the moment.
The official postgres docker image has **docker-entrypoint-initdb.d** folder where you can put such scripts and they run automatically as a part of the docker-entrypoint script.
I'm using bitnami/postgres image because I need its out-pf-the-box replication functionality, which is great!
I created a Dockerfile that inherits from **bitnami/postgres:9.6** and I added a copy of the db_init script.
When I tried to add running it as an addition to the original CMD, I get this error:
```
nami    ERROR com.bitnami.postgresql is not fully installed. You cannot execute commands
```
1. Is it possible to add this functionality to bitnami/postgres?
2. How can I make it work until it's implemented?
Adding sleep did not do the job...

Thank you!

**Comment by juan131** [comment]
Hi @liyaka 

Instead of adding your *init_db script(s)* to the Dockerfile definition, you need to edit the **(app-entroypoint.sh)[https://github.com/bitnami/bitnami-docker-postgresql/blob/master/10/rootfs/app-entrypoint.sh]** after initialising PostgreSQL

Anyway, I think we should include an easier way to run this kind of scripts. There is a similar request on MariaDB container (see https://github.com/bitnami/bitnami-docker-mysql/issues/41)

**Comment by tompizmor** [comment]
Yes, I think it makes sense to support this feature in our database containers as it seems it is very usual.

**Comment by liyaka** [comment]
I tried to add to the app-entrypoint.sh
```
echo
psql=( psql -v ON_ERROR_STOP=1 -U postgres -a )
for f in /docker-entrypoint-initdb.d/*; do
	case "$f" in
		*.sh)     echo "$0: running $f"; . "$f" ;;
		*.sql)    echo "$0: running $f"; "${psql[@]}" -f "$f"; echo ;;
		*.sql.gz) echo "$0: running $f"; gunzip -c "$f" | "${psql[@]}"; echo ;;
		*)        echo "$0: ignoring $f" ;;
	esac
	echo
done
```

and I get this error:
```
nami    INFO  Initializing postgresql
postgre INFO  ==> Creating postgres user with unrestricted access...
postgre INFO  ==> Configuring replication parameters...
postgre INFO 
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Password: Not set during installation
postgre INFO   (Passwords are not shown for security reasons)
postgre INFO  ########################################################################
postgre INFO 
nami    INFO  postgresql successfully initialized
INFO  ==> Starting postgresql... 

/app-entrypoint.sh: running /docker-entrypoint-initdb.d/db-init.sql
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by juan131** [comment]
Did you try indicating `127.0.0.1` as hostname? It looks like if it's trying to connect using a socket instead of `host:port`

**Comment by liyaka** [comment]
Hi @juan131 
Did you try to run it?
When ```nami start --foreground postgresql``` runs, nothing runs after it...
This is what worked for me eventually:
I added **init_db.sh**:
```
#!/bin/bash -e

until pg_isready
do
    echo "."
    sleep 1
done
sleep 2

echo
psql=( psql -v ON_ERROR_STOP=1 -U postgres -a )
for f in /docker-entrypoint-initdb.d/*; do
	case "$f" in
		*.sh)     echo "$0: running $f"; . "$f" ;;
		*.sql)    echo "$0: running $f"; "${psql[@]}" -f "$f"; echo ;;
		*.sql.gz) echo "$0: running $f"; gunzip -c "$f" | "${psql[@]}"; echo ;;
		*)        echo "$0: ignoring $f" ;;
	esac
	echo
done
```
Changed **app-entrypoint.sh** to this:
```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

nami_initialize postgresql
info "Starting postgresql... "

./init_db.sh &
exec tini -- nami start --foreground postgresql
```
my **Dockerfile**:
```
FROM bitnami/postgresql:9.6

COPY db-init.sql /docker-entrypoint-initdb.d/
COPY app-entrypoint.sh init_db.sh /
RUN chmod +x /*.sh

CMD [""]
```

**Comment by juan131** [comment]
Hi @liyaka 

Great!! The problem was that PostgreSQL was not running when you tried to connect to it but it's great the way you implemented to wait until it's ready so you can populate. 

As I mentioned, we plan to include an an easier way to run initialisation scripts so you can populate your databases during the container creation.
