### ISSUE TITLE
Postgis

### ISSUE THREAD

**Issue by kkalugerov** [bitnami/bitnami-docker-postgresql#85]
Hello there, I would like to ask you if there is a way to add postgis to latest postgresql 10 for which you have developed a Dockerfile :?

**Comment by rafariossaa** [comment]
Hi,
  One way of doing this is cloning the repository and adding the postgis package to the RUN install line in the Dockerfile, then you need to build a the image and the run a container using the images you have just built.

  Hope this helps

**Comment by kkalugerov** [comment]
Something like you are doing here -> RUN bitnami-pkg unpack postgresql-10.4.0-2 --checksum fc09c88d5f1f8d9b280b45654bc3ea942b92a9d5009b199f402641ae7ba3ae10 :?

**Comment by rafariossaa** [comment]
Let me check it to give you appropriate directions.

**Comment by kkalugerov** [comment]
@rafariossaa  any progress :? :)

**Comment by rafariossaa** [comment]
HI,
  For now we are not releasing an image with postgis, and adding postgis through bitnami tooling is not immediate.
  What you can do is follow the official installations steps from postgis. In our images postgres is installed on /opt/bitnami/postgresql/ , so maybe you would need to adjust con configuration in the compilations steps.
  If you want to be able to generate new images, add your steps to the RUN directives in the dockerfile. For new containers for the same image, commit your changes to a new images.

**Comment by rafariossaa** [comment]
Hi @knopkodav,
  When you need to go through all those steps not much can be done.

  As you get a solution for this issue, I will mark it as solved.

Thanks for giving your solution,
Rafael Rios

**Comment by magicalbanana** [comment]
@knopkodav can you share your Dockerfile? I'm trying to do this as well but I'm unable to do so.

**Comment by willaustin** [comment]
I had to do the following to get it to work:

```
FROM bitnami/postgresql:10.6.0

USER root

RUN apt update && apt install -y postgis

USER 1001
```

Don't forget to shell in after it's running and create the extension from the psql client
```
postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION
postgres=# SELECT PostGIS_full_version();
                                                                               postgis_full_version

-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------
 POSTGIS="2.4.0 r15853" PGSQL="100" GEOS="3.5.1-CAPI-1.9.1 r4246" PROJ="Rel. 4.9.3, 15 August 2016" G
DAL="GDAL 2.1.2, released 2016/10/24" LIBXML="2.9.4" LIBJSON="0.12.1" RASTER
(1 row)
```

**Comment by tompizmor** [comment]
Thanks @willaustin!

**Comment by sylv3r** [comment]
@willaustin I see a huge problem here though :

**Comment by tompizmor** [comment]
@sylv3r I created a git repo in `/opt/bitnami/postgresql` before install the postgis extension and these is the list of new files added:

```
	bin/pgsql2shp
	bin/raster2pgsql
	bin/shp2pgsql
	lib/address_standardizer-2.4.so
	lib/postgis-2.4.so
	lib/postgis_topology-2.4.so
	lib/rtpostgis-2.4.so
	share/contrib/
	share/doc/
	share/extension/address_standardizer--1.0--2.4.0.sql
	share/extension/address_standardizer--2.4.0--2.4.0next.sql
	share/extension/address_standardizer--2.4.0.sql
	share/extension/address_standardizer--2.4.0next--2.4.0.sql
	share/extension/address_standardizer.control
	share/extension/address_standardizer.sql
	share/extension/address_standardizer_data_us--2.4.0--2.4.0next.sql
	share/extension/address_standardizer_data_us--2.4.0.sql
	share/extension/address_standardizer_data_us--2.4.0next--2.4.0.sql
	share/extension/address_standardizer_data_us.control
	share/extension/address_standardizer_data_us.sql
	share/extension/postgis--2.0.0--2.4.0.sql
	share/extension/postgis--2.0.1--2.4.0.sql
	share/extension/postgis--2.0.2--2.4.0.sql
	share/extension/postgis--2.0.3--2.4.0.sql
	share/extension/postgis--2.0.4--2.4.0.sql
	share/extension/postgis--2.0.5--2.4.0.sql
	share/extension/postgis--2.0.6--2.4.0.sql
	share/extension/postgis--2.0.7--2.4.0.sql
	share/extension/postgis--2.1.0--2.4.0.sql
	share/extension/postgis--2.1.1--2.4.0.sql
	share/extension/postgis--2.1.2--2.4.0.sql
	share/extension/postgis--2.1.3--2.4.0.sql
	share/extension/postgis--2.1.4--2.4.0.sql
	share/extension/postgis--2.1.5--2.4.0.sql
	share/extension/postgis--2.1.6--2.4.0.sql
	share/extension/postgis--2.1.7--2.4.0.sql
	share/extension/postgis--2.1.8--2.4.0.sql
	share/extension/postgis--2.1.9--2.4.0.sql
	share/extension/postgis--2.2.0--2.4.0.sql
	share/extension/postgis--2.2.1--2.4.0.sql
	share/extension/postgis--2.2.2--2.4.0.sql
	share/extension/postgis--2.2.3--2.4.0.sql
	share/extension/postgis--2.2.4--2.4.0.sql
	share/extension/postgis--2.2.5--2.4.0.sql
	share/extension/postgis--2.3.0--2.4.0.sql
	share/extension/postgis--2.3.1--2.4.0.sql
	share/extension/postgis--2.3.2--2.4.0.sql
	share/extension/postgis--2.3.3--2.4.0.sql
	share/extension/postgis--2.4.0--2.4.0next.sql
	share/extension/postgis--2.4.0.sql
	share/extension/postgis--2.4.0alpha--2.4.0.sql
	share/extension/postgis--2.4.0beta1--2.4.0.sql
	share/extension/postgis--2.4.0dev--2.4.0.sql
	share/extension/postgis--2.4.0next--2.4.0.sql
	share/extension/postgis--2.4.0rc1--2.4.0.sql
	share/extension/postgis--2.4.0rc2--2.4.0.sql
	share/extension/postgis--2.4.0rc3--2.4.0.sql
	share/extension/postgis--unpackaged--2.4.0.sql
	share/extension/postgis.control
	share/extension/postgis_tiger_geocoder--2.0.0--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.1--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.2--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.3--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.4--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.5--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.6--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.0.7--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.0--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.1--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.2--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.3--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.4--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.5--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.6--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.7--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.8--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.1.9--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.2.0--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.2.1--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.2.2--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.2.3--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.2.4--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.2.5--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.3.0--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.3.1--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.3.2--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.3.3--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0--2.4.0next.sql
	share/extension/postgis_tiger_geocoder--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0alpha--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0beta1--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0dev--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0next--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0rc1--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0rc2--2.4.0.sql
	share/extension/postgis_tiger_geocoder--2.4.0rc3--2.4.0.sql
	share/extension/postgis_tiger_geocoder--unpackaged--2.4.0.sql
	share/extension/postgis_tiger_geocoder.control
	share/extension/postgis_tiger_geocoder.sql
	share/extension/postgis_topology--2.0.0--2.4.0.sql
	share/extension/postgis_topology--2.0.1--2.4.0.sql
	share/extension/postgis_topology--2.0.2--2.4.0.sql
	share/extension/postgis_topology--2.0.3--2.4.0.sql
	share/extension/postgis_topology--2.0.4--2.4.0.sql
	share/extension/postgis_topology--2.0.5--2.4.0.sql
	share/extension/postgis_topology--2.0.6--2.4.0.sql
	share/extension/postgis_topology--2.0.7--2.4.0.sql
	share/extension/postgis_topology--2.1.0--2.4.0.sql
	share/extension/postgis_topology--2.1.1--2.4.0.sql
	share/extension/postgis_topology--2.1.2--2.4.0.sql
	share/extension/postgis_topology--2.1.3--2.4.0.sql
	share/extension/postgis_topology--2.1.4--2.4.0.sql
	share/extension/postgis_topology--2.1.5--2.4.0.sql
	share/extension/postgis_topology--2.1.6--2.4.0.sql
	share/extension/postgis_topology--2.1.7--2.4.0.sql
	share/extension/postgis_topology--2.1.8--2.4.0.sql
	share/extension/postgis_topology--2.1.9--2.4.0.sql
	share/extension/postgis_topology--2.2.0--2.4.0.sql
	share/extension/postgis_topology--2.2.1--2.4.0.sql
	share/extension/postgis_topology--2.2.2--2.4.0.sql
	share/extension/postgis_topology--2.2.3--2.4.0.sql
	share/extension/postgis_topology--2.2.4--2.4.0.sql
	share/extension/postgis_topology--2.2.5--2.4.0.sql
	share/extension/postgis_topology--2.3.0--2.4.0.sql
	share/extension/postgis_topology--2.3.1--2.4.0.sql
	share/extension/postgis_topology--2.3.2--2.4.0.sql
	share/extension/postgis_topology--2.3.3--2.4.0.sql
	share/extension/postgis_topology--2.4.0--2.4.0next.sql
	share/extension/postgis_topology--2.4.0.sql
	share/extension/postgis_topology--2.4.0alpha--2.4.0.sql
	share/extension/postgis_topology--2.4.0beta1--2.4.0.sql
	share/extension/postgis_topology--2.4.0dev--2.4.0.sql
	share/extension/postgis_topology--2.4.0next--2.4.0.sql
	share/extension/postgis_topology--2.4.0rc1--2.4.0.sql
	share/extension/postgis_topology--2.4.0rc2--2.4.0.sql
	share/extension/postgis_topology--2.4.0rc3--2.4.0.sql
	share/extension/postgis_topology--unpackaged--2.4.0.sql
	share/extension/postgis_topology.control
```

Maybe it is possible to reduce the docker image size by copying the whole `/opt/bitnami/postgresql` dir.

**Comment by sylv3r** [comment]
@tompizmor unfortunately the heavy stuff is in `libgdal-dev` which is a required shared library.
It could maybe be possible to isolate only the stuff needed from here, but that's heavy work and at the end handling an heavy image is cheaper than trying to figure out how to have the smallest one.
Thanks for having try !

**Comment by tompizmor** [comment]
You're welcome! Please don't hesitate to ask if you have any other question!

**Comment by coltmeister** [comment]
For anyone else having this issue and wanting a quick fix, I created a public docker image prebundled with postgis and postgres-contrib from the bitnami postgres image. 

The git repo is located [here](https://github.com/coltmeister/bitnami-postgis) and the docker repo is located [here](https://cloud.docker.com/repository/docker/coltonsberry/bitnami-postgis). (`coltonsberry/bitnami-postgis`).

**Comment by tompizmor** [comment]
Thanks for that @coltmeister! We will definitely take a look!

**Comment by Amithpn** [comment]
I built the postgres image by adding postgis install steps. But container is refusing to start. Below is the exception: 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/app-entrypoint.sh\": permission denied": unknown.

Any idea whats the exception might be?

**Comment by tompizmor** [comment]
Either your container user doesn't have permissions to execute the `/app-entrypoint.sh` script, or the script itself doesn't have execution permissions.

If you share your Dockerfile I can give it a try

**Comment by Amithpn** [comment]
Hi @tompizmor , Below is the docker file i used to build the image. 

`FROM bitnami/minideb-extras-base:stretch-r259

ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
    HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-9" \
    OS_NAME="linux"

# Install required system packages and dependencies
RUN install_packages libbsd0 libc6 libedit2 libgcc1 libicu57 liblzma5 libncurses5 libnss-wrapper libssl1.1 libstdc++6 libtinfo5 libxml2 libxslt1.1 locales zlib1g
RUN . ./libcomponent.sh && component_unpack "postgresql" "10.8.0-2" --checksum 926e5842cbe9bee8e600bbc0b553e7dbcd5da44d3bdfff279a13132b817d0764
RUN echo 'en_GB.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen

## Install Postgis
RUN install_packages wget gcc make build-essential libxml2-dev libgeos-dev libproj-dev libgdal-dev \
    && cd /tmp \
    && wget "http://download.osgeo.org/postgis/source/postgis-2.4.0.tar.gz" \
    && export C_INCLUDE_PATH=/opt/bitnami/postgresql/include/:/opt/bitnami/common/include/ \
    && export LIBRARY_PATH=/opt/bitnami/postgresql/lib/:/opt/bitnami/common/lib/ \
    && export LD_LIBRARY_PATH=/opt/bitnami/postgresql/lib/:/opt/bitnami/common/lib/ \
    && tar zxf postgis-2.4.0.tar.gz && cd postgis-2.4.0 \
    && ./configure --with-pgconfig=/opt/bitnami/postgresql/bin/pg_config \
    && make \
    && make install

COPY rootfs /
RUN /postunpack.sh
ENV BITNAMI_APP_NAME="postgresql" \
    BITNAMI_IMAGE_VERSION="10.8.0-debian-9-r28" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    NAMI_PREFIX="/.nami" \
    NSS_WRAPPER_LIB="/usr/lib/libnss_wrapper.so" \
    PATH="/opt/bitnami/postgresql/bin:$PATH"

VOLUME [ "/bitnami/postgresql", "/docker-entrypoint-initdb.d" ]

EXPOSE 5432

USER 1001
ENTRYPOINT ["sh", "/entrypoint.sh" ]
CMD [ "/run.sh" ]`

Image is getting build successfully, after i run the image using the command: docker run -it db74a67c4635 bash, im getting below exception.

`[user@dev-server ~]# docker run -it db74a67c4635 bash
/entrypoint.sh: 5: set: Illegal option -o pipefail
[user@dev-server ~]#`

Dockerfile i have copied from here: https://github.com/bitnami/bitnami-docker-postgresql/blob/10.8.0-debian-9-r28/10/debian-9/Dockerfile

Let me know what might be the exception.

**Comment by Amithpn** [comment]
Hi All,
Below is the working postgressql Dockerfile with Postgis Support.

`FROM bitnami/postgresql:10.6.0

USER root

RUN install_packages wget gcc make build-essential libxml2-dev libgeos-dev libproj-dev libgdal-dev \
    && cd /tmp \
    && wget "http://download.osgeo.org/postgis/source/postgis-2.4.7.tar.gz" \
    && export C_INCLUDE_PATH=/opt/bitnami/postgresql/include/:/opt/bitnami/common/include/ \
    && export LIBRARY_PATH=/opt/bitnami/postgresql/lib/:/opt/bitnami/common/lib/ \
    && export LD_LIBRARY_PATH=/opt/bitnami/postgresql/lib/:/opt/bitnami/common/lib/ \
    && tar zxf postgis-2.4.7.tar.gz && cd postgis-2.4.7 \
    && ./configure --with-pgconfig=/opt/bitnami/postgresql/bin/pg_config \
    && make \
    && make install

USER 1001`

All features related to postgis works with this image

**Comment by tompizmor** [comment]
Thanks @Amithpn!

I have tried the new Dockerfile and works fine.

(I updated your comment so the Dockerfile can be copy/paste)

**Comment by sicksid** [comment]
guys have you had this issue before?

`
ERROR:  permission denied to create extension "postgis"
HINT:  Must be superuser to create this extension.
STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis
`
when running django tests?

**Comment by sicksid** [comment]
nvm i had to do it manually and it all works properly
basically running
`docker-compose exec db sh -c 'psql -U postgres -c "create extension postgis;"'`

**Comment by tompizmor** [comment]
Thanks for updating the issue. I am glad you find a workaround.
