### ISSUE TITLE
RFE: redirect postgresql logs to stderr directly (current implementation misses logs when PostgreSQL crashes on start)

### ISSUE THREAD

**Issue by intelfx** [bitnami/bitnami-docker-postgresql#88]
**Description**

It appears that Bitnami-specific PostgreSQL wrappers have it write its logs to `/opt/bitnami/logs/postgresql.log` and then `tail -f` that file to stderr. This is suboptimal and misses logs when the process crashes very early, see e. g. helm/charts#8830.

The RFE is to make postgresql log directly to stderr.

**Steps to reproduce the issue:**

1. Reproduce the setup in helm/charts#8830
2. Observe no actual error logs in `kubectl logs`
3. Patch the StatefulSet to not exit after crash, exec into the failing Pod, observe missed logs in `/opt/bitnami/logs/postgresql.log` that were never forwarded to stderr but are vital for diagnosing the actual error

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

k8s, but this shouldn't be significant.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. Currently, the container is using `pg_ctl` to start the database. In this sense, it may make more sense to use the postgresql command so it stays in the foreground and thus we do not miss any logs. We will take a look at how to change the configuration

**Comment by intelfx** [comment]
I believe `pg_ctl` writes logs to stdout by default.

Where can I take a look at the actual commands used to initialize and start PostgreSQL? Sources for your PostgreSQL "Bitnami package"?

**Comment by javsalgar** [comment]
Apart from the container logic shown in this repo, you can take a look, inside the container, in the `/root/.nami/components/com.bitnami.postgresql` folder. There you will see the nami JS files for initializing. For the startup script take a look at the nami.json file.
