### ISSUE TITLE
how can I enable stats?

### ISSUE THREAD

**Issue by berlinguyinca** [bitnami/bitnami-docker-postgresql#89]
dear all,

how can I do:

```
CREATE extension pg_stat_statements;
```

for a database at create and in the configuration file, specify the required options?

kind regards

**Comment by berlinguyinca** [comment]
thank you for your reply.

**Comment by juan131** [comment]
HI @berlinguyinca 

I proceed to close this issue. Please do not hesitate to reopen it if you require further assistance.
