### ISSUE TITLE
RFE: uncomment `include_dir = 'conf.d'` in the default PostgreSQL config

### ISSUE THREAD

**Issue by intelfx** [bitnami/bitnami-docker-postgresql#90]
The title says it all, really.

It would be nice to uncomment this line in the default `/opt/bitnami/postgresql/conf/postgresql.conf`:

```
#------------------------------------------------------------------------------
# CONFIG FILE INCLUDES
#------------------------------------------------------------------------------

# These options allow settings to be loaded from files other than the
# default postgresql.conf.

#include_dir = 'conf.d'                 # include files ending in '.conf' from
                                        # directory 'conf.d'
```

**Comment by tompizmor** [comment]
Hi @intelfx,

Thanks for creating the issue! It makes total sense to us. 
We have written this down and will work to include the feature in future releases.

**Comment by carrodher** [comment]
I just added the logic to support the `include_dir` directive, I documented the use of this configuration in the README: https://github.com/bitnami/bitnami-docker-postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf

@intelfx can you take a look? Thanks!

**Comment by intelfx** [comment]
@carrodher It appears to work on this side. However, the Helm-side support is still inadequate for our needs; I've commented in the helm/charts#8916.

**Comment by tompizmor** [comment]
Thanks! We will take a look
