### ISSUE TITLE
Checksum verification fails

### ISSUE THREAD

**Issue by vhelke** [bitnami/bitnami-docker-postgresql#93]
Hi,

I am trying to build the Postgres-image using the following Dockerfile:
bitnami-docker-postgresql/10/debian-9/Dockerfile

I cannot proceed any further since the checksum verification fails.

```
Step 5/12 : RUN bitnami-pkg unpack postgresql-10.5.0-7 --checksum 390f7360f22f4cccc170c3fe00fcb5f1f5e5fa5133c4f64e6b37209783a049f3
 ---> Running in b814654ec16f
INFO  ==> Downloading postgresql-10.5.0-7-linux-amd64-debian-9 package
INFO  ==> Verifying package integrity
sha256sum: WARNING: 1 computed checksum did NOT match
postgresql-10.5.0-7-linux-amd64-debian-9.tar.gz: FAILED
The command '/bin/sh -c bitnami-pkg unpack postgresql-10.5.0-7 --checksum 390f7360f22f4cccc170c3fe00fcb5f1f5e5fa5133c4f64e6b37209783a049f3' returned a non-zero code: 1
```

Testing was done using the current latest (Commit: 095956fe214f95de256463f6947743e95796de0a)

**Comment by rafariossaa** [comment]
Hi @vhelke ,
  Thanks for reporting this issue, we are currently fixing it.
  I will notice you as soon as this is fixed.
  
Thanks forehand,
Rafael Rios

**Comment by rafariossaa** [comment]
Hi @vhelke ,
  We have released a new update that fix this problem.

Best Regrads,
Rafael Rios
